### ISSUE TITLE
New Feature: Auto-Nudge

### ISSUE THREAD

**Issue by iradicus** [ec-/Quake3e#10]
I added a simple but effective enhancement to a copy of the source code that I think would be beneficial to everyone. So I am putting my code snippet here so you can consider if you want to incorporate it or not.

The feature is auto-nudge which is basically automatic time nudge that uses your average ping as the time nudge value. (It is also not limited by the -30 to 30 nudge range). It is so simple to implement I'm surprised it was not already a feature. In my testing I am able to play competitively with even 150ms ping (and even better with lower).

I'm not sure if there are legitimate reasons why you may not want to implement this (people might consider it unfair advantage??). It just helps you play unlagged, so if anything I think it just helps equal the playing field for people with higher ping vs people with lower ping. Or maybe the results wont be as good for other people (different connections), so I don't know. I leave it up to you but works great for me.

First you need to define a new client variable called: cl_autoNudge (integer)
Then add the following function to cl_cgame.c

```
/*
==================
CL_AvgPing
Calculates Average Ping from snapshots in buffer. Used by AutoNudge.
==================
*/
int CL_AvgPing( void ) {
	int avgPing = 0;
	int count = 0;
	int i;

	for ( i = 0 ; i < PACKET_BACKUP ; i++ ) {
		if ( cl.snapshots[i].ping > 0 && cl.snapshots[i].ping < 999 ) {
			avgPing += cl.snapshots[i].ping;
			count++;
		}
	}

	if ( count > 0 )
		avgPing = (int)((avgPing / count) + 0.5); // round
	
	return avgPing;
}

```
Last modify function CL_SetCGameTime function and modify the time nudge portion of logic:

```
                // cl_timeNudge is a user adjustable cvar that allows more
		// or less latency to be added in the interest of better 
		// smoothness or better responsiveness.

		if ( cl_autoNudge->integer == 1 )
			cl.serverTime = cls.realtime + cl.serverTimeDelta + CL_AvgPing();
		else
			cl.serverTime = cls.realtime + cl.serverTimeDelta - cl_timeNudge->integer;
```

That's it. Very simple.
I also made a few additional enhancements pertaining to console (unrelated). But another feature which I think would be beneficial to all is cl_infoLevel (0 = All, 1 = Warnings & Errors, 2 = Errors Only), which controls the verbosity of the output to client console.

**Comment by ensiform** [comment]
While I'm sure many will like this, timenudge has a lot of placebo and lacking of empirical evidence that it does any good beside changing the ping number.

It does however have many caveats, including but not limited to prediction errors, and negative impact of timing delay vs the server.

**Comment by ec-** [comment]
@iradicus how does it interacts with unlagged mods?

**Comment by iradicus** [comment]
@ec- I only found an insta-unlagged server to try it on (in Germany), but with 150ms ping and auto-nudge 1 it felt like LAN game making rail shots no problem. I felt accuracy was better with auto-nudge on than off.

Since my original post I made some additional changes to the auto-nudge logic that I think make it more flexible.

1) I made cl_autonudge a float (range 0 to 1.0) so it can be used as auto nudge factor of ping.
So if you set cl_autonudge 0.333, and have avg ping of 150 then timenudge value becomes
(150 * 0.333) =~ (50)  * -1 = -50

2) I changed the average ping calculation to use median average instead of mean average, due to cases of fluctuating ping with extreme highs and lows that could effect the average.

3) I made CL_TimeNudge a function that returns either autoNudged value or cl_timeNudge depending on if autonudge is being used.

Here are the revised functions:

```
*
==================
CL_AvgPing
Calculates Average Ping from snapshots in buffer. Used by AutoNudge.
==================
*/
float CL_AvgPing( void ) {
	int ping[PACKET_BACKUP];
	int count = 0;
	int i, j, iTemp;
	float result;

	for ( i = 0; i < PACKET_BACKUP; i++ ) {
		if ( cl.snapshots[i].ping > 0 && cl.snapshots[i].ping < 999 ) {
			ping[count] = cl.snapshots[i].ping;
			count++;
		}
	}

	if ( count == 0 )
		return 0;

        // sort ping array
	for ( i = count - 1; i > 0; --i ) {
            for ( j = 0; j < i; ++j ) {
                if (ping[j] > ping[j + 1]) {
                    iTemp = ping[j];
                    ping[j] = ping[j + 1];
                    ping[j + 1] = iTemp;
                }
            }
      }

    // use median average ping
    if ( (count % 2) == 0 )
        result = (ping[count / 2] + ping[(count / 2) - 1]) / 2.0;
    else
	result = ping[count / 2];

	return result;
}


/*
==================
CL_TimeNudge
Returns either auto-nudge or cl_timeNudge value.
==================
*/
int CL_TimeNudge( void ) {
	float autoNudge = cl_autoNudge->value;

	if ( autoNudge != 0 )
		return (int)((CL_AvgPing() * autoNudge) + 0.5) * -1;
	else
		return cl_timeNudge->integer;
}
```
Then you just have to change one line of code in CL_SetCGameTime method:
```
// cl.serverTime = cls.realtime + cl.serverTimeDelta - cl_timeNudge->integer;
cl.serverTime = cls.realtime + cl.serverTimeDelta - CL_TimeNudge();
```

**Comment by ec-** [comment]
Well, pretty much every improvement that increases FPS (for example) might be considered as _unfair_ too so I don't see any problems here, it is a nice feature
