### ISSUE TITLE
Regressions: chat text flickering + ESC key for consoile

### ISSUE THREAD

**Issue by uzum4ki** [ec-/Quake3e#103]
Hello, the chat text displayed on the upper left part of the screen is flickering since release 2021-01-16.
Also, the latest published release (13 hrs ago at the time of writing, https://github.com/ec-/Quake3e/commit/e982ad6ca8f36c0ee75378bc26896371ff1cc9fe) does not provide the ESCape key to open the console (shift+ESc still works tho)

**Comment by ensiform** [comment]
Escape key has never opened the console?

**Comment by ec-** [comment]
I can't reproduce that - what OS/GPU/WM you have, can you capture video with this? It may be useful to see your `q3config.cfg` too

**Comment by uzum4ki** [comment]
Thanks for the feedback. I know have a doubt about the ESC key but I'm pretty sure it was working before... I'll try with earlier version and state about it. It happens either on GNU/Linux (Debian Buster aka "stable" running XFCE with Nvidia) and on a Windows 10 Laptop (up-to-date at the time of writing with a Nvidia GPU too). I'm not able to do it for now but I'll try to capture the flickering effect ASAP and provide the q3config either (which was without any pbm until the version mentioned earlier).

**Comment by KuehnhammerTobias** [comment]
The escape key never opened the console. I think you mean the key beyond ESC (tilde key), this one was opening the console before. Since we now have SDL, we'll run into the same issues here as well, see: https://github.com/ioquake/ioq3/pull/285
I'm not saying the issue is the same, just the problem will be the same I think.
I can't imagine that the flickering console text is related to key bindings, though.

**Comment by uzum4ki** [comment]
Hello and sorry for the delay.
@ToKu: you're right, this is the key _below_ the ESC key which used to work but doesn't work anymore on Linux (but still works on Windows). So yes, it's probably SDL related and thus I guess there is no chance to get it back...
Anyway, sure, this is not related to the text flickering issue (i probably should have done 2 tickets instead of one), which happens to both Linux and Windows. Here is a quick GIF showing the visual artefact. I'll upload my q3config when I'm at home tonight.
![quake3e-flickering](https://user-images.githubusercontent.com/7620856/112972521-9fd6d580-9150-11eb-8355-4fc213129b5b.gif)

**Comment by ec-** [comment]
Flickering should be fixed now, check recent build/sources

**Comment by uzum4ki** [comment]
@ec- : I tested the Windows version of your last build ([0308f60](https://github.com/ec-/Quake3e/commit/0308f600259b51f9ce4c2b29183dd2c1576767dc)) and yes, the text flickering has disappeared, thanx!
And, I guess i know the answer but is there any chance to have the console working the "old way" on Linux?
Anyway thank you for quick fix

**Comment by uzum4ki** [comment]
@ec- Sorry for the long delay... yes it works when compiled with USE_SDL=0.
Thank you very much!

**Comment by ensiform** [comment]
Ideally though you should probably use SDL on binaries on Linux especially for vulkan renderer. Which keyboard layout is used?

**Comment by uzum4ki** [comment]
I'm using a french AZERTY keyboard and a compil without SDL works just fine to me.

**Comment by ensiform** [comment]
What key / chars are on the key left of the 1 and under escape.

**Comment by uzum4ki** [comment]
this is the key for "power of 2", here is a picture of the french azerty layout:
![500px-KB_France svg](https://user-images.githubusercontent.com/7620856/115624269-ad6c1f00-a2fa-11eb-8f8d-56344f0f4309.png)
