### ISSUE TITLE
macOS video issues

### ISSUE THREAD

**Issue by quakelover** [ec-/Quake3e#104]
Two main problems (perhaps these should be separate issues? let me know):

1. The OpenGL version handles fullscreen but is too slow to play. The cursor and rendering lag so much that it cannot be played.
2. The vulkan version doesn't lag, but it doesn't properly fill up the window space (either windowed or fullscreen). See screenshot below:

<img width="2160" alt="Screen Shot 2021-03-11 at 1 51 42 PM" src="https://user-images.githubusercontent.com/80932985/111721143-8b274300-881c-11eb-8537-40a25e55b95f.png">

System info:

- os: catalina
- hw: MBP 2.5 GHz Quad-Core Intel Core i7 / AMD Radeon R9 M370X 2 GB

**Comment by ec-** [comment]
1) Please, show condump (exec `\condump 1.txt` in console and post contents of `1.txt` there) after client initialization
2) It looks like 2x window upscale, how recent your engine build?

**Comment by quakelover** [comment]
Using the latest build `d064a3f` here is my report:

### Quake3e macOS OpenGL build

Now in this build the lag has disappeared (awesome!), however a new weird bug has appeared, which is that anytime I click on something in the window, it takes me out of the app (note: I am in windowed mode, I couldn't test fullscreen because I each time I tried to click "Setup" it switched me out of the app, placing it in the background).

However, one time the mouse seemed to be acquired successfully, and I was able to click things finally to connect to a multiplayer server. Then suddenly, I think maybe I might've intentionally switched out of the app and back into it, the weird click-and-deactivate-app behavior returned. Attached in the output of `\condump q3e_opengl.txt`:

[q3e_opengl.txt](https://github.com/ec-/Quake3e/files/6174511/q3e_opengl.txt)

### Quake3e macOS Vulkan build

For this the behavior remained the same as above. Though there was no problem with clicking things, the 2x upscale you've observed (probably due to retina support) wasn't fixed. I immediately quit the game (after launching in windowed mode too):

[q3e_vulkan.txt](https://github.com/ec-/Quake3e/files/6174513/q3e_vulkan.txt)

**Comment by quakelover** [comment]
Oh, don't know if it matters but the computer happens to be plugged into an external monitor too, though I think the issue occurs either way.

**Comment by ec-** [comment]
Please, update to latest build
* Both backends using correct SDL functions to determine drawable side so I suspect that this is a SDL+Vulkan+cocoa bug
* As for accidental moves to backgroud - I can't reproduce it in VM (Catalina 10.15.6)
* Also I noticed `stencil(0-bits)` - this is not recommended, set `\r_stencilBits 8`

In vulkan log I see:
```
Available physical devices:
 0: Discrete AMD Radeon R9 M370X, 0x6821
 1: Integrated Intel Iris Pro Graphics, 0x0d26
```

So you may try using `\r_device 1` for example

**Comment by ec-** [comment]
It has been confirmed as [SDL bug](https://github.com/libsdl-org/SDL/commit/963c9495d3585f3d099df0fa750c72051380ef29#diff-491420423ac8b908eb1a5e8ada4e788114e40eb60e198119310351e35ebfc408):

`The GL2 program will report a drawable size of 2x window width and 2x window height, while the Vulkan program will report the window size`

So no real high-dpi support until next SDL release

**Comment by quakelover** [comment]
> So you may try using `\r_device 1` for example

Well, that would be the integrated graphics that I'd like to avoid using.

The good news is that you did something in the latest build that appears to have fixed everything ... even without the latest SDL release. Not sure what you did but the bug with the mouse clicking is gone from the OpenGL version, and both versions now work in fullscreen without issue, and the vulkan version no longer has the retina issue.

Thanks so much for fixing this!!!!

I'm gonna close this issue, but I have a final question that maybe you might know the answer to, which is, how do I persist settings across restarts? It seems like things like `\r_stencilBits 8` persist, but I had to restart the game several times to do it. Is there a more "correct" way of setting these variables besides simply typing them into the console? Or is that the right way to do it (and it should persist)?

**Comment by quakelover** [comment]
OK, weird thing: while Quake3e now works (for the most part) correctly, ioquake no longer does. Now ioquake3 has the red flickering and wrong proportionally sized window. Here are two screenshots showing the two colors the background flickers between when in fullscreen mode in ioquake3:

![Screen Shot 2021-03-20 at 5 46 30 PM](https://user-images.githubusercontent.com/80932985/111890169-331b4880-89a4-11eb-9cf9-c226d2157fb2.png)
![Screen Shot 2021-03-20 at 5 46 29 PM 2](https://user-images.githubusercontent.com/80932985/111890172-36aecf80-89a4-11eb-9fe5-0f1c38427055.png)

My guess is that the reason for this is because I have `~/.q3a` symlinked to `~/Library/Application Support/Quake3`, and now some setting that used to work correctly in ioquake3 is breaking ioquake3, but is correct for Quake3e...

Just some feedback in case it's useful. Also, repeating my question in case you didn't notice it above:

> but I have a final question that maybe you might know the answer to, which is, how do I persist settings across restarts? It seems like things like `\r_stencilBits 8` persist, but I had to restart the game several times to do it. Is there a more "correct" way of setting these variables besides simply typing them into the console? Or is that the right way to do it (and it should persist)?

**Comment by quakelover** [comment]
Here was another weird heisenbug that I noticed just now: everything was working fine and I put the machine to sleep. Then suddenly `./quake3e-vulkan` stopped taking hold of mouse. I could see the regular macOS mouse cursor visible and moving, and it wouldn't move the red target Quake3 cursor.

What mysteriously fixed it was running `./quake3e` (the OpenGL version). After running that, quitting it, and re-running `./quake3e-vulkan` it started working again. Let me know if you need anything...

**Comment by ec-** [comment]
To apply `\r_stencilBits 8` - single `\vid_restart` is enough, also it is 8 by default so no need in any actions when switching to new mods

Everything that depends from system (sleep/wake events, launching clients in a specific order etc.) is very likely to be unfixable from engine side.

ioquake3 doesn't call `*GetDrawableSize` funcions so its behavior is unpredictable
