### ISSUE TITLE
Anti-aliasing doesn't work

### ISSUE THREAD

**Issue by Lyckra** [ec-/Quake3e#105]
I have turned on anti-aliasing and I can see in the config file that it's on but it doesn't work in game. It also doesn't work when it's forced externally using the Nvidia Control Panel. I'm using a GTX 1080 Ti on Windows 10 with the latest Nvidia drivers.

**Comment by ec-** [comment]
Check if `\r_fbo 1` is set, you can't control it via 'control panels'
