### ISSUE TITLE
ERROR: program tried to overflow program stack

### ISSUE THREAD

**Issue by Mikomanus** [ec-/Quake3e#106]
Hi,

Linux server is crashing after few maps with following:

********************
ERROR: program tried to overflow program stack
********************
----- Server Shutdown (Server crashed: program tried to overflow program stack) -----

Running Ubuntu 20.04.2 LTS
quake3e.ded.x64 - 1e136ff.

I am not sure if there are any additional debug information possible to extract.

**Comment by Mikomanus** [comment]
ok i booted the server with +set vm_rtChecks 0 and so far not crash.

**Comment by ec-** [comment]
What mod you are using? At least ExcessivePlus is known for such behavior

**Comment by Mikomanus** [comment]
Hi, yes it is exessiveplus. But with the reCheck 0 everything is ok.
