### ISSUE TITLE
Feature Request: can you please include building of renderer2 in the MAKEFILE?

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#108]
Hi,
I know you guys don't like the second opengl renderer, but please at least add it to the MAKEFILE.
We can always set it to = 0 by default, so nobody will be affected. For development purposes having the 2nd opengl renderer would be awesome. Even if the compilation process fails, it's fine, I can fix and improve the renderer I think. Unfortunately, I really don't know how to add the renderer to the MAKEFILE in the most professional and effective way possible.
Thanks.

**Comment by ec-** [comment]
Ok, now it's your routine :P

**Comment by KuehnhammerTobias** [comment]
Thank you very much!
It's very likely I'll spam you with some renderer 2 pull requests now, feel free to ignore them, if you don't like them :)
I'm mainly concerned about GPU vertex skinned IQMs. I started a discussion here: https://discourse.ioquake.org/t/current-status-of-iqm-md5-models/1153, zturtleman spent so much time into this and I really want to see IQMs on Q3e.
Kind Regards!

**Comment by ec-** [comment]
If those pull requests does not break anything outside of renderer2 - sure I will apply them

**Comment by KuehnhammerTobias** [comment]
Yeah, everything outside will be unaffected, everything new will have a cvar if possible, and I can also #ifdef all changes, so changes will reside inside the code but will be inactive until someone wan't to use the changes. Though, personally I don't like #ifdef hell/mess.
Of course, you will decide/modify/skip pull requests, as you like.
