### ISSUE TITLE
"connection interrupted" in single player when com_maxfps>500

### ISSUE THREAD

**Issue by szabolcs-cs** [ec-/Quake3e#109]
My graphics card seems to have no problem producing 500 fps@4K, but setting `com_maxfps` above `500` creates stuttering and the "connection interrupted" error

**Comment by ec-** [comment]
Such high FPS produces side-effects because of (low) network packet rate and way how mod detects network interruptions, do not use more than 250 FPS for regular gameplay

**Comment by ec-** [comment]
If you want to measure highest FPS/performance enter following command:
`\timedemo 1; demo four`

**Comment by szabolcs-cs** [comment]
`\timedemo 1; demo four`
You guessed right, I just wanted to benchmark!
2022 fps at 4K... wow!
