### ISSUE TITLE
FPS very low in latest version

### ISSUE THREAD

**Issue by raspatan** [ec-/Quake3e#113]
Hi there. I compiled today (31st May) the latest version and FPS are massively low. Last time I compiled was late December and have been playing fine. Not sure which is the particular version that broke my FPS (based on [changelog](https://github.com/ec-/Quake3e/commit/8f423a0c14c5cc79dfb2eff2ddbdd371838f1642), could be 16 Jan, 28 Mar, or 27 May updates). I loaded my config and problem persists, which suggests problem might be a new command (or change in default value in one I have no defined). Any ideas how can I debug the problem?

On the positive side, it seems "bright lights" in open issue #80 is now resolved.

**Comment by KuehnhammerTobias** [comment]
There are builds available to the corresponding changes you mentioned (changelog). These builds are available here: https://github.com/ec-/Quake3e/releases (hit the Assets button and search for the correct build for your OS). This way you can narrow down which build introduced the FPS decrease.
Additionally it would help people to help you if you give abit more tech infos, what OS are you using, which renderer is affected (opengl, vulkan)?

**Comment by raspatan** [comment]
@KuehnhammerTobias Thanks. Did that and problem is the latest release. March's version is fine for FPS (but issue #80 is not resolved). Additionally, I did not pay attention to the compilation but there are some warnings. [Here](https://paste.ubuntu.com/p/KZ4rq8D3Tq/) is the console output. My machine:

    VERSION: 1.32e  
    PLATFORM: linux [ubuntu 20.04]    
    ARCH: x86_64
    COMPILE_PLATFORM: linux
    COMPILE_ARCH: x86_64

**Comment by KuehnhammerTobias** [comment]
Thanks for the details. Please open the console and type:
_/cl_renderer_
than hit ENTER. Now you can see which renderer you are currently using.
**opengl** (= the default one)
**vulkan**
**opengl2**
You can also change the renderer on the fly by typing _/cl_renderer_ again and now add the renderer you want to use, for example
_/cl_renderer vulkan_
do a video restart by typing: _/vid_restart_
than hit ENTER, now the desired renderer is loaded.
Please note, that the opengl2 renderer is broken in many ways and is NOT recomended for the moment.
The vulkan renderer seems incredibly fast (at least on my machine) but vulkan has still some slow downs, and crashes from time to time.

**Comment by ensiform** [comment]
cl_renderer isn't used by default in the prebuilt files. Separate binaries are generated to use the corresponding one. Quake3e vulkan and such

**Comment by KuehnhammerTobias** [comment]
Uh oh, I didn't know this, @ensiform!
Well, somehow I think @raspatan uses opengl2 atm (maybe tried once, but fall-back was default opengl, now it's available etc., or transfered from an old ioq3 cfg, idk).

**Comment by ec-** [comment]
I looks like that you're using `opengl2` renderer for some reason, try compiling with `USE_RENDERER_DLOPEN=0` and `USE_VULKAN=1`

**Comment by raspatan** [comment]
Thanks all. Compiled with USE_RENDERER_DLOPEN=0` and it works fine, with no warnings when compiling (but issue #80 is not resolved). 
Then compiled with `USE_VULKAN=1' only and same problems like the beginning (with issue #80 solved and warnings when compiling). Here the output are 5 files (two .x64 files and thre .so files).
Then tried both together and it works **amazing** (however, issue #80 is still not resolved). NEver used Vulkan before but it is way faster.

So the question is, why since 27-05 version default (`make`) compilation uses the "wrong" opengl? Same command creates no problem in previous versions.
Also, why does the "wrong" opengl solves issue #80?
Over to you.

**Comment by KuehnhammerTobias** [comment]
I think it is better doing things step-by-step and not mixing up too many things.
Can you guarantee you are using opengl and NOT opengl2?
Is the main issue (FPS) gone than?
Issue 80 is not related to the FPS issue, right?
Please stick to naming sheme what do you mean by 'wrong' renderer?
If the FPS issue is related to opengl2 than you should be okay to make sure you are using opengl.

**Comment by ensiform** [comment]
Opengl2 renderer isn't even available unless self built or someone else built though

**Comment by raspatan** [comment]
@ensiform I compiled myself from source using `make`. That's why it was available (I think). 
@KuehnhammerTobias I don't know how to check opengl under use. But I implemented ec- suggestions step by step. By "wrong" I meant broken (opengl2), as you called it.
I thought compiling with `make` and nothing else would produce default opengl but that caused problems, whereas specifying `USE_RENDERER_DLOPEN=0` solved the problem. So I'm confused about how to get default to compile.

I haven't checked byt my config and the autoexec one could be contaminating things. Will try with clean game.

**Comment by ensiform** [comment]
The default compilation should be already with dlopen option off. And not "gl2" renderer, which is the ioquake3 higher end renderer and barely supported by quake3e if at all.

**Comment by KuehnhammerTobias** [comment]
Hmm, this means the FPS decrease must occur with the default opengl renderer than?
I recompiled the latest source and can't find any FPS difference of the latest opengl renderer and any previous source version.
@raspatan can you please tell me on which map the FPS decrease is most noteable?

**Comment by raspatan** [comment]
Ok, so for some reason (ioquake3-inherited probably), my config had `cl_renderer= "opengl2"`. When changing from inside to opengl or vulkan, it worked fine.

What puzzles me still is why my config was ok in the pre 27-05 version of the engine. The issue only happened in the latest version. Did you change the default compilation settings so that now it produces the three versions (opengl, opengl2, vulkan) whereas before it did not? That is at least my experience. For instance, when compiling latest version with `make` it produces the three of them. When compiling March's version with `make` it only produces opengl and vulkan versions.

PD:  I also realised there is some other setting (a `r_...` setting most likely) producing my weird lighting (#80), so will have to debug that separately.

**Comment by raspatan** [comment]
Ok, I can see now. Indeed you added it! Closed issue #108 is precisely about this. So problem was in the end my inherited config from ioq3. I only moved to Quake3e last December. This solved the mystery, it seems!

**Comment by KuehnhammerTobias** [comment]
Yeah, that is what I suspected, I know many people that switched from ioq3 to Q3e and inherited the config from ioq3 with opengl2 enabled.
Hopefully someday the second renderer will be usable too, as some of us are used to.

**Comment by raspatan** [comment]
Yes. Would be good to avoid this problem in the future but don't know how to in light of the three renders being included by default.

Anyway, I think this issue is now resolved so will close it. Thanks everyone!

**Comment by ec-** [comment]
I am disabled opengl2 by default from now
