### ISSUE TITLE
Remove Checks for Quake 3 point Release assets when using +set fs_game

### ISSUE THREAD

**Issue by senposage** [ec-/Quake3e#121]
When using +set fs_game to run a stand alone mod the executable still looks for the quake 3 point release assets even if they are not required by the stand alone mod

**Comment by ensiform** [comment]
fs_game by itself does not imply standalone.

Maybe fs_basegame?

**Comment by ec-** [comment]
As mentioned above - use `fs_basegame` value other than `baseq3` or `demoq3`, for example - `baseoa`
