### ISSUE TITLE
Disable QVM?

### ISSUE THREAD

**Issue by Sondro** [ec-/Quake3e#122]
Alright, I think I got it to work by adding  to my config.cfg: 
```
seta sv_pure "0" 
seta vm_cgame "0" 
seta vm_game "0" 
seta vm_ui "0"
```

But It appears the baseq3 .pk3s don't have dlls & must use qvms?
 
I'm getting "VM_LoadDLL' "..." failed.

---------------------------------------------------------------------------
Hi.

Is it possible to disable the QVM?

I was able to load a null QVM by commenting out some code & got the menus & player model working, but it dies on stage load with a null qvm error.

Using "./quake3e.x64 +set sv_pure 0 +set vm_cgame 0 +set vm_game 0 +set vm_ui 0" & added them to my config.cfg, but it doesn't seem to stop qvms from loading.

**Comment by Sondro** [comment]
Is there an easy way to compile dlls for baseq3?

**Comment by ec-** [comment]
Extracting/using dlls from pk3 files were never supported in Quake3 as it leads to weaken security on client-side

**Comment by Sondro** [comment]
I understand what you're saying & the benefits of QVM for mini-mods. But I think it's actually MORE secure if you just have a few DLLs for the mods you want & disable QVM. Like for instance you just want baseq3 or some other standalone-ish distro (like Open Arena with Quake3e). It's the same risk as downloading an executable initially (yet still be able to use pk3 for assets). 

Maybe call them 'pkx' or something like that & then you can just disable downloading them with CURL? I'm not interested in 'mini mods', only large TC-like mods I can review & manually download outside of the engine, then setup a dll for performance (without having to extract a bunch of pk3s & make a huge mess).

**Comment by ensiform** [comment]
RTCW, ET, and JK Academy all use DLLs for their mod code and its a security nightmare and platform support hell.

**Comment by Sondro** [comment]
Well, I'm not saying to abandon QVMs, just fix up DLL pk3 suppot maybe with pkx.

**Comment by ec-** [comment]
> But I think it's actually MORE secure if you just have a few DLLs for the mods you want & disable QVM

This is a false and misleading statement

> It's the same risk as downloading an executable initially

As of 'root of trust' - you're downloading (or compiling) client only once, after that you can _safely_ download/update any QVM mod, unlike DLLs

>then setup a dll for performance

You will not achieve so much comparing to my recent QVM

>without having to extract a bunch of pk3s

This has nothing with QVM/DLL based mods, it is how Q3 modification system works since ages. Also with QVM you may have everything packed in a single pk3 file - which is not the case for DLL-based mods where you must extract DLLs out of pk3 file - which will lead to a bigger mess comparing to QVMs

>just fix up DLL pk3

It is not 'fix up' - it is an obvious security regression/backdoor so **won't implement**

**Comment by Sondro** [comment]
Alright, if you don't want to implement it that's fine. It's not really a 'regression' since DLLs are for increased performance vs QVM. I don't really see how a QVM is going to be as fast as a DLL -- maybe on modern systems it can be more negligible.
