### ISSUE TITLE
r_overBrightBits 1 + r_mapOverBrightBits 0 = everything is pitch black

### ISSUE THREAD

**Issue by Aciz** [ec-/Quake3e#125]
Setting `r_overBrightBits 1` and `r_mapOverBrightBits 0` results in the world being completely black.  `r_fbo` doesn't affect it, happens on both OpenGL and Vulkan renderers.

![image](https://user-images.githubusercontent.com/14221121/139935679-56a5ab2f-e073-48c3-9c8c-95ccfb543cf6.png)

**Comment by ec-** [comment]
original 1.32c/ioq3 looks the same so don't use `r_mapOverBrightBits 0`

**Comment by Aciz** [comment]
Well yes, but should it really look this way? If you turn off `r_overBrightBits`, it's completely fine, to me this looks like a bug in the (vanilla) renderer that could be fixed.

![image](https://user-images.githubusercontent.com/14221121/140041557-24f15f11-ce9a-44f3-a385-e44b9cbffc15.png)

**Comment by ec-** [comment]
Many users and map creators relies on current code, I don't think is a good idea to alter anything there

**Comment by ensiform** [comment]
What benefit does it provide them?

**Comment by Aciz** [comment]
I am no renderer code expert but to me this looks like a math bug in the code where all RGB values get `0 0 0` value when this combination is used, as everything is not just really dark, it's just plain black everywhere.

**Comment by ec-** [comment]
@Aciz thank you for your feedback
