### ISSUE TITLE
[Feature Request] Built-in fixes from The Unofficial Patch

### ISSUE THREAD

**Issue by Patrxgt** [ec-/Quake3e#136]
[![IMG_20220119_002504](https://user-images.githubusercontent.com/62941214/150034955-3855ecbb-b3f4-4d72-a6ce-617dfb30667e.jpg)](https://www.moddb.com/mods/the-unofficial-patch) 

It would be nice to have fixes from unofficial update mentioned above built into this source port.

**Comment by ensiform** [comment]
Quake3e doesn't contain any mod code. Seems out of scope. Maybe part of baseq3a repo. Also the image link points to the image not the mod url.
