### ISSUE TITLE
Some weird colorful lightmaps on the floor

### ISSUE THREAD

**Issue by mgorchak-blackberry** [ec-/Quake3e#144]
I'm running Vulkan renderer using two days old Quake3e code from master branch. Hardware is Intel KabyLake NUC, Mesa3D 21.2.4.

Please check the screenshot below:

![screenshot-colorspots](https://user-images.githubusercontent.com/74101708/151274768-0f816564-b1c7-46ff-8417-f1d2076adf15.jpg)

Thank you!

**Comment by ec-** [comment]
Try with `\r_mergedLightmaps 0`, this looks very similar to #68

**Comment by mgorchak-blackberry** [comment]
Yes, it fixes the lightmap issue.

**Comment by ec-** [comment]
Please check also OpenGL build on maps like `lun3dm5`

**Comment by mgorchak-blackberry** [comment]
Unfortunately I can't. It is running under QNX, we have OpenGL ES and Vulkan there only, no OpenGL.

**Comment by ec-** [comment]
Try with most recent sources
