### ISSUE TITLE
Re enable anisotropic filter

### ISSUE THREAD

**Issue by Riccardoman** [ec-/Quake3e#147]
Is there a command for re enabling anisotropy with nearest filter enabled on vk? I had this issue since the last week release

**Comment by ec-** [comment]
What kind of issue? That old vulkan behavior doesn't match opengl renderer - that's why it was corrected

**Comment by Riccardoman** [comment]
Here's two screenshots for comparison (i use nearest neighbor by default)
![shot-20220206-134547](https://user-images.githubusercontent.com/74624503/152681484-16b47bf4-85b1-4821-bd51-9e9e642b608e.jpg)
before last week release
![shot-20220206-134456](https://user-images.githubusercontent.com/74624503/152681511-5268135c-6a5e-4b65-a7b4-a04f8adcc224.jpg)
after last week release
I tried re enabling anisotropy with seta r_ext_texture_filter_anisotropic "1" but it doesn't work

**Comment by ec-** [comment]
Show me exact cvar values or better whole q3config.cfg

**Comment by ec-** [comment]
Problem is that on some systems with enabled anisotropic filtering - nearest magnification / nearest mipmap filtering doesn't work at all

**Comment by Riccardoman** [comment]
[q3config.zip](https://github.com/ec-/Quake3e/files/8010259/q3config.zip)
I have 16x anisotropic enabled as default on my nvidia control panel, disabling it doesn't seem to make any difference

**Comment by KuehnhammerTobias** [comment]
@Riccardoman Yeah, I can confirm anisotropic filtering is broken (at least on Nvidia). It is also broken with the opengl2 renderer. I'm currently working on it to get it fixed, at least with opengl2. What I wonder is if you enabled anisotropic filtering on your  nvidia control panel it shouldn't be broken at all because your card will bypass/ignore the game's internal settings, maybe some driver issue.
Anyways, I highly recommend to always let the software (game) do the anisotropic filtering, NOT the card (via nvidia panel).

**Comment by KuehnhammerTobias** [comment]
@Riccardoman Ah yes, sorry I was not clear enough, I think. I meant you shouldn't set anisotropic filtering **globally** in your NV control panel. Do it game specific. Select the game that don't have anisotropic filtering (mostly very old games) set the filtering like you want, and hope it works :)
But as soon as the game provides anisotropic filtering (like Q3e) use those settings instead, and don't set the filtering method in your NV control pane, neither globally (for all games), nor for Q3e. There are a few benefits if you do this that way, like finding bugs easier, and most of the times using the games internal filtering method is much faster.

**Comment by Riccardoman** [comment]
Latest build, the problem still persists (every setting in the nvidia control panel is on default)

**Comment by Riccardoman** [comment]
> @Riccardoman Yeah, I can confirm anisotropic filtering is broken (at least on Nvidia). It is also broken with the opengl2 renderer. I'm currently working on it to get it fixed, at least with opengl2. What I wonder is if you enabled anisotropic filtering on your nvidia control panel it shouldn't be broken at all because your card will bypass/ignore the game's internal settings, maybe some driver issue. Anyways, I highly recommend to always let the software (game) do the anisotropic filtering, NOT the card (via nvidia panel).

Did you find a workaround? also why the filter worked prefectly before February?

**Comment by ec-** [comment]
AF doesn't work properly on all hardware/drivers with nearest filtering so it was disabled for such cases to produce predictable results for everyone

**Comment by Riccardoman** [comment]
That's a pity, hope to see it return in the future, for now I'll stay with the pre february build

**Comment by ensiform** [comment]
No chance of cvar to control?

**Comment by Riccardoman** [comment]
That would be appreciated

**Comment by Riccardoman** [comment]
I hope to not be pressant but it would be nice to get a cvar for reenabling the filter for users that don't have the same issue with nearest enabled

**Comment by ec-** [comment]
This is nvidia-specific enhancement, I wouldn't introduce a new cvar just for that
