### ISSUE TITLE
How can I make a standalone game based on this?

### ISSUE THREAD

**Issue by MegaTKC** [ec-/Quake3e#150]
Hi, I have a question. I want to create a game based on the id Tech 3 engine. Your engine here has vulkan and I would want to create a fun and exciting game for the pi 4. I want to use vulkan as it can provide good fps for the Raspberry Pi. How can i create a standalone version using this engine just like ioquake3?

**Comment by ensiform** [comment]
The game code portion is in a separate repository compared to ioquake3.

See: https://github.com/ec-/baseq3a

By default this isn't as designed to be used for standalone but it should still be possible to do, you'd just have more work to rid the quake 3 references.

**Comment by ec-** [comment]
Take look at https://github.com/OpenArena/gamecode

If you want to create standalone game then you must replace **all** original Q3A resources with new ones in a separate directory and point ```fs_basegame``` cvar to that location, example for OpenArena (add following to command line):

```+set fs_basegame baseoa```

OpenArena is a good starting point for total conversion/standalone game IMO
