### ISSUE TITLE
FMV Videos Appear Stretched

### ISSUE THREAD

**Issue by OpenRift412** [ec-/Quake3e#152]
I don't know if there's a console command to fix this, but all the videos (intro, new tier unlock, etc.) seem to stretch to my resolution's aspect ratio instead of staying in 4:3 like they're meant to.

**Comment by ec-** [comment]
Original 1.32 engine plays cinematics in such way _at least_ in 5:4 mode (1280x1024), nothing to fix

**Comment by star69rem** [comment]
Just because the original was broken as well doesn't mean it shouldn't be fixed. The FMV always gets stretched to the aspect ratio of the resolution that you're running at instead of getting corrected relative to the native aspect ratio of the FMV.

**Comment by ec-** [comment]
Related code already exists: https://github.com/ec-/Quake3e/blob/master/code/client/cl_cin.c#L1617
but commented out because it looks ugly on wide aspect ratios, you may enable it locally and recompile for yourself

**Comment by star69rem** [comment]
I don't understand why it would look ugly to display at the correct aspect ratio. Stretching things out looks ugly.

**Comment by ec-** [comment]
Original intro already has black bars on top and bottom so it looks ugly:
![PIC](https://github.com/user-attachments/assets/2cbbd42b-6e7a-4cb9-950e-159c481c51c5)

**Comment by star69rem** [comment]
The letterboxing is baked into the video. Even with it stretched, you still have black bars, and it looks even worse. 

![image](https://github.com/user-attachments/assets/4496e954-20dc-4603-8ee1-3ff7ef8b2a04)

The second half of the intro FMV is 4:3 gameplay footage with no letterboxing too. That's all perfectly normal. The commented out behavior is the correct behavior here.

**Comment by star69rem** [comment]
So you're just going to stonewall me and pretend that that screenshot is perfectly normal and should be the default behavior, huh? Sounds healthy. Definitely not the 8th billion case of github being a mental illness magnet.
