### ISSUE TITLE
Player model warped in menu with supersample enabled

### ISSUE THREAD

**Issue by Riccardoman** [ec-/Quake3e#154]
![Screenshot (1440)](https://user-images.githubusercontent.com/74624503/160261698-fc0ef5ab-ce21-4da4-9863-ca0a8f2d0b11.jpg)
Otherwise  with multisample it works as intended

**Comment by ec-** [comment]
Not related to engine: use baseq3a or any other mod with correct model FOV fix for high resolution

**Comment by Riccardoman** [comment]
I'm no programmer, do you have it already precompiled for win32-msvc?

**Comment by ec-** [comment]
No, download `extras.zip` from Oct-14 release and use `pak8a.pk3`, this is irrelevant to engine functionality

**Comment by Riccardoman** [comment]
Sorry, compiling the code thanks to your bat file was much easier than I thought. I also was also able to integrate the more maps menu into it :)

**Comment by Riccardoman** [comment]
![q3](https://user-images.githubusercontent.com/74624503/160839026-0463df6f-01b5-4dae-9181-c8c1f0acdd29.jpg)
I wanted to thank you again for your compiler, I have no idea how compiling works but thanks to your work I can now manage to mess with the code
