### ISSUE TITLE
Request Raspberry Pi4 - Vulkan+SDL2 KMS/DRM Backend Support

### ISSUE THREAD

**Issue by bluestang2006** [ec-/Quake3e#155]
This is a feature request for Quake3e to get Raspberry Pi4's Vulkan driver to work under SDL2's Vulkan KMS/DRM backend. In its current state, Quake3e fails to create a Vulkan Surface in KMS/DRM and segfaults, whereas the OpenGL driver works just fine. (SDL2+OGL+KMS/DRM)

In addition, the other [vkQuake3](https://github.com/suijingfeng/vkQuake3) works under SDL2's Vulkan KMS/DRM backend without any issues.

Under Wayland it will work, but it has an [issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/6155) that is yet to be resolved.

However, the best performance for the Raspberry Pi4 is under KMS/DRM.

**Comment by ec-** [comment]
Could you post `\condump`? At this moment I can test it under official 64-bit RaspberryPI OS (it has no KMS/DRM support), debug build may help to figure out exact crash point in your case

**Comment by bluestang2006** [comment]
> Could you post `\condump`/console log? At this moment I can test it under official 64-bit RaspberryPI OS (it has no KMS/DRM support), debug build may help to figure out exact crash point in your case

Yes, you need to install SDL2 2.0.20 - the easiest way is to build and install it from the [Debian Repo](https://salsa.debian.org/sdl-team/libsdl2/-/tree/debian/2.0.20+dfsg-2)

In RPiOS (32/64-bit) all you need to do to invoke an X-11 less terminal is Ctrl-Alt-F1, Ctrl-Alt-F7 will get you back to the X-11 desktop.

From what I can gather, `if ( SDL_Vulkan_CreateSurface( SDL_window, instance, surface ) == SDL_TRUE )` is false in [sdl_glimp.c](https://github.com/ec-/Quake3e/blob/master/code/sdl/sdl_glimp.c#L763) and the function `VK_CreateSurface` is returning `qfalse`.

**Comment by bluestang2006** [comment]
Like I said earlier, `VK_CreateSurface` is returning `qfalse`:

```
Q3 1.32e linux-aarch64-debug Apr  2 2022
----- FS_Startup -----
...found 9 cached paks
...loaded in 10 milliseconds
----------------------
4133 files in 10 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found ARM aarch64
----- Client Initialization -----
----- Client Initialization Complete -----
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
SDL using driver "KMSDRM"
Initializing Vulkan display
...setting mode -2: 1920 1080
Using 24 color bits, 24 depth, 8 stencil display.
----- Client Shutdown (Server fatal crashed: Error creating Vulkan surface) -----
RE_Shutdown( 3 )
-----------------------
Sys_Error: Error creating Vulkan surface
quake3e.aarch64: code/unix/unix_main.c:286: Sys_Exit: Assertion `code == 0' failed.
Received signal 6, exiting...
```

**Comment by bluestang2006** [comment]
@ec- 16b08caa9801e06f9f54bb3ca5670ea12ed9e903 fixes this issue specifically, however, if you are staring at a blank screen when you quit it is because of an annoying [driver issue](https://gitlab.freedesktop.org/mesa/mesa/-/issues/5603) that needs to be fixed. I've been getting around it by switching from DRM to X11 and back. (i.e. Ctrl+Alt+F7 then Ctrl+Alt+F1)

Here is the `condump` of the new commit:
```
Q3 1.32e linux-aarch64 Apr  2 2022
----- FS_Startup -----
...found 9 cached paks
...loaded in 7 milliseconds
----------------------
4133 files in 10 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found ARM aarch64
----- Client Initialization -----
----- Client Initialization Complete -----
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
SDL using driver "KMSDRM"
Initializing Vulkan display
...setting mode -2: 1920 1080
Using 24 color bits, 24 depth, 8 stencil display.
.......................
Available physical devices:
 0: Integrated V3D 4.2, 0xbe485fd3
.......................
...selected physical device: 0
...presentation modes: FIFO
...selected presentation mode: FIFO, image count: 3

VK_VENDOR: Broadcom Inc.
VK_RENDERER: Integrated V3D 4.2, 0xbe485fd3
VK_VERSION: API: 1.1.210, Driver: 22.0.99

VK_MAX_TEXTURE_SIZE: 2048
VK_MAX_TEXTURE_UNITS: 8

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
 presentation: VK_FORMAT_B8G8R8A8_UNORM
 capture: VK_FORMAT_R8G8B8A8_UNORM
 depth: VK_FORMAT_D24_UNORM_S8_UINT
MODE: -2, 1920 x 1080 fullscreen hz:120
GAMMA: hardware w/ 0 overbright bits
texturemode: GL_LINEAR_MIPMAP_LINEAR
texture bits: 32
picmip: 0
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound ------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "pulseaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     22050
  Samples:  256
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
----- Sound Info -----
    2 channels
 8192 samples
   16 samplebits (int)
    1 submission_chunk
22050 speed
0x558dbd4cc0 dma buffer
No background file.
----------------------
Sound initialization successful.
--------------------------------
Sound memory manager started
Loading vm file vm/ui.qvm...
VM file ui compiled to 308068 bytes of code
ui loaded in 1689600 bytes on the hunk
35 arenas parsed
32 bots parsed
--- Common Initialization Complete ---
Hostname: raspberrypi
IP: 127.0.0.1
IP: 192.168.1.12
IP6: ::1
IP6: fe80::7088:9d40:a6d0:58d1%wlan0
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
Working directory: /home/pi/vkQ3e
Started tty console (use +set ttycon 0 to disable)
]quit
----- Client Shutdown (Client quit) -----
Closing SDL audio playback device...
SDL audio playback device closed.
SDL audio shut down.
RE_Shutdown( 3 )
]destroy dumb object 1: Invalid argument
destroy dumb object 2: Invalid argument
destroy dumb object 3: Invalid argument
-----------------------
pi@raspberrypi:~ $ ./vkQ3e/quake3e.aarch64
Q3 1.32e linux-aarch64 Apr  2 2022
----- FS_Startup -----
...found 9 cached paks
...loaded in 3 milliseconds
----------------------
4133 files in 10 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found ARM aarch64
----- Client Initialization -----
----- Client Initialization Complete -----
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
SDL_Init( SDL_INIT_VIDEO ) FAILED (No available video device)
----- Client Shutdown (Server fatal crashed: VKimp_Init() - could not load Vulkan subsystem) -----
RE_Shutdown( 3 )
-----------------------
Sys_Error: VKimp_Init() - could not load Vulkan subsystem
pi@raspberrypi:~ $ ./vkQ3e/quake3e.aarch64
Q3 1.32e linux-aarch64 Apr  2 2022
----- FS_Startup -----
...found 9 cached paks
...loaded in 7 milliseconds
----------------------
4133 files in 10 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
execing autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found ARM aarch64
----- Client Initialization -----
----- Client Initialization Complete -----
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
SDL using driver "KMSDRM"
Initializing Vulkan display
...setting mode -2: 1920 1080
Using 24 color bits, 24 depth, 8 stencil display.
.......................
Available physical devices:
 0: Integrated V3D 4.2, 0xbe485fd3
.......................
...selected physical device: 0
...presentation modes: FIFO
...selected presentation mode: FIFO, image count: 3

VK_VENDOR: Broadcom Inc.
VK_RENDERER: Integrated V3D 4.2, 0xbe485fd3
VK_VERSION: API: 1.1.210, Driver: 22.0.99

VK_MAX_TEXTURE_SIZE: 2048
VK_MAX_TEXTURE_UNITS: 8

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
 presentation: VK_FORMAT_B8G8R8A8_UNORM
 capture: VK_FORMAT_R8G8B8A8_UNORM
 depth: VK_FORMAT_D24_UNORM_S8_UINT
MODE: -2, 1920 x 1080 fullscreen hz:120
GAMMA: software w/ 0 overbright bits
texturemode: GL_LINEAR_MIPMAP_LINEAR
texture bits: 32
picmip: 0
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound ------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "pulseaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     22050
  Samples:  256
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
----- Sound Info -----
    2 channels
 8192 samples
   16 samplebits (int)
    1 submission_chunk
22050 speed
0x5598361a20 dma buffer
No background file.
----------------------
Sound initialization successful.
--------------------------------
Sound memory manager started
Loading vm file vm/ui.qvm...
VM file ui compiled to 308068 bytes of code
ui loaded in 1689600 bytes on the hunk
35 arenas parsed
32 bots parsed
--- Common Initialization Complete ---
Hostname: raspberrypi
IP: 127.0.0.1
IP: 192.168.1.12
IP6: ::1
IP6: fe80::7088:9d40:a6d0:58d1%wlan0
Opening IP6 socket: [::]:27960
Opening IP socket: 0.0.0.0:27960
Working directory: /home/pi/vkQ3e
Started tty console (use +set ttycon 0 to disable)
]quit
----- Client Shutdown (Client quit) -----
Closing SDL audio playback device...
SDL audio playback device closed.
SDL audio shut down.
RE_Shutdown( 3 )
```

**Comment by ec-** [comment]
> ...presentation modes: FIFO

I guess that this is a root of problems: 
- driver/environment supports only v-sync-enabled mode (FIFO)
- its implementation is not correct/buggy

**Comment by bluestang2006** [comment]
> > ...presentation modes: FIFO
> 
> I guess that this is a root of problems:
> 
> * driver/environment supports only v-sync-enabled mode (FIFO)
> * its implementation is not correct/buggy

The MESA WSI code only has FIFO implemented for anything outside of X11 and Wayland. The Vulkan spec mandates that FIFO has to be implemented at a minimum though.

All that said, I am able to play Quake3e in KMS/DRM now with your last patch. The other issues are MESA ones that need to be fixed on their end.

On a side note, for the Raspberry Pi4, I had to increase the `image_count` to `MAX_SWAPCHAIN_IMAGES` (8) because of stuttering that I was seeing in the VK_MESA_Overlay output once it was working KMS/DRM. Every 3rd frame was dropping down to ~60 FPS, whereas the other 2 frames before were at ~120 FPS. Increasing the image_count from 3 to 8 fixed the issue and presentation was very smooth.

In the MESA WSI code, all the `maxImageCount` vars are set to`0`.

**Comment by ec-** [comment]
> Increasing the image_count from 3 to 8 fixed the issue and presentation was very smooth.

Only 8 is really working or maybe there other (lower) values?

>In the MESA WSI code, all the maxImageCount vars are set to 0.

What `surface_caps.maxImageCount` in this case? Maybe we need some special processing

**Comment by bluestang2006** [comment]
> > Increasing the image_count from 3 to 8 fixed the issue and presentation was very smooth.
> 
> Only 8 is really working or maybe there other (lower) values?
>
> > In the MESA WSI code, all the maxImageCount vars are set to 0.
> 
> What `surface_caps.maxImageCount` in this case? Maybe we need some special processing

KMS/DRM
[wsi_common_display.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_display.c#L908) `caps->minImageCount = 2;`
[wsi_common_display.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_display.c#L909) `caps->maxImageCount = 0;`

X11
[wsi_common_x11.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_x11.c#L617) `caps->minImageCount = 3;` (however, this can be overridden several ways within the code)
[wsi_common_x11.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_x11.c#L665) `caps->maxImageCount = 0;`

Wayland
[wsi_common_wayland.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_wayland.c#L709) `caps->minImageCount = 4;`
[wsi_common_wayland.c](https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/vulkan/wsi/wsi_common_wayland.c#L711) `caps->minImageCount = 0;`

I used `maxImageCount = 8;` because the MESA driver is relying on the application to set the maximum images hence why they are setting it to 0 in their code.

Furthemore, vkQuake3 uses the following, which is also why I ended doing the same thing for my RPi4.
```
 if (vk.surface_caps.maxImageCount == 0)
 {
     image_count = MAX_SWAPCHAIN_IMAGES;
 }
 else
 {
     image_count = MIN(image_count+1, vk.surface_caps.maxImageCount);
 }
```

**Comment by bluestang2006** [comment]
@ec- After some testing in KMS/DRM, the commit ca8899236f54f261d101d42675fd2c954b552825 can be reverted. I tested my pc setup (XWayland and Wayland) and my Raspberry Pi 4 and everything checked out just fine. There have been some XWayland changes that fixed the issue I was having prior to the change.

As for the Raspberry Pi 4, KMS/DRM is happy with `minImageCount = 4` and the only present mode available is FIFO. 

If I manually hardcode `minImageCount = 3`, the max frame rate I can reach is 60 FPS even with `com_maxfps 125`.

At `minImageCount = 3`, I can reach 120 FPS but there is some stuttering that is occurring.

Anyways, this is the patch I've been testing:
```diff
diff --git a/code/renderervk/vk.c b/code/renderervk/vk.c
index a1aa5e1e..05293e19 100644
--- a/code/renderervk/vk.c
+++ b/code/renderervk/vk.c
@@ -477,7 +477,9 @@ static void vk_create_swapchain( VkPhysicalDevice physical_device, VkDevice devi
 		}
 	}
 
-	if ( surface_caps.maxImageCount > 0 ) {
+	if ( surface_caps.maxImageCount == 0 ) {
+		image_count = MAX_SWAPCHAIN_IMAGES;
+	} else if ( surface_caps.maxImageCount > 0 ) {
 		image_count = MIN( MIN( image_count, surface_caps.maxImageCount ), MAX_SWAPCHAIN_IMAGES );
 	}
 
diff --git a/code/renderervk/vk.h b/code/renderervk/vk.h
index 526f26c4..f9005bc9 100644
--- a/code/renderervk/vk.h
+++ b/code/renderervk/vk.h
@@ -3,7 +3,7 @@
 #include "../renderercommon/vulkan/vulkan.h"
 #include "tr_common.h"
 
-#define MAX_SWAPCHAIN_IMAGES 8
+#define MAX_SWAPCHAIN_IMAGES 4
 #define MIN_SWAPCHAIN_IMAGES_IMM 3
 #define MIN_SWAPCHAIN_IMAGES_FIFO 3
 #define MIN_SWAPCHAIN_IMAGES_MAILBOX 3
```

**Comment by ec-** [comment]
Is this resolved now?

**Comment by bluestang2006** [comment]
> Is this resolved now?

Yes it is, closing issue.
