### ISSUE TITLE
r_lodcurveerror not working

### ISSUE THREAD

**Issue by AtifArshad1995** [ec-/Quake3e#16]
Hi Dev(s), i am trying to get the far away curved surfaces to look smooth. So i put r_lodcurveerror=10000 (max value) in autoconfig.cfg but it isn't working. 

It is also an issue in another ports like ioquake3, cnq3. So maybe it is vanilla quake 3 issue but it is still a bug/ unintended behaviour nonetheless, so can u fix this issue.

I have also made a issue at ioquake3's git:
https://github.com/ioquake/ioq3/issues/383

**Comment by ec-** [comment]
We need to gather opinions about removing CVAR_CHEAT flag for it

**Comment by BidyBiddle** [comment]
The cvar is unlocked in ET, QL, UrT and Spearmint builds that I know of.

Some screens (http://t.ly/54OH) to illustrate the gain.

![image](https://user-images.githubusercontent.com/5862605/109374958-6133ce00-78b9-11eb-9c76-1104bf1b0896.png)
![image](https://user-images.githubusercontent.com/5862605/109374965-6bee6300-78b9-11eb-97f2-c5d540484449.png)

**Comment by ensiform** [comment]
I wouldn't say it's a bug or unintended behavior at all. Just that at the time of Q3, it was usable as a cheat.

My guess is that changing the curve amount affects ability to see through some areas.
