### ISSUE TITLE
Feature request: Vulkan texture filtering

### ISSUE THREAD

**Issue by ConHuevosGuey** [ec-/Quake3e#161]
Unsure if this exists, I could not find it in the documentation but I would like the ability to change the texture filtering while using the vulkan renderer.  The default seems to be bilinear filtering and 'r_texturemode' does not seem to affect the vulkan renderer.

**Comment by KuehnhammerTobias** [comment]
Do you mean this? https://github.com/ec-/Quake3e/issues/161

**Comment by ConHuevosGuey** [comment]
No, that is anisotropic filtering not working while nearest neighbor is enabled.  Oddly enough he says while in vulkan.  I set cl_renderer to 'vulkan'
vid_restart
and bilinear filtering gets enabled and I can't find a way to change it to nearest.  r_texturemode has no effect.

**Comment by ec-** [comment]
`\r_textureMode GL_NEAREST_MIPMAP_NEAREST` works for me

**Comment by ConHuevosGuey** [comment]
Apologies, ignore this.  It wasn't working but I believe I had a configuration file error somewhere.  I deleted it and made a fresh one and it's working.
