### ISSUE TITLE
M1 cursor appears when mouse moving fast

### ISSUE THREAD

**Issue by kuncevic** [ec-/Quake3e#162]
I did compile the sources for M1, experiencing that weird issue when mouse moving fast.

Please see the gif below 

![animation_](https://user-images.githubusercontent.com/1283734/165955350-192b6f11-8684-43ff-a81b-16b5615d6f87.gif)

<img width="213" alt="image" src="https://user-images.githubusercontent.com/1283734/165955788-633ce56e-6ce2-4523-9ca9-f9d9e7cf67c5.png">

p.s had no problems like that on my old x64 mac

**Comment by ec-** [comment]
There is no API difference between x86/ARM platforms so looks like as SDL2/platform bug

**Comment by kuncevic** [comment]
Yeah I c, just checked, I am using `SDL2-2.0.22` which is the latest atm

**Comment by kuncevic** [comment]
whoops just noticed that was a wrong repo, that is [where it has to go](https://github.com/ezQuake/ezquake-source/issues/654)
