### ISSUE TITLE
Req: Proper 21:9 support

### ISSUE THREAD

**Issue by Whatscheiser** [ec-/Quake3e#163]
I'm currently running Quake 3 using the Spearmint Projects engine which has proper aspect correct support for 21:9 displays. Given Q3Plus seems to make use of this engine and I'd like to move over to it, I was hoping to find the same functionality in Quake3e. Unless I'm missing something I don't believe this feature has been baked in yet. So I'd like to request that it be added.

**Comment by ensiform** [comment]
It's up to the mod you're running to support wide aspect resolution for UI/HUD and fov. Out of scope for engine.

**Comment by Whatscheiser** [comment]
How would a mod do that without it being a feature of the engine? I'm confused by your statement. Maybe I'm not describing this well. Level geometry is correct. I can use the console to set a custom resolution that appears to work fine. No 16:9 stretched... it looks like I'm hitting the correct 3440x1440. But the model position for weapons isn't correct. I assume because the camera position for the player doesn't compensate for the wider viewing angle.

 for example img 1 is under q3e and img 2 is spearmint
![bandicam 2022-05-07 16-10-59-338](https://user-images.githubusercontent.com/90274289/167270360-569d6c7a-d8a0-44ae-b7fc-ca3d45a88e0f.jpg)
![bandicam 2022-05-07 16-11-56-222](https://user-images.githubusercontent.com/90274289/167270363-01702b4b-be87-4670-8c32-f447a4577f4b.jpg)

**Comment by ensiform** [comment]
That's all handled by the cgame.qvm (mod)

Not the engine.

**Comment by Whatscheiser** [comment]
Hmm. Well damn. Alright, thanks I appreciate your responses.
