### ISSUE TITLE
Feature Request: Allow loading BSP file version 47

### ISSUE THREAD

**Issue by Whatscheiser** [ec-/Quake3e#164]
I've seen this feature done in other engines and it saves a lot of leg work when trying to work with files from later id games. (Return to Castle Wolfenstein for example) I was kind of surprised to see that some of my maps wouldn't load in Q3e. Maybe its outside of the current scope, sure would like to see it though.

**Comment by ensiform** [comment]
Even if the bsp would load, the rendering would not be the same. As there's a different lighting model and different fog behaviors that are exclusive to those games. Not to mention game specific shaderparms and shader extensions.

QL bsp47 is also the same as 46 but the adverts lump is added. And is not compatible with wolf bsp47. They erroneously reused 47 for QL but was too late in release by the time such issue was raised.
