### ISSUE TITLE
Default path broken

### ISSUE THREAD

**Issue by Kr3m** [ec-/Quake3e#167]
Game no longer reads from C:\Users\USER\AppData\Roaming\Quake3 forcing players to mix custom maps and mods with the vanilla game again.  One step forward, ten steps back.  Does ~/.q3a even work on Linux with this version?  Yikes....

**Comment by ec-** [comment]
It is a known and **desired** behavior on windows platform, I see no good reasons why windows users should be forced to dig into homepath directories just to mimic linux/unix filesystem behavior

**Comment by ensiform** [comment]
Not broken. That is an ioquake3 feature which is intentional not used.

**Comment by The-Gig** [comment]
Are you saying now "basepath" and "homepath" are the same (game installation folder) by default, like it was in original game for Windows 98, instead of the behavior from ioquake3 (default homepath in %appdata%\quake3)?
Or am I missing something?

**Comment by ec-** [comment]
Initial commit of this project (2010-Dec-01) already contains `USE_PROFILES` definition in `Sys_DefaultHomePath()` which effectively disables that ioq3 **addition**

**Comment by The-Gig** [comment]
For me, coming from many years of OpenArena, that sounds a bit strange (almost every program nowadays stores settings in user-specific folders -and often the program install directory has got read only permission-), but ok...

Then, I guess Kr3n or anyone willing user-specific settings will have to use a shortcut or batch file to add "+set fs_homepath <path>" command line parameter...

**Comment by Kr3m** [comment]
> It is a known and **desired** behavior on windows platform, I see no good reasons why windows users should be forced to dig into homepath directories just to mimic linux/unix filesystem behavior

I think this is a minority opinion.  You were never forced to use this directory.  It was optional.  You could always load your mods and maps from either folder, but now we're reverting back to mixing the vanilla game with custom maps, configs, and mods.  They won't even load from that folder anymore.  Definitely a lot more sloppy, especially if the game is installed to the default Steam path for Steam users in the Program Files directory.

**Comment by ensiform** [comment]
You are free to specify +set fs_homepath "%APPDATA%/Quake3%" or whatever you prefer as a full path

**Comment by Kr3m** [comment]
> You are free to specify +set fs_homepath "%APPDATA%/Quake3%" or whatever you prefer as a full path.
> 
> Regardless of which default is used, some groups of players will be angry at the default value. Lose lose situation.

Doesn't setting the fs_homepath lose the ability to load from the install folder though?  It should never be lose lose.  Before it would load pk3 files from both folders.  Now it seems it is limited to one even if you set fs_homepath.  That's the only lose lose scenario here.

**Comment by The-Gig** [comment]
> > You are free to specify +set fs_homepath "%APPDATA%/Quake3%" or whatever you prefer as a full path.
> > Regardless of which default is used, some groups of players will be angry at the default value. Lose lose situation.
> 
> Doesn't setting the fs_homepath lose the ability to load from the install folder though? It should never be lose lose. Before it would load pk3 files from both folders. Now it seems it is limited to one even if you set fs_homepath. That's the only lose lose scenario here.

I haven't done tests about this with q3e, so I'm not sure. But in theory fs_homepath should not break basepath. So the game should load PK3s from basepath and then the stuff from hompath (overriding assets with the same name)... Otherwise the game would not even find pak0.pk3.

**Comment by ec-** [comment]
Content in `fs_homepath` has higher priority over content in `fs_basepath`.
 
Vanilla win32 behavior is predictable and very handy for users who do not want to dig into different directories - and it is a good way to handle all files in one place - and it is possible to create portable bundles with that. Opposite situation is a consequence of unix permissions/limitations - I see no reasons why everyone should follow that.

So back to topic header - it is not broken for win32 in Q3e, it is broken in ioq3/derivatives

**Comment by The-Gig** [comment]
I would not consider "broken" any of the two. They are just two different approaches, its one with their own pros and cons. ;-)

**Comment by KuehnhammerTobias** [comment]
Yes, very handy for Win users. What I'm missing is to have the cfg write-protected, for development purposes it is sometimes useful to have the cfg write-protected. Q3e seems to changed that, it unlocks the write protection. Is this related to NOT have the cfg in the homepath? Sorry if this is off topic, but it is very likely that this is related to weird Windows path bahvior. It would be nice to have at least the option to leave the write-protection untouched. Though, maybe I miss something here, idk. I can't remember if vQ3 also unlocks write-protection or not.

**Comment by ensiform** [comment]
> Yes, very handy for Win users. What I'm missing is to have the cfg write-protected, for development purposes it is sometimes useful to have the cfg write-protected. Q3e seems to changed that, it unlocks the write protection. Is this related to NOT have the cfg in the homepath? Sorry if this is off topic, but it is very likely that this is related to weird Windows path bahvior. It would be nice to have at least the option to leave the write-protection untouched. Though, maybe I miss something here, idk. I can't remember if vQ3 also unlocks write-protection or not.

It is not related to write protection from home or basepath to my knowledge. You'd have to check the commit history for exact reasoning.

There's not much purpose to write protection when the config almost never gets broken by a crash unlike vanilla game. Because it doesn't try to write you config every frame anymore.

**Comment by KuehnhammerTobias** [comment]
Oh, nice to know I can backport the write-protection. Thanks for the hint, ensiform!

**Comment by ensiform** [comment]
> Oh, nice to know I can backport the write-protection. Thanks for the hint, ensiform!

Look for Sys_ResetReadOnlyAttribute and disable it

**Comment by Kr3m** [comment]
> Content in `fs_homepath` has higher priority over content in `fs_basepath`.
> 
> Vanilla win32 behavior is predictable and very handy for users who do not want to dig into different directories - and it is a good way to handle all files in one place - and it is possible to create portable bundles with that. Opposite situation is a consequence of unix permissions/limitations - I see no reasons why everyone should follow that.
> 
> So back to topic header - it is not broken for win32 in Q3e, it is broken in ioq3/derivatives

That's absolutely not true.  It is in fact broken here.  ioq3 is the only option for people who share a computer and want to have separate configs for the same game as well as people who like keeping Q3 vanilla untouched.

**Comment by ensiform** [comment]
> > Content in `fs_homepath` has higher priority over content in `fs_basepath`.
> > Vanilla win32 behavior is predictable and very handy for users who do not want to dig into different directories - and it is a good way to handle all files in one place - and it is possible to create portable bundles with that. Opposite situation is a consequence of unix permissions/limitations - I see no reasons why everyone should follow that.
> > So back to topic header - it is not broken for win32 in Q3e, it is broken in ioq3/derivatives
> 
> That's absolutely not true. It is in fact broken here. ioq3 is the only option for people who share a computer and want to have separate configs for the same game as well as people who like keeping Q3 vanilla untouched.

Bro, set fs_homepath to the path similar to what ioquake3 uses in your startup shortcut and be done with it. The default behavior doesn't seem to be changing to ioquake3 behavior here as the majority wishes to not. It is not "broken" just because it is not the same as ioquake3. As I said before, there is no fix. Because some players expect vanilla behavior and apparently a very few amount like ioquake3 behavior.

**Comment by Kr3m** [comment]
> > > Content in `fs_homepath` has higher priority over content in `fs_basepath`.
> > > Vanilla win32 behavior is predictable and very handy for users who do not want to dig into different directories - and it is a good way to handle all files in one place - and it is possible to create portable bundles with that. Opposite situation is a consequence of unix permissions/limitations - I see no reasons why everyone should follow that.
> > > So back to topic header - it is not broken for win32 in Q3e, it is broken in ioq3/derivatives
> > 
> > 
> > That's absolutely not true. It is in fact broken here. ioq3 is the only option for people who share a computer and want to have separate configs for the same game as well as people who like keeping Q3 vanilla untouched.
> 
> Bro, set fs_homepath to the path similar to what ioquake3 uses in your startup shortcut and be done with it. The default behavior doesn't seem to be changing to ioquake3 behavior here as the majority wishes to not. It is not "broken" just because it is not the same as ioquake3. As I said before, there is no fix. Because some players expect vanilla behavior and apparently a very few amount like ioquake3 behavior.

I'm pretty sure even the default q3 used the user home directory at some point maybe 1.32?  I know Quake Live did, but I've run servers for both and know for a fact it was setup in Linux this way, but am pretty sure Quake 3 did as well and this isn't unique to ioquake3.  Either way, for me this just seems like a nerfed version of ioq3 and I don't see how the positives outweigh the negatives at this point.

**Comment by Kr3m** [comment]
> No, it does not on Windows, ever. It is an ioquake3 feature.
> 
> https://github.com/id-Software/Quake-III-Arena/blob/master/code/win32/win_shared.c#L298
> 
> `+set fs_homepath "C:\Users\YOURUSER\Documents\Quake3"` should work just fine it is just not default because it follows the original behavior as seen above.
> 
> How many people play quake 3 with multi user profiles? Almost nobody. CNQ3 (cpma) also has no multi user support by default either.
> 
> > Either way, for me this just seems like a nerfed version of ioq3 and I don't see how the positives outweigh the negatives at this point.
> 
> Yeah sure okay bro. So many negatives.

So they added a homepath variable, called it homepath, and didn't know what homepath means?  That's just weird.  Oh well.  I might explore what positive features were added in more depth.  I admittedly wasn't even interested when I realized they nerfed the homepath.  Easy to assume they probably broken more than that, but if not, I'll just fork it and fix it.

**Comment by KuehnhammerTobias** [comment]
@Kr3m I totally agree with you, I was also switching from ioq3 and my feelings about Q3e was a bit undecided, so many features are missing, etc.
After some time I get used to the new 'path' situation, it has it pros and cons, for what I wonder how hard would it be to have a cvar to let the user decide? @ensiform ?

**Comment by ensiform** [comment]
The cvar has always existed, it just is defaulted to empty (on windows). Nobody nerfed anything. ioquake3 added it. QuakeLive was released much later on, and took the route of using "Saved Games" folder.

@KuehnhammerTobias  Why should there be a cvar to "decide". You can already decide for yourself by adding the fs_homepath to point to where you want your homepath to be. Seems over-engineering for very little gain, since it would also still need to be set at startup no matter. Can't load it from a config if you don't "know" where the config is to be loaded from.

**Comment by KuehnhammerTobias** [comment]
A chicken and egg problem?

**Comment by ensiform** [comment]
In reference to adding a cvar to decide? Yes.

**Comment by Kr3m** [comment]
> The cvar has always existed, it just is defaulted to empty (on windows). Nobody nerfed anything. ioquake3 altered it so that it has the user's appdata path. QuakeLive was released much later on, and took the route of using "Saved Games" folder, like other later idTech games.
> 
> @KuehnhammerTobias Why should there be a cvar to "decide". You can already decide for yourself by adding the fs_homepath to point to where you want your homepath to be. Seems over-engineering for very little gain, since it would also still need to be set at startup no matter. Can't load it from a config if you don't "know" where the config is to be loaded from.
> 
> This debate is tiresome and has been raging for years in many communities that tried to follow ioquake3's suit. MANY old school players complain that "portable" mode is gone. And then you have a few which say its fine.

I think the portability argument is strange considering the game is more portable when you have a homepath set.  You can literally plug that into any Quake 3 install, and you're good to go.  It's not only portable, but it's more porrtable this way.

**Comment by ec-** [comment]
As it was said - it is not "broken", it is a known and **expected** behavior on win32, less actions to manage configs - better for end-users, nothing to discuss
