### ISSUE TITLE
Recent changes breaks > 4 bloom passes?

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#168]
I'm not sure if this is another 'intentional' quality decrease to get better performance or if this is a real issue.
Since the latest renderer changes, I think it is  this one: https://github.com/ec-/Quake3e/commit/26c41b897ed872c3d7a3294c6f6c4e5f0685e352
I get the following message:
`...not enough texture units (4) for 8-pass bloom
...error creating framebuffers for bloom`
If this was done intentionally, can we have a (meta)cvar for things like that?
If I change r_bloom_passes to 4, bloom works again.

**Comment by ensiform** [comment]
Nothing changed in this commit. Only code moved to a different function (R_InitExtensions) so that it still gets executed on "keep window" which is used by snd_restart. I was getting that error on snd_restart before this patch.

**Comment by KuehnhammerTobias** [comment]
Okay, thanks for pointing this out, I changed the title of the issue.

**Comment by ensiform** [comment]
I would try to query all of those values locally to see which one is bad on your machine.

**Comment by KuehnhammerTobias** [comment]
I can confirm that https://github.com/ec-/Quake3e/commit/386ad870ee15f932be5e688de4461abc89e51a9a fixes the issue and restores bloom passes (at least for me). I'm using 8 bloom passes, and bloom looks as nice as before. No error messages anymore, also no error messages after snd_restart. I'm not closing this issue, waiting for feedback from @ensiform about the snd_restart thing. I leave it up to you to close the ticket.
Well done!

**Comment by ec-** [comment]
NVidia reports `GL_MAX_ACTIVE_TEXTURES_ARB = 4` for some compatibility reasons I guess

So `glConfig.numTextureUnits` were first set to higher value by quering `GL_MAX_TEXTURE_IMAGE_UNITS`/`GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS` then truncated to (obviously lower and 'compatible') `GL_MAX_ACTIVE_TEXTURES_ARB`

**Comment by ensiform** [comment]
Its good now
