### ISSUE TITLE
Feature Request: QL-style r_picmip

### ISSUE THREAD

**Issue by reinstallgentoo** [ec-/Quake3e#17]
I'm unsure how this is done but in Quake Live, r_picmip only applies to world textures & models (iirc). Also, please forgive my terminology here..

**Affected by r_picmip:**
world textures
world models

**Unaffected by r_picmip:**
player models
weapon models (world & firstperson)
weapon particle effects (rocket/grenade explosions etc.)
other particles (flags etc.)

The benefit of this is improved visibility while keeping the particles looking original and no longer obscuring your vision (by being picmip'd).

So my request would be either to change r_picmip to function in this manner or have the option to enable this.

Thanks for reading.

**Comment by KG7x** [comment]
\r_nomip 0|1- apply picmip only on worldspawn textures
