### ISSUE TITLE
Using only for mods?

### ISSUE THREAD

**Issue by HiImJulien** [ec-/Quake3e#173]
Hey there!

Can this fork be used to play "Urban Terror", a Q3 Mod, without having the game itself?
If so, what are the steps necessary to do so?

Running the executable now yields the following error, which is probably expected:
```
Q3 1.32e linux-x86_64 Jun  9 2022
----- FS_Startup -----
...loaded in 0 milliseconds
----------------------
0 files in 0 pk3 files

Search paths:
 * /home/kirsch/.q3a
 * /home/kirsch/Downloads/Quake3e-master/build/release-linux-x86_64
 * /home/kirsch/.q3a
 * /home/kirsch/Downloads/Quake3e-master/build/release-linux-x86_64


pak0.pk3 is missing. Please copy it
from your legitimate Q3 CDROM.


Point Release files are missing. Please
re-install the 1.32 point release.


Also check that your Q3 executable is in
the correct place and that every file
in the baseq3 directory is present and readable.
Sys_Error: Couldn't load default.cfg
```

Thanks in advance!

**Comment by HiImJulien** [comment]
Nevermind, I found the solution:

`./quake3e.x64 +set fs_game q3ut4`

Assuming that q3ut4 is in the same folder.

**Comment by The-Gig** [comment]
In general, about using Quake 3 Mods without having Q3A...
Maybe you can try with OpenArena instead, see <https://openarena.fandom.com/wiki/Mod_compatibility>.
Please notice that while OA is licensed under GPL, third party maps and mods, especially those created for Q3A, may not. This means using them is at your own risk.
