### ISSUE TITLE
Crash when I activate r_bloom 1 (Attachments array ovrerlow) on Vulkan

### ISSUE THREAD

**Issue by Sol1vaN** [ec-/Quake3e#175]
Hi there,

The game crash when r_bloom 1 is active and then you restart the video engine with vid_restart.
This happens only with vulkan render.

I've attached the log.

I'm using Ryzen 5 5500X with RTX 2070
[crash.txt](https://github.com/ec-/Quake3e/files/8962901/crash.txt)

**Comment by Sol1vaN** [comment]
why? some explain to this?😓

**Comment by ec-** [comment]
>closed this as completed

means it was fixed in https://github.com/ec-/Quake3e/commit/35515a29e27a9f69de7d6103868dbd97a15417a4

**Comment by Sol1vaN** [comment]
> > closed this as completed
> 
> means it was fixed in [35515a2](https://github.com/ec-/Quake3e/commit/35515a29e27a9f69de7d6103868dbd97a15417a4)

yes sorry, ive noticed later, thnk very much! 🥰
