### ISSUE TITLE
Using "screenMap" in shader

### ISSUE THREAD

**Issue by Mix3r** [ec-/Quake3e#181]
Hi, Eugene. Sorry for taking some of your time, but i couldn't figure out where to place screenmap inside the shader. for example:

models/weapons2/machinegun_d
{
cull none
  {
    screenMap models/weapons2/machinegun_d.tga
    rgbGen lightingDiffuse
    tcGen environment
  }
}

The game says "unknown parameter 'ScreenMap' in shader models/weapons2/machinegun_d" and refuses to draw any texture
Would you provide an example of shader with correct placement of screenMap keyword. Thanks in advance. I'll mention you in credits of our project, which is heavily based on using Quake3e engine (upcoming release 1.1.1)

**Comment by ensiform** [comment]
You may only add them to shaderx files.

It's unsupported in regular shader files.

**Comment by Mix3r** [comment]
Thank you very much for valuable support! I've placed the shader inside standalone .shaderx file and it works. Adding you into credits immediately, as well as Eugene for providing Quake3e with such great feature.
