### ISSUE TITLE
[Vulkan] multisample and supersample cmds doesn't work

### ISSUE THREAD

**Issue by Cianez** [ec-/Quake3e#182]
I've tested "r_ext_supersample 2" and "r_ext_multisample 8" separately, but they don't seem to work at all. I've also forced them in the autoexec.cfg but they don't work either.
Am I doing something wrong?

**Comment by KG7x** [comment]
requires \r_fbo 1

**Comment by Cianez** [comment]
> requires \r_fbo 1

Oh, that's why.
Guess I missed the "offscreen rendering, enabled with \r_fbo 1, all following requires it enabled" part.
My bad sorry, this issue can be closed. Thank you @KG7x .
