### ISSUE TITLE
Error building ARCH=arm

### ISSUE THREAD

**Issue by taoeffect** [ec-/Quake3e#186]
Tried on an M2: `make USE_VULKAN=1 RENDERER_DEFAULT=vulkan USE_RENDERER_DLOPEN=0 ARCH=arm -j 8` and got:

```
code/qcommon/vm_armv7l.c:3202:2: error: implicit declaration of function '__clear_cache' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        __clear_cache( vm->codeBase.ptr, vm->codeBase.ptr + vm->codeLength );
        ^
```

**Comment by ensiform** [comment]
Apple arm platforms like the M2 is aarch64, not "arm"

**Comment by taoeffect** [comment]
Oh, I checked the Makefile and it used both so I just picked one:

```Makefile
ifeq ($(ARCH),arm)
  HAVE_VM_COMPILED = true
endif
ifeq ($(ARCH),aarch64)
  HAVE_VM_COMPILED = true
endif
```

I get a similar error:

```
code/qcommon/vm_aarch64.c:3481:2: error: implicit declaration of function '__clear_cache' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        __clear_cache( vm->codeBase.ptr, vm->codeBase.ptr + vm->codeLength );
        ^
1 error generated.
```

**Comment by taoeffect** [comment]
>  Pretty sure you don't have to pass arch on apple if you're building native only.

Oops, missed this comment. By default it builds x86_64:

```
$ lipo -info quake3e
Non-fat file: quake3e is architecture: x86_64
```

**Comment by ensiform** [comment]
> > Pretty sure you don't have to pass arch on apple if you're building native only.
> 
> Oops, missed this comment. By default it builds x86_64:
> 
> ```
> $ lipo -info quake3e
> Non-fat file: quake3e is architecture: x86_64
> ```

Sounds like your terminal or build process is being run through rosetta then.

**Comment by taoeffect** [comment]
> Sounds like your terminal or build process is being run through rosetta then.

Hmm, I don't think it is, but if you know of another way I can check let me know:

```
$ lipo -info $(which zsh)
Architectures in the fat file: /bin/zsh are: x86_64 arm64e
```

> But its probably not actually present due to trying to be as x86_64?

I'm not sure I understand what you're saying here. FYI it does build an x86_64 binary without error.

**Comment by ec-** [comment]
Check `uname -a` output - most likely you're running compilation through x86_64-emulation environment

**Comment by taoeffect** [comment]
I figured it out!

Transitioning Homebrew from an Intel machine to Apple Silicon resulted me with an x86 version of zsh.

So to fix this I had to uninstall Homebrew and re-install it. Thanks for your help! It now builds the binary as arm64, although I can't run it, will open a separate issue for that.
