### ISSUE TITLE
New version of grep throws warning

### ISSUE THREAD

**Issue by zoidby** [ec-/Quake3e#187]
Hi

Running make with newly released grep 3.8 i get this warning:

`grep: warning: stray \ before #`

Apparently you don’t need to escape certain characters anymore and grep will warn about it. Removing the trailing \ in line 222 of the Makefile seems to work fine.

**Comment by ec-** [comment]
replacing 
```shell
grep "\#define Q3_VERSION"
```
with
```shell
grep "#define Q3_VERSION"
```
breaks compatibility with my older 32-bit build environment (grep v.2.14) so I'm going to use _a bit more_ complex expression:
```shell
grep ".\+define[ \t]\+Q3_VERSION[ \t]\+\+"
```
