### ISSUE TITLE
Pink screen overlayer on screen when in fullscreen mode 

### ISSUE THREAD

**Issue by rykerOnGithubDotCom** [ec-/Quake3e#192]
I use a Linux Mint 64x OS with a NVIDIA Geoforce graphics card w/ drivers properly installed and a 4k monitor. I tried to run Quake3e in the most current build as of writing and there is a pink overlay over the entire screen. This will not occur in windowed mode.

**Comment by ensiform** [comment]
r_fastsky set to 1?

**Comment by rykerOnGithubDotCom** [comment]
Setting the fastsky var does nothing, this happens on the title screen and in-game

**Comment by ensiform** [comment]
I'm asking if it was.

Which binary are you using? OpenGL based or vulkan backend.

Post your console log with graphics info. From starting with `+set logfile 4` it will be in the q3a home path directory somewhere as `qconsole.log`

Could be issue with your graphics driver or external settings as well, without more specific information available. My Manjaro machine runs both OpenGL and vulkan on 520 drivers just fine.

**Comment by rykerOnGithubDotCom** [comment]
I tried both OpenGL and Vulkan and same results, I mainly use OpenGl. The pink covers the console aswell. I did the set logfile 4 thing and no file was created. It looks normal in screenshots and it only looks pink after about a half of a second of the game being focused. Here is a photograph:
![DSC00081](https://user-images.githubusercontent.com/96715006/199887821-a58bc71c-7cd1-4a20-9183-b5478001b58e.JPG)

**Comment by ensiform** [comment]
> I tried both OpenGL and Vulkan and same results, I mainly use OpenGl. The pink covers the console aswell. I did the set logfile 4 thing and no file was created. It looks normal in screenshots and it only looks pink after about a half of a second of the game being focused. Here is a photograph:
> ![DSC00081](https://user-images.githubusercontent.com/96715006/199887821-a58bc71c-7cd1-4a20-9183-b5478001b58e.JPG)
> 

You checked home/.q3a/baseq3/ ?

**Comment by rykerOnGithubDotCom** [comment]
Here's the log:
[qconsole.log](https://github.com/ec-/Quake3e/files/9941327/qconsole.log)

**Comment by ec-** [comment]
> Using 24 color bits, 24 depth, 0 stencil display.

try with **\r_stencilBits 8**

**Comment by rykerOnGithubDotCom** [comment]
> > Using 24 color bits, 24 depth, 0 stencil display.
> 
> try with **\r_stencilBits 8**

Still happening

**Comment by ec-** [comment]
Please share your **q3config.cfg**

**Comment by rykerOnGithubDotCom** [comment]
[q3config.cfg.txt](https://github.com/ec-/Quake3e/files/9944846/q3config.cfg.txt)

**Comment by ensiform** [comment]
> [q3config.cfg.txt](https://github.com/ec-/Quake3e/files/9944846/q3config.cfg.txt)
> 

Looks like missing `r_fbo 1` and you do have fast sky enabled. And stencilbits still showing as 0

**Comment by rykerOnGithubDotCom** [comment]
fastsky and stencilbits don't do anything to fix it. When r_fbo is set to 1 it produces this in windowed and fullscreen but fixes the pink as far as I know.
![image](https://user-images.githubusercontent.com/96715006/200159228-73d4bdc2-490e-49e2-a7fd-ebbf9c938b3a.png)

**Comment by ensiform** [comment]
> fastsky and stencilbits don't do anything to fix it. When r_fbo is set to 1 it produces this in windowed and fullscreen but fixes the pink as far as I know.
> ![image](https://user-images.githubusercontent.com/96715006/200159228-73d4bdc2-490e-49e2-a7fd-ebbf9c938b3a.png)
> 

Looks like your GPU dying or some kind of driver problem.

**Comment by ec-** [comment]
I see, I suspect than this nvidia driver has gamma ramp size > 256 and SDL2 can't handle it properly, try to compile engine with `USE_SDL=0` make option and check

**Comment by KuehnhammerTobias** [comment]
My personal opinion is tha r_gamma and r_intensity should never be >1. Yours is 3! When I choose a value higher than 1 my Q3e installation look as as ugly as the screenshot above.

**Comment by rykerOnGithubDotCom** [comment]
Thank you, KuehnhammerTobias, it was my gamma and intensity that was causing it. All I have to do was set r_fbo and the gamma and intensity values to one and it is back to normal.
