### ISSUE TITLE
Weird Low Damage/Health Glitch

### ISSUE THREAD

**Issue by rykerOnGithubDotCom** [ec-/Quake3e#195]
Me and my brother wanted to duel in Quake 3 both using quake3e, but for some reason, my brother would always spawn at 30 health and it would drain down to 5 health gradually, and he would do super low damage regardless of armor. He had just installed the game off of Steam for the first time and replaced his exe with quake3e's exe and had no mods or had not joined any other servers before hand. He was the one who hosted the LAN server.
    He also played singleplayer and the same thing happened. We also joined a empty server together in tournament mode and the same thing happened. Me and my brother tried many different player models and no difference. This is the most crazy thing i've ever seen in quake 3, if this isn't a quake3e bug specifically then I hope this source port can be the first to fix it.

My view (When we first played on my brother's LAN server):
https://youtu.be/2zKss9bXDf4

My brother's view (Playing singleplayer):
https://youtu.be/JFn77WqncnY

I play on Linux and my brother plays on Windows.

**Comment by ensiform** [comment]
You have a/mods installed that affect the gameplay like that. Won't be related to quake3e.

**Comment by rykerOnGithubDotCom** [comment]
Yeah, it was the handicap option, i didn't know it did that.
