### ISSUE TITLE
Dedicated server

### ISSUE THREAD

**Issue by QuintenQVD0** [ec-/Quake3e#196]
Hello

I try to run the dedicated server in a docker container but it prints this messgae
Sys_Error: Unable to create directory "//.q3a", error is Read-only file system(30)

The container is hard lockt to only allow /home/container and sub directory's
Is there a way I can change this behavear?

**Comment by ensiform** [comment]
The same as all idtech3 engines,

`+set fs_homepath "insert your path where files can be written to"`

**Comment by QuintenQVD0** [comment]
anyone?

**Comment by ec-** [comment]
Try `+set fs_homepath "~/.q3a"`, it is an issue with system paths, not engine
