### ISSUE TITLE
I want your permission to submit a version of OpenARENA that uses Quake3e as its engine to Flathub.

### ISSUE THREAD

**Issue by xplshn** [ec-/Quake3e#197]
I've been trying to build Quake3e as a FlatPak for past few days and I finally got it to run yesterday, today I finished resolving all issues I had, so its mostly ready for submission, I'm just waiting for your permission to submit it, as it is a requirement for all applications to be submitted to Flathub to be given permission by the original developer of the program. Feel free to contact me, here's an email alias: h8sptkzzy@mozmail.com

**Comment by ec-** [comment]
You don't need my explicit permission: GPLv2 **granted it by default**.
So as long as you follow GPLv2 licence terms - feel free to do whatever you want with Quake3e

**Comment by xplshn** [comment]
Yes, thank you, it is a requirement from Flathub that I have explicit permission, I'll tell you when they accept my request and the app goes up

**Comment by xplshn** [comment]
> Yes, thank you, it is a requirement from Flathub that I have explicit permission, I'll tell you when they accept my request and the app goes up
Here it is:
https://flathub.org/apps/details/io.github.ec_.Quake3e.OpenArena

**Comment by Calinou** [comment]
This issue can be closed now that https://flathub.org/apps/details/io.github.ec_.Quake3e.OpenArena is available :slightly_smiling_face:
