### ISSUE TITLE
Feature request: pk3dir support from ioquake3

### ISSUE THREAD

**Issue by ensiform** [ec-/Quake3e#2]
Useful for development

Have folder with ".pk3dir" at end and it will be treated like a pk3 file but is just a folder within mod folder.

**Comment by KuehnhammerTobias** [comment]
... or even cooperate with [Chomenor](https://github.com/Chomenor) and include his new filesystem. His project has enhanced developer support along with other improvements concerning folders/directories (personally I use  it for a while now and it seems to work fine).
He recently refered to why a [pk3dir](https://github.com/Chomenor/ioq3_new_filesystem/commit/1a03cf23e66561a69299feb07afb4454e1657a00) isn't really needed. Check out his [README](https://github.com/Chomenor/ioq3_new_filesystem/blob/master/new-filesystem-readme.md) for more informations concerning pk3dir and debugging. Just a thought! What do you think?

**Comment by ensiform** [comment]
His system is too complex and breaky.

**Comment by KuehnhammerTobias** [comment]
You're the first one with constructive criticism, and an explanation of your concerns! Thank You very much for your clarification ensiform!

**Comment by ensiform** [comment]
Mind you I have not studied most of it in detail or in depth.  I just don't see the benefits of the total rewrite for something that is meant to be compatible with existing mods and games based on tech3.  It is definitely beneficial for a new game with new assets.

**Comment by KuehnhammerTobias** [comment]
Lucky You! You can study code from others at least! From an amateur's perspective, I have no clue of any pk3dirs/pak sorting/etc. programming. I simply can try and see if something works for me, or not.
I don't have the skills to judge someone's code. Unvanquished for example is a bit of a mess to me, although probably experts know what they are doing. [ztutleman's pak sorting](https://github.com/zturtleman/spearmint/wiki/Mint-Game-Settings) (accessing pk3s via text file) is very handy, on the other hand sometimes it also doesn't work as I suspect, although it helped me alot during development. It seems to me Chomenor's work prints more developer messages, messages ioquake3 doesn't show at all, definitely an improvement... well, I don't know! As already said I'm no expert!
I'm sure you'll find a good solution!
