### ISSUE TITLE
Vulkan render issue: returned VK_ERROR_DEVICE_LOST

### ISSUE THREAD

**Issue by RaymanMago1265** [ec-/Quake3e#200]
This happens with some official maps, when you fall on the lava or there's some many explosions, the game closes and pops-up an error.
Idk if this issue can be fixable or not,  my processor is an AMD-A9 9430 RADEON R5.

Screenshot for reference:
[https://imgur.com/a/zvPNeuo](url)

**Comment by ec-** [comment]
Test with latest build

**Comment by RaymanMago1265** [comment]
> Test with latest build

I did, but i got the same issue

**Comment by RaymanMago1265** [comment]
Update: I tested before and with the lastest build.
I found probably the reason why i had that weird crash, the solution was to uninstall and downgrade to an old build of amd. 
In other words, Quake3e hates AMD Adrenaline.

**Comment by ec-** [comment]
Please tell AMD driver version you are using and hardware, at least for now, it might be useful to guide in similar cases

**Comment by RaymanMago1265** [comment]
> Please tell AMD driver version you are using and hardware, at least for now, it might be useful to guide in similar cases

I was using Radeon™ Software Adrenalin 22.1.2  driver, my hardware i said was a AMD-A9 9430 RADEON R5 (Integrated in my HP All-in-One) and downgraded to 17.12.

Thanks for make Quake III on new OS.
