### ISSUE TITLE
Quake3e application is frozen when alt+tab

### ISSUE THREAD

**Issue by d1zulya** [ec-/Quake3e#201]
This is weird, never had anything like this with any application.
This happens when I am alt+tab to another application during the game. So if you launch the quake3e.x64.exe, capturing it with OBS and alt+tab, the game screen will freeze. It would be fine if you alt+tab to a game again.
You can see it at https://www.twitch.tv/videos/1700564197?t=3h18m35s (game sounds are still on while the screen is frozen).
If you alt+enter before alt+tab (so the game will be in a window mode) it will be fine.

**Comment by ec-** [comment]
If game window minimizes - it is by design, because:
1) OBS can't capture offscreen surfaces
2) _at least_ NVidia can't render to offscreen surfaces

Use windowed + `r_noborder 1` mode as workaround or switch to multi-monitor setup

**Comment by ensiform** [comment]
Is `\r_fbo 1` assuming using opengl backend.

**Comment by ec-** [comment]
backend/renderer shouldn't matter: if game window is minimized (offscreen) then it will not be rendered/**presented** and thus - not captured by OBS

**Comment by d1zulya** [comment]
> Use windowed + `r_noborder 1` mode as workaround

It works now, thanks! :)
