### ISSUE TITLE
Not building with mingw64

### ISSUE THREAD

**Issue by Kr3m** [ec-/Quake3e#209]
lto-wrapper.exe: warning: using serial compilation of 11 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information

code/win32/glw_win.h:63:19: warning: type of 'glw_state' does not match original declaration [-Wlto-type-mismatch]
   63 | extern glwstate_t glw_state;
      |                   ^
code/sdl/sdl_glimp.c:48:12: note: 'glw_state' was previously declared here
   48 | glwstate_t glw_state;
      |            ^
code/sdl/sdl_glimp.c:48:12: note: code may be misoptimized unless '-fno-strict-aliasing' is used
lto-wrapper.exe: warning: using serial compilation of 19 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information

code/win32/glw_win.h:63:19: warning: type of 'glw_state' does not match original declaration [-Wlto-type-mismatch]
   63 | extern glwstate_t glw_state;
      |                   ^
code/sdl/sdl_glimp.c:48:12: note: 'glw_state' was previously declared here
   48 | glwstate_t glw_state;
      |            ^
code/sdl/sdl_glimp.c:48:12: note: code may be misoptimized unless '-fno-strict-aliasing' is used
lto-wrapper.exe: warning: using serial compilation of 19 LTRANS jobs
lto-wrapper.exe: note: see the '-flto' option documentation for more information
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-mprintf.o):mprintf.c:(.text+0x1824): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-mprintf.o):mprintf.c:(.text+0x18be): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-strerror.o):strerror.c:(.text+0x6f4): undefined reference to `__imp__sys_nerr'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-cookie.o):cookie.c:(.text+0x19ad): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-cookie.o):cookie.c:(.text+0x1d22): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-url.o):url.c:(.text+0xb7a): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-url.o):url.c:(.text+0x34f9): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe:
 code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-formdata.o):formdata.c:(.text+0x1023): undefined reference to `__imp___iob_func'
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: code/libcurl/windows/mingw/lib64/libcurl.a(libcurl_la-formdata.o):formdata.c:(.text+0x1259): more undefined references to `__imp___iob_func' follow
collect2.exe: error: ld returned 1 exit status
make[2]: *** [Makefile:1094: build/release-mingw64-x86_64/quake3e.x64.exe] Error 1
make[2]: Leaving directory '/c/Users/kremi/OneDrive/Documents/GitHub/Quake3e'
make[1]: *** [Makefile:658: targets] Error 2
make[1]: Leaving directory '/c/Users/kremi/OneDrive/Documents/GitHub/Quake3e'
make: *** [Makefile:615: release] Error 2

**Comment by ec-** [comment]
`ucrt64` environment is not supported, use either `mingw64` or `mingw32`

**Comment by Kr3m** [comment]
> `ucrt64` environment is not supported, use either `mingw64` or `mingw32`

Yeah, I got it sorted out, and even got it to cross-compile in Linux so I'm happy.  =D
