### ISSUE TITLE
[Question] How can I play Quake3e in widescreen 1080p?

### ISSUE THREAD

**Issue by ghost** [ec-/Quake3e#213]

**Comment by ensiform** [comment]
What resolution is your monitor?

r_modeFullscreen -2 uses your monitor resolution, which is default.

r_mode controls windowed mode resolution only by default. Also can be -2 if you wish. Otherwise the options are the same as vanilla quake 3 using -1 and r_customWidth and r_customHeight cvars.

**Comment by Calinou** [comment]
Remember to also change field of view to match widescreen aspect ratios if you're not using https://clover.moe/flexible-hud-for-ioq3/ (which can't be done when playing online on servers that don't use this mod): `/cg_fov 106.26`
