### ISSUE TITLE
Anisotropic filtering has no effect in Vulkan renderer (but it works in opengl1)

### ISSUE THREAD

**Issue by Calinou** [ec-/Quake3e#215]
**OS:** Fedora 37
**GPU:** GeForce RTX 4090 (NVIDIA 525.89.02)
**Quake3e version:** 07354f58cb0008b8700dc7563994a324075c7630

Cvars:

```
r_ext_texture_filter_anisotropic 1
r_ext_max_anisotropy 16
r_texturemode GL_LINEAR_MIPMAP_LINEAR
```

I made sure to run `vid_restart` after changing cvars.

## `cl_renderer vulkan`

*No anisotropic filtering visible (visual output is identical to `r_ext_texture_filter_anisotropic 0`).*

![s webp](https://user-images.githubusercontent.com/180032/228393064-d7572f8a-44a5-4f5b-867f-6eb17571a9c7.png)

## `cl_renderer opengl`

*Anisotropic filtering works as expected.*

![out webp](https://user-images.githubusercontent.com/180032/228393068-4c6bc63e-4285-46ed-a921-aa1e34127d51.png)

### Console output after running `cl_renderer vulkan; vid_restart`

```
----- Initializing Renderer ----
-------------------------------
----- R_Init -----
SDL using driver "x11"
Initializing Vulkan display
...setting mode -2: 3840 2160
Using 24 color bits, 24 depth, 8 stencil display.
.......................
Available physical devices:
 0: Discrete NVIDIA GeForce RTX 4090, 0x2684
 1: CPU llvmpipe (LLVM 15.0.7, 256 bits), 0x0000
.......................
...selected physical device: 0
][2023-03-29 01:04:58.429] [MANGOHUD] [info] [overlay.cpp:768] Uploading is disabled (permit_upload = 0)
...presentation modes: FIFO FIFO_RELAXED IMMEDIATE 
...selected presentation mode: IMMEDIATE, image count: 3
 
VK_VENDOR: NVIDIA
VK_RENDERER: Discrete NVIDIA GeForce RTX 4090, 0x2684
VK_VERSION: API: 1.3.224, Driver: 525.89.2.0
 
VK_MAX_TEXTURE_SIZE: 2048
VK_MAX_TEXTURE_UNITS: 8
 
PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
 presentation: VK_FORMAT_B8G8R8A8_UNORM
 color: VK_FORMAT_R16G16B16A16_UNORM
 capture: VK_FORMAT_R16G16B16A16_UNORM
 depth: VK_FORMAT_D24_UNORM_S8_UINT
RENDER: 7680 x 4320, MODE: -2, 3840 x 2160 fullscreen hz:120
GAMMA: hardware w/ 1 overbright bits
texturemode: GL_LINEAR_MIPMAP_LINEAR
texture bits: 32
picmip: 0
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound ------
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "pulseaudio".
SDL_AudioSpec:
  Format:   AUDIO_S16LSB
  Freq:     22050
  Samples:  512
  Channels: 2
Starting SDL audio callback...
SDL audio initialized.
----- Sound Info -----
    2 channels
16384 samples
   16 samplebits (int)
    1 submission_chunk
22050 speed
0x2a110280 dma buffer
No background file.
----------------------
Sound initialization successful.
--------------------------------
Sound memory manager started
Loading vm file vm/ui.qvm...
...which has vmMagic VM_MAGIC_VER2
Loading 1162 jump table targets
^3jump target 11 set on instruction 13586 (OP_CONST) with bad opStack 8
VM file ui compiled to 264200 bytes of code
ui loaded in 1054272 bytes on the hunk
36 arenas parsed
32 bots parsed
```

**Comment by ec-** [comment]
Works fine on my side (Intel iGPU), could you check with `\r_device 1` (llvmpipe software emulation in your case)?

**Comment by KuehnhammerTobias** [comment]
Like ensiform said (https://github.com/ec-/Quake3e/commit/4ac4d34c7a48d74081f6f189fe5e72314fc87756), I also think this one is related to: https://github.com/ec-/Quake3e/issues/147
What makes me wonder is why VK is broken this way, for GL2 it's just no longer implemented (sdl_glimp.c).
As far as VK rendering is concerned, I get more and more the impression that there is lot of (older) hardware out there, that has troubles with VK rendering at all, idk.

**Comment by Calinou** [comment]
> Works fine on my side (Intel iGPU), could you check with `\r_device 1` (llvmpipe software emulation in your case)?

I've tried `r_device 1` with Vulkan but still don't have working anisotropic filtering, despite rendering being very slow (which shows that llvmpipe is being used :stuck_out_tongue:).

**Comment by ensiform** [comment]
> Like ensiform said (https://github.com/ec-/Quake3e/commit/4ac4d34c7a48d74081f6f189fe5e72314fc87756), I also think this one is related to: https://github.com/ec-/Quake3e/issues/147
> What makes me wonder is why VK is broken this way, for GL2 it's just no longer implemented (sdl_glimp.c).
> As far as VK rendering is concerned, I get more and more the impression that there is lot of (older) hardware out there, that has troubles with VK rendering at all, idk.
> As a workaround you can enable the filtering through your NV panel (which doesn't seems to work for some users, though) :\

Gl2 is pretty much use at your own risk anyway.

Vulkan doesn't actually list the AF state like in opengl renderer so it's hard to say why it's disabled.

**Comment by GranMinigun** [comment]
On my system (Intel HD, Linux) AF in Vulkan renderer appears to work on the initial launch, but gets disabled on `vid_restart`.

**Comment by sashaaaaaaaaa** [comment]
AF doesn't work for me in Vulkan with a Radeon R9 390 in Linux

**Comment by Aciz** [comment]
I think I figured out the steps for reproducing this, and why people seem to have so different experience. Can't speak for AMD/Intel users but at least for me on Nvidia GTX 1080 Ti, on both Windows and Linux I experience scenarios where it doesn't work. However there's a 100% consistent way for me to fix it: change `r_textureMode` to something else, and then back to `GL_LINEAR_MIPMAP_LINEAR`. AF will not work if you start the game in `r_textureMode GL_LINEAR_MIPMAP_LINEAR`, you will need to change it to something else, then back to `GL_LINEAR_MIPMAP_LINEAR`, and AF starts working. Starting the game with `r_textureMode != GL_LINEAR_MIPMAP_LINEAR` and then changing to `r_textureMode GL_LINEAR_MIPMAP_LINEAR` works too. `vid_restart` doesn't seem to have any effect on the behavior, doing a `vid_restart` while AF is working does not break it for me.

**Comment by Wille-Helm** [comment]
Same here, I'm using a Radeon RX 6800 XT and the trick with r_texturemode works too.

**Comment by ec-** [comment]
Please check latest build

**Comment by Aciz** [comment]
Seems to be resolved, no need to toggle `r_textreMode` anymore. Tested Linux x64 but I doubt it's platform specific in any way.

**Comment by GranMinigun** [comment]
Confirming works here too.

**Comment by Calinou** [comment]
It works on my end too as of https://github.com/ec-/Quake3e/commit/d90d628fda6fda861d63ddbeaa55882081ad9530, thanks :slightly_smiling_face:
