### ISSUE TITLE
mingw64 compile error.

### ISSUE THREAD

**Issue by Kr3m** [ec-/Quake3e#219]
code/win32/win_main.c: In function ‘Sys_Mkdir’:
code/win32/win_main.c:142:17: error: ‘EEXIST’ undeclared (first use in this function); did you mean ‘OF_EXIST’?

**Comment by garoto** [comment]
`master` compiles fine for me using busybox-w32+mingw-64 from version 1.18.0 of this package: https://github.com/skeeto/w64devkit

https://0x0.st/HPkl.html

**Comment by ec-** [comment]
This should be fixed with recent change, please check

**Comment by Kr3m** [comment]
> This should be fixed with recent change, please check

Works great now thanks.  =D
