### ISSUE TITLE
Feature Request: '/tell' bound to selfID

### ISSUE THREAD

**Issue by haxxus** [ec-/Quake3e#22]
This would be useful to me personally on a bot i'm working on for a .log parser and i don't think it would hurt anything, the request is to make /tell grab the user id if no id is specified.

For example, right now if tell is used without an active id it doesn't output on the .log, doesn't go past the client at all so the solution im using now is having the client use /tell selfID message, My request would automate this part.

If is something your willing to do Cyrax but have no time in doing so let me know and i can find someone to provide the code change that i will send to you for review.

**Comment by ensiform** [comment]
Specific to tell from the server?
