### ISSUE TITLE
Issue with instaunlagged mod compatibility

### ISSUE THREAD

**Issue by caje1** [ec-/Quake3e#220]
I'm having an issue where the instaunlagged mod (specifically IU1.2Beta3, which I've attached) crashes when trying to start a game. 

I can select it in the mod list, but when I actually try to start a game by creating a skirmish, it will go to the "Connecting to localhost...awaiting connection" screen and then immediately crash with my screen staying very bright. I'm not super technical, so I'm not sure where to look for an error/crash log. Other mods such as defrag work with no issues.

The mod works with both the original version of the game as well as ioquake 3. Any feedback or help would be appreciated.
[IU1.2Beta3.zip](https://github.com/ec-/Quake3e/files/11523763/IU1.2Beta3.zip)

**Comment by KG7x** [comment]
if put vm\qagame.qvm in IU1.2Beta3\pak0.pk3\vm\qagame.qvm or make new pk3 and put in vm\qagame.qvm work fine

**Comment by caje1** [comment]
That worked, thank you!
