### ISSUE TITLE
Add Ogg Vorbis support (required to connect to some OpenArena servers)

### ISSUE THREAD

**Issue by Calinou** [ec-/Quake3e#227]
It looks like Quake3e doesn't support Ogg Vorbis unlike ioquake3, which prevents connecting to servers hosting some OpenArena mods such as `rat`. See https://github.com/ec-/Quake3e/issues/197 for context.

```
cg_registerSounds(): Engine does not support Ogg Vorbis
```

The server aborts connection as (I assume) it's a pure server, so your client **must** be able to load the audio somehow.

While no Quake 3 mod makes use of Ogg Vorbis to my knowledge, this is absolutely required connect to some OpenArena servers.

**Comment by ensiform** [comment]
Nor OpenAL.

**Comment by KuehnhammerTobias** [comment]
@Calinou you can use the OmegA-engine if you want: https://github.com/EddieBrrrock/OmegA-engine
EddieBrrrock implemented OpenAL and OGG vorbis into Q3e, the OmegA-engine works well with rat mod etc., and his fork is up-to-date with current Q3e. There are other Q3e forks with OpenAL implemented, for example https://github.com/ec-/Quake3e/compare/master...ivanka2012:MiniQuake3:master and all the UrbanTerror Q3e forks (those even come with dmaHD).
Btw, implementing OpenAL into Q3e isn't that hard to manage, I just don't know HOW the developers want to have it implemented. https://github.com/ec-/Quake3e/issues/33
Anyways try the OmegA-engine meanwhile.

**Comment by ec-** [comment]
Ogg support from @EddieBrrrock looks clean as for me, I'll try to find some time backporting it to q3e

**Comment by ec-** [comment]
Please check current implementation
