### ISSUE TITLE
macOS Resolution

### ISSUE THREAD

**Issue by livid** [ec-/Quake3e#228]
It seems that Quake3e uses logical resolution instead of device resolution. Therefore, on a 4K screen with this scaling setting, I can't get Quake3e to run beyond 1920x1080.

<img width="482" alt="Screenshot 2023-06-27 at 3 07 59 AM" src="https://github.com/ec-/Quake3e/assets/11427/d4cfee2b-c6f8-48e0-9022-eda286ef220d">

**Comment by ensiform** [comment]
r_mode only applies to windowed mode. Not fullscreen.

r_modeFullscreen applies

**Comment by livid** [comment]
> r_mode only applies to windowed mode. Not fullscreen.
> 
> r_modeFullscreen applies, if blank it will use the former.

Thank you so much! It works!

Always a great feeling to learn something new in the Quake 3 open-source world.
