### ISSUE TITLE
Crash on Round End in Team Arena while using ZTM's Flexible HUD

### ISSUE THREAD

**Issue by OpenRift412** [ec-/Quake3e#235]
So I was playing Team Arena's singleplayer campaign when I noticed that upon finishing a round, the game froze almost instantly and completely locked up. Upon further inspection, I realized that this was caused by [ZTM's Flexible HUD mod](https://clover.moe/flexible-hud-for-ioq3/). Testing this without the mod and with ioQuake3, the game didn't seem to have much of a problem, but it seems that only Quake 3e does. 

I also tried both GL and Vulkan renderers, and both have the same issue.

**Comment by ec-** [comment]
Should be fixed in https://github.com/ec-/Quake3e/commit/624540863f1c1732adfb3a88b991447b0d9da666
