### ISSUE TITLE
Negative download percentage

### ISSUE THREAD

**Issue by thefakeryker** [ec-/Quake3e#238]
![image](https://github.com/ec-/Quake3e/assets/96715006/d7a9c1c5-2119-40a4-881e-86c245ce4d28)

**Comment by KuehnhammerTobias** [comment]
For reference @Chomenor recently fixed this: https://github.com/Chomenor/cmod-game-code/commit/4e080e2b115d2355e2b0c902f6d74ede94c8444e
Maybe good for baseq3a game code as well. Though, a fix engine-sided would be cool!

**Comment by ec-** [comment]
1. Not related to the engine
2. Seem to be fixed for [baseq3a](https://github.com/ec-/baseq3a) long time ago:
![pic](https://github.com/ec-/Quake3e/assets/6439984/f900df0d-ea88-4893-ba87-c7707bc981b6)
