### ISSUE TITLE
Team Arena: Crash when loading Singleplayer Match on Teamwerkz

### ISSUE THREAD

**Issue by OpenRift412** [ec-/Quake3e#239]
I get this error when loading it up:
![image](https://github.com/ec-/Quake3e/assets/29780788/2858688c-b5d1-4583-903e-d1451cfe80b8)

**Comment by ensiform** [comment]
What is your `com_hunkMegs` set to? Did you try increasing?

**Comment by OpenRift412** [comment]
> What is your `com_hunkMegs` set to? Did you try increasing?

It was set to 64, so I increased it to 128 and it seems to be working. I don't know why it was set to 64 when the default was apparently 128. Same in base Quake III as well.

**Comment by ensiform** [comment]
A config file or menu probably changed it.
