### ISSUE TITLE
Wide screen is forced on higher resolutions on macOS

### ISSUE THREAD

**Issue by Perlence** [ec-/Quake3e#241]
Hello everyone! First of all, thanks for all the work you put into optimizing the renderer! It's the only port I know of that makes Quake III Arena and UrbanTerror playable at 125 FPS on a MacBook Air M1.

I'm using the OpenGL renderer and I want to set a 4:3 resolution on the 16:10 screen. Setting `r_mode 6` (1024x768) works, the resulting image is 4:3, see Picture 1. However, setting `r_mode 7` (1152x864) and higher forces the game to fill the whole screen, see Picture 2. I've also tried setting custom 4:3 resolutions, but they were also forced to be wide.

<details>
<summary>Picture 1</summary>
<img src="https://github.com/ec-/Quake3e/assets/1044300/4b7e0672-a21d-4373-b3ad-b8f61ff2b762">
</details>

<details>
<summary>Picture 2</summary>
<img src="https://github.com/ec-/Quake3e/assets/1044300/91ee8e88-6bda-417c-b0c1-0c1630254922">
</details>

The related settings:

```
seta r_customPixelAspect "1"
seta r_customheight "1600"
seta r_customwidth "2133"
seta r_mode "-1"
seta r_modeFullscreen ""
seta r_fullscreen "1"
```

I'm not sure if the Vulkan renderer has this problem because I couldn't get it to work, see #183.

**Comment by ec-** [comment]
Modern drivers doesn't like custom resolutions so much. So if you want to keep black bars at sides (preserve aspect ratio - is that your point?) - then:
* always use native resolution in full-screen mode (**r_modeFullscreen "-2"**)
* set **r_fbo 1** - it will enable framebuffer post-processing
* set corresponding **r_renderScale** mode (see in-game description for this cvar)
* set any custom **r_renderWidth** / **r_renderHeight** you want
* issue `\vid_restart`

**Comment by Perlence** [comment]
Awesome, thanks, this is what I was looking for! I ended up with the following settings:

```
seta r_mode "6"
seta r_modeFullscreen "-1"
seta r_customWidth "2560"
seta r_customHeight "1600"
seta r_fbo "1"
seta r_renderWidth "2133"
seta r_renderHeight "1600"
seta r_renderScale "4"
```

I use `r_modeFullscreen "-1"` because with "-2" quake3e thinks the native resolution is 1280x800, but it's actually twice that.
