### ISSUE TITLE
Difference from ioq3?

### ISSUE THREAD

**Issue by VinnyVicious** [ec-/Quake3e#243]
What are the main differences from q3e to ioq3? Is it more stable for players?

**Comment by ec-** [comment]
Yes

**Comment by VinnyVicious** [comment]
Why?

**Comment by The-Gig** [comment]
One noticeable difference is the default homepath (settings and autodownload) folder. While ioquake3 set it as per-user (e.g. under %appdata% in Windows), Quake3e made it the same as the homepath (installation folder) like in the original game.
You can set it as you wish my adding "+fs_homepath <path>" parameter in your OS command line (e.g. in a shortcut).

**Comment by ec-** [comment]
Pretty much all key differences is listed in README.md, I see no need to duplicate it there

**Comment by kungfooman** [comment]
Personally I had audio bugs with Quake3e on Windows 10, while ioq3 was working nicely. I spawned many bots and rockets flying everywhere and it just crashed for some reason. So I would say... test both, and see which fork works for you.

**Comment by KG7x** [comment]
> Personally I had audio bugs with Quake3e on Windows 10, while ioq3 was working nicely. I spawned many bots and rockets flying everywhere and it just crashed for some reason. So I would say... test both, and see which fork works for you.

try check on clean config

**Comment by ensiform** [comment]
> Personally I had audio bugs with Quake3e on Windows 10, while ioq3 was working nicely. I spawned many bots and rockets flying everywhere and it just crashed for some reason. So I would say... test both, and see which fork works for you.

Did you turn off openal in ioq3 to get accurate comparison?

**Comment by ec-** [comment]
> Personally I had audio bugs with Quake3e on Windows 10

Please create separate issue with demo/reproduction steps
