### ISSUE TITLE
vid_restart fast not working with vulkan?

### ISSUE THREAD

**Issue by kevinmcq** [ec-/Quake3e#250]
vid_restart fast seems to work fine when cl_renderer is opengl, but when using vulkan I get the following crash/error:

> /vid_restart fast
> RE_Shutdown( 0 )
> ----- Initializing Renderer ----
> -------------------------------
> ----- R_Init -----
> Initializing Vulkan subsystem
> ...initializing QVK
> ...setting mode -1: 1920 1080 FS
> ...using desktop display depth of 32
> ...already fullscreen, avoiding redundant CDS
> ...window already present, CreateWindowEx skipped
> Cmd_AddCommand: minimize already defined
> Cmd_AddCommand: in_restart already defined
> .......................
> Available physical devices:
>  0: Discrete NVIDIA GeForce RTX 3080, 0x220a
> .......................
> ...selected physical device: 0
> ...using 8x MSAA
> ...presentation modes: FIFO FIFO_RELAXED MAILBOX IMMEDIATE
> ...selected presentation mode: IMMEDIATE, image count: 3
> ----- Client Shutdown (Server fatal crashed: Vulkan: qvkCreateSwapchainKHR( device, &desc, NULL, > swapchain ) returned VK_ERROR_NATIVE_WINDOW_IN_USE_KHR) -----
> RE_Shutdown( 3 )
> Shutting down Vulkan subsystem
> ...destroying window
> ...restoring display settings
> ...shutting down QVK
> ...unloading Vulkan DLL
> -----------------------
> ----- Server Shutdown (Server fatal crashed: Vulkan: qvkCreateSwapchainKHR( device, &desc, NULL, swapchain ) returned VK_ERROR_NATIVE_WINDOW_IN_USE_KHR) -----
> ==== ShutdownGame ====
> AAS shutdown.
> ---------------------------
> Vulkan: qvkCreateSwapchainKHR( device, &desc, NULL, swapchain ) returned > > > VK_ERROR_NATIVE_WINDOW_IN_USE_KHR

this is on windows 10, latest nvidia drivers

**Comment by ec-** [comment]
Thank you for feedback!
Please check [latest build](https://github.com/ec-/Quake3e/releases/tag/latest)

**Comment by kevinmcq** [comment]
latest build fixed it!
