### ISSUE TITLE
Clarification needed: Why fs_homepath is write protected?

### ISSUE THREAD

**Issue by xplshn** [ec-/Quake3e#251]
What does that error mean? I wanted to change the folder to which the user config is saved in my Flatpak of OpenArena, and it resulted in this error when I changed the CVAR fs_homepath.

**Comment by ec-** [comment]
Set it from command line by adding `+set fs_homepath <path>` as it is not allowed to change such parameters at runtime

**Comment by xplshn** [comment]
I did just that, the error that kept coming was "fs_homepath is write protected."

**Comment by xplshn** [comment]
We currently use this patch in our engine:

`diff --git a/code/unix/unix_shared.c b/code/unix/unix_shared.c
index 8a988ba0..8b491239 100644
--- a/code/unix/unix_shared.c
+++ b/code/unix/unix_shared.c
@@ -414,7 +414,7 @@ const char *Sys_DefaultHomePath( void )
 #ifdef MACOS_X
 		Q_strcat( homePath, sizeof(homePath), "/Library/Application Support/Quake3" );
 #else
-		Q_strcat( homePath, sizeof( homePath ), "/.q3a" );
+		Q_strcat( homePath, sizeof( homePath ), "/.openarena" );
 #endif
 		if ( mkdir( homePath, 0750 ) ) 
 		{`

But we need to be able to point the homepath to another folder in order to run some mods and different games. Could it be because of the patch? I'm not familiar with how the Quake3 engine handles

**Comment by ensiform** [comment]
Are you using `+set fs_homepath "blah"` only on the command line? Because this is the only place it can be set as it is before the filesystem is loaded.

If the message is still appearing either you're missing `+set` or somehow it's not being processed during startup args like a normal process or you entered it in game console which is too late.

**Comment by xplshn** [comment]
Yes, only in the starting script for my flatpak have I added the CVAR, using +set.
