### ISSUE TITLE
more of a question than an issue, but is it possible to use this engine to boot games that run on the quake 3 engine?

### ISSUE THREAD

**Issue by F3arM3** [ec-/Quake3e#258]
I am asking this because I recently aquired a copy of star trek voyager elite force which runs on the quake 3 engine and I would like to if possible play it natively on linux

**Comment by ec-** [comment]
If you can run your game/mod with original quake3 1.32 release then probably yes, otherwise not becase renderers/qvms/dlls/syscalls might be not compatible
