### ISSUE TITLE
Arm64 version doesnt work.

### ISSUE THREAD

**Issue by Davo6233** [ec-/Quake3e#259]
Hello, quake3e-windows-msvc-arm64 package doesnt work, because Windows on ARM doesnt support OpenGL or Vulkan. Could you make DirectX12 version? :P That would be great.

**Comment by ensiform** [comment]
Just use the compatibility pack.

https://apps.microsoft.com/detail/9NQPSL29BFFF?hl=en-us&gl=US

**Comment by ec-** [comment]
I wouldn't bother adding non-portable renderer just to mitigate "NIH"/vendor-lock policy of MS, both OpenGL and Vulkan is an industrial standards

**Comment by ArminiusTux** [comment]
Impressive & stable WinARM support, not only by supplying a server.exe but also a Vulkan ready client (although Windows on ARM devices still lack support for this API).

If only this [sister project](https://github.com/JACoders/OpenJK), would wield the force of reduced instructions in a similar fashion. 😉
