### ISSUE TITLE
compile crash, then game crash

### ISSUE THREAD

**Issue by Captaintoottoot** [ec-/Quake3e#26]
I am using visual studio 2017.  When I compile I get the following error:

1>------ Build started: Project: quake3e, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(1198,5): warning MSB8012: TargetPath(M:\ztemp\Quake3e Sep\Quake3e-master\code\win32\msvc2017\.\output\quake3e.exe) does not match the Linker's OutputFile property value (M:\ztemp\Quake3e Sep\Quake3e-master\code\win32\msvc2017\output\quake3e.x64.exe). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(1200,5): warning MSB8012: TargetName(quake3e) does not match the Linker's OutputFile property value (quake3e.x64). This may cause your project to build incorrectly. To correct this, please make sure that $(OutDir), $(TargetName) and $(TargetExt) property values match the value specified in %(Link.OutputFile).
1>   Creating library .\output\quake3e.lib and object .\output\quake3e.exp
1>cl_main.obj : error LNK2019: unresolved external symbol CL_SaveJPGToBuffer referenced in function CL_InitRef
1>cl_main.obj : error LNK2019: unresolved external symbol CL_SaveJPG referenced in function CL_InitRef
1>cl_main.obj : error LNK2019: unresolved external symbol CL_LoadJPG referenced in function CL_InitRef
1>.\output\quake3e.x64.exe : fatal error LNK1120: 3 unresolved externals
1>Done building project "quake3e.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========

Something about the jpg stuff is causing problems, so I removed the jpg screenshot ability, commenting out CL_SaveJPGToBuffer, CL_SaveJPG, and part of the CL_LoadJPG.  It compiles fine with no errors.  But then the game crashes on load.  Here is what the console says before it quickly exits: 
![quakee crash](https://user-images.githubusercontent.com/10479366/64739245-8f540100-d4bf-11e9-86c3-7bf8d0cfde3d.jpg)

**Comment by ensiform** [comment]
You can't comment out the jpeg stuff. Else the images won't load :joy:

**Comment by Captaintoottoot** [comment]
I left the loadjpg partly so the parts in like tr_image would still work.  But I removed the saving and the screenshot parts.  I was just trying a quick hack.  What would be causing this to not compile right out of the box though?
