### ISSUE TITLE
fs_basegame behavior with mods errors with Couldn't load default.cfg

### ISSUE THREAD

**Issue by WHS-Phoenix** [ec-/Quake3e#260]
Tried to run Generations Arena in Team Arena mode with the following launch options:

"C:\Games\Quake 3 132\quake3e.x64.exe" +set fs_basegame missionpack +set fs_game generations

Console reports:

----- FS_Startup -----
...found 16 cached paks
...loaded in 8 milliseconds
----------------------
9364 files in 16 pk3 files
Couldn't load default.cfg

I do not have this problem with Quake3 1.32b or IOquake3.  The correct behavior is for Q3A to load assets from baseq3, missionpack, then generations folders.

**Comment by ensiform** [comment]
fs_basegame missionpack implies you are not having baseq3 anymore. And missionpack does not ship a default.cfg

**Comment by ensiform** [comment]
Would you prefer restoring behavior or maybe an extra cvar like fs_extragame or something?

**Comment by ec-** [comment]
I'd rather add support for multiple (space-separated) values in `fs_basegame` or something like that

**Comment by WHS-Phoenix** [comment]
@ensiform If you're not using Quake3e without baseq3 (a standalone build) wouldn't you be changing the base path on compile anyway?  In that context fs_basegame would seem to serve no purpose.

@ec- So, something like "+set fs_basegame baseq3 missionpack +set fs_game modname", with the argument sequence for fs_basegame determining load priority?

**Comment by ensiform** [comment]
It would be useful still for example with baseoa or something standalone. But IMHO how many mods do you really want to.

The basepath may still differ but you can still have different default mod path such as openarena I guess, since basepath is the root not the mod subdir.

**Comment by WHS-Phoenix** [comment]
For my own project I did some tinkering and worked around it to restore the search order since Generations is dependent on baseq3 existing.  If an official change comes I'll update my codebase to include but for now it works for me.

**Comment by ec-** [comment]
Applied in https://github.com/ec-/Quake3e/commit/93cb4701f3ca8e38849cd3fcb270be77b4aec331, please test by using `+set fs_basegame "baseq3/missionpack"`

**Comment by WHS-Phoenix** [comment]
It functions, however any boolean conditions that I have checked against fs_basegame within the game source fail since they are expecting "missionpack", not "baseq3/missionpack".  Examples would be spawning in Team-Arena specific weapons as opposed to replacing them with alternatives (eg, Shotgun for TA Nailgun, Lightning Gun for TA Chaingun, and Grenade Launcher for TA Prox Launcher, and ammo, et al).  I can fix that in my mod by changing the string comparison to account for this, though I'm not sure if any other projects out there explicitly check fs_basegame for any of their internal logic.

**Comment by ec-** [comment]
> I can fix that in my mod by changing the string comparison to account for this
do it for now, I guess there's no other projects that need such functionality
