### ISSUE TITLE
WASAPI: unsupported channel count 6

### ISSUE THREAD

**Issue by gregorypiro** [ec-/Quake3e#265]
So, guys i have 5.1 surround headphones, is there anyway i can set it up with q3e under windows 11? I will be appreciate for ANY directions..

I attached picture of communicate in this issue.
![WASAPI](https://github.com/ec-/Quake3e/assets/112812393/58f8aa19-6d2d-4e43-ab0c-c3058be98277)

**Comment by ec-** [comment]
There is no support for more than 2 channel audio in Q3e, consider using some compatibility settings atm
