### ISSUE TITLE
Increase max sv_dlRate

### ISSUE THREAD

**Issue by ostrich** [ec-/Quake3e#267]
`sv_dlRate` is capped at 500 (K/s). Assuming clients can support it, please consider removing the cap or increasing it to something much higher.

**Comment by ensiform** [comment]
Why? It only applies to udp downloads. Using http downloads isn't affected by the cap. The udp cap  will still be not very great if you keep compatibility with all clients. The udp download speed fixes from ioq3 are already applied to get them as high as they can be.

**Comment by ostrich** [comment]
Why? My ignorance of running a modern Q3 server. I didn't know about the http download functionality.
