### ISSUE TITLE
Quake 3 enhanced has weird annoying noisy sound when running *WORKAROUND AVAILABLE*

### ISSUE THREAD

**Issue by mae-lippert** [ec-/Quake3e#268]
Hi, when i start my self compiled executable from most recent quake 3 enhanced sources i only hear a weird annoying noisy sound the whole time the game runs! i dont hear ANY other original sounds from the game! the noise vanishes when i minimize the game but at once reappears when switch back to the game!

i use a creative soundblaster AE-7 with latest sound drivers and soundblaster command control software with a classic analog 5.1 speaker setup under windows 11 with latest updates and bios updates of the mainboard! i own a huge collection of steam and battle.net games that are working ALL flawlessy!

is this already known? could you fix this please? thank you all for this project and PLEASE keep up the good work! this game is an all-time triple AAA legend and should be continued to be maintained to run on most modern systems! in my teenager years it was a lan party "must-have"!

**Comment by ensiform** [comment]
It's not already known. What's the sound? Is there missing sound errors?

**Comment by mae-lippert** [comment]
> It's not already known. What's the sound? Is there missing sound errors?

There a NO missing sound errors according to the log! or any errors or warnings shown at all!

how to describe that sound? i will try... its like a "white noise pattern sound" with a frequency of 35 - 40 hz!

i made an maybe important discovery and have now a "workaround solution":

when i switch via the sound blaster command control software the AE-7 sound card to "direct mode" in the playback section i have NOT that annoiying sound and ALL sounds, ingame movies and music is working flawlessy as expected! this "workaround solution" applies to all audio bit depths up to 32 bit and sampling frequencies up to 384 khz! but i have then in "direct mode" only 2.1 stereo sound and not 5.1 surround sound and i have to manually switch her forth and back to this "direct mode" which is a little bit annoying just to play this still great game because every other game i own work in 5.1 surround mode flawlessy! is this fixable?

**Comment by mae-lippert** [comment]
are there any "smart" console commands to change permanently the audio subsystem to an alternate one? this could maybe also help here!

**Comment by ec-** [comment]
After game starts, execute `\condump 123.txt` and post 123.txt file there (for both cases)

**Comment by mae-lippert** [comment]
[2.1-direct-stereo-mode.txt](https://github.com/ec-/Quake3e/files/14393076/2.1-direct-stereo-mode.txt)
[5.1-surround-mode.txt](https://github.com/ec-/Quake3e/files/14393077/5.1-surround-mode.txt)

https://github.com/ec-/Quake3e/assets/26750889/add05e16-a690-4d46-979b-a40beb55eac0

Hi, sorry for my very late reply...i was in holidays with my family :-)

i created the requested console dumps and made also a 10 seconds recording of that sound when running quake 3 enhanced on my creative soundblaster AE-7 in surround mode. you have maybe to tune up a bit the volume because when i recorded it with my mobile phone i had lower the volume because its very painfull at normal volume in my (and my families) ears, sorry for the inconvinience!

**Comment by ec-** [comment]
```
SDL_Init( SDL_INIT_AUDIO )... OK
SDL audio driver is "wasapi".
SDL_AudioSpec:
  Format:   AUDIO_F32LSB
  Freq:     22050
  Samples:  493
  Channels: 6
  ```

Why you're using SDL build on Windows? Compile either with `USE_SDL=0` switch or use pre-compiled binaries, Quake 3 do not support surround sound anyway so consider using some compatibility/forced stereo profile

**Comment by mae-lippert** [comment]
ok, case closed! thanks for your advice! i just recompiled the binaries with USE_SDL=0 in makefile.local, tested it and everything sounds now even in surround mode as it should be! i choosed sdl because in my past i never had problems with the sdl library so far... but i will remember this, thanks again!

**Comment by mae-lippert** [comment]
ok, case closed! thanks for your advice! i just recompiled the binaries with USE_SDL=0 in makefile.local, tested it and everything sounds now even in surround mode as it should be! i choosed sdl because in my past i never had problems with the sdl library so far... but i will remember this, thanks again!
