### ISSUE TITLE
R_TEXTUREMODE is not behaving persistently through sessions with the Vulkan renderer

### ISSUE THREAD

**Issue by ConHuevosGuey** [ec-/Quake3e#272]
**PROBLEM**
When setting 'r_texturemode' to "GL_NEAREST" or "GL_NEAREST_MIPMAP_NEAREST" the game is saving the value however it is not applying it when it is exited and launched again.  The texture mode will always be a linear filter.

When launching the game after saving the setting, the 'r_texturemode' value is correctly displaying "GL_NEAREST" but the actual texture filtering applied is linear.  Only by changing it to another texture filter will it actually be applied.

I made a video example however it's larger than 10MB so I'm unable to attach it and whenever I record Quake3E my gamma on my monitor turns up really high only on the monito Q3e is on but appears dark in OBS where it's being recorded.    So it may be difficult to see the difference between the linear/nearest filter because it's so dark.

Link to video:
[https://streamable.com/uk1i2i](url)

If there is a way to fix this brightness issue, I'd love to know.

**Comment by ensiform** [comment]
Already reported as part of #215.

Reset the value to something else and then change it to desired and it fixes it.

**Comment by ec-** [comment]
That should be fixed in https://github.com/ec-/Quake3e/commit/d90d628fda6fda861d63ddbeaa55882081ad9530

**Comment by ConHuevosGuey** [comment]
> That should be fixed in [d90d628](https://github.com/ec-/Quake3e/commit/d90d628fda6fda861d63ddbeaa55882081ad9530)

Thanks, it now functions properly.

Regarding the brightness issue, r_fbo 1 fixes it.  Thanks to ensiform mentioning it here:  https://github.com/ec-/Quake3e/issues/29#issuecomment-533823073
