### ISSUE TITLE
r_gamma command doesn't work anymore

### ISSUE THREAD

**Issue by v1l3dq** [ec-/Quake3e#279]
I just wanted to bring up that r_gamma hasn't been working on my laptops since long ago with your updates.  I've been using the last quake3e.x64 exe that it works on that you released on April 18, 2022 for some time.  I've checked your updates to see if you have fixed it or not, but I still see that it is not fixed.  So I figured that I would bring it up. 

Thank you.

My laptop specs are:

Alienwarem18rc1
AMD Ryzen 9 7845HX with Radeon Graphics           3.00 GHz
64-bit operating system, x64-based processor
Nvidia RTX 4070 Laptop GPU
31.19 GB RAM
Windows 11 Pro (Version 23H2)

**Comment by ensiform** [comment]
Have you ever enabled r_fbo 1?

**Comment by v1l3dq** [comment]
What are the settings for r_fbo?  The same as r_gamma?   I commonly use r_gamma 1.0 to 1.9, depending on what is needed.  Some mappers on custom maps make their maps so dark that you cannot see your way around on the default gamma settings.  This is why I have always been so dependant upon that cvar.  I play mostly custom maps from ..::LvL and such.

With r_fbo it says it works in window mode.  I commonly play r_fullscreen "1"

I love EDawn btw!!!  The mod, etc.

**Comment by ensiform** [comment]
`r_fbo 1` is what you need to use. It makes gamma shaders work and a bunch of other features that are added in the renderer

**Comment by ec-** [comment]
post your `\condump` & `q3config.cfg` contents, I suspect that you have `r_ignorehwgamma 1` or something similar

**Comment by v1l3dq** [comment]
// generated by quake, do not modify
unbindall
bind 0x00 "weapon 7"
bind TAB "+scores"
bind ENTER "weapon 5"
bind ESCAPE "togglemenu"
bind SPACE "messagemode"
bind + "sizeup"
bind - "sizedown"
bind / "weapnext"
bind 0 "weapon 10"
bind 1 "weapon 4"
bind 2 "weapon 1"
bind 3 "weapon 3"
bind 4 "weapon 7"
bind 5 "rcon status"
bind 6 "weapon 6"
bind 7 "rcon disable_item_invis 1"
bind 8 "weapon 8"
bind 9 "weapon 9"
bind = "sizeup"
bind [ "weapprev"
bind \ "+mlook"
bind ] "weapnext"
bind _ "sizedown"
bind ` "toggleconsole"
bind a "+moveleft"
bind b "exec my_botsnames.cfg"
bind c "clear"
bind d "+moveright"
bind e "weapon 6"
bind f "weapon 8"
bind g "rcon disable_weapon_grenadelauncher 0"
bind k "kick allbots"
bind m "exec my_maplist.cfg"
bind q "weapon 5"
bind r "weapon 2"
bind s "+back"
bind t "toggle cg_drawtimer"
bind u "messagemode2"
bind w "+forward"
bind x "weapon 9"
bind y "messagemode2"
bind z "vstr musictoggle"
bind 0x7e "toggleconsole"
bind BACKSPACE "kill"
bind PAUSE "pause"
bind UPARROW "+forward"
bind DOWNARROW "+back"
bind LEFTARROW "+moveleft"
bind RIGHTARROW "+moveright"
bind ALT "+scores"
bind CTRL "+movedown"
bind SHIFT "weapon 6"
bind DEL "weapon 4"
bind PGDN "weapon 7"
bind PGUP "+button3"
bind END "+movedown;+zoom"
bind F1 "vote yes"
bind F2 "vote no"
bind F3 "ui_teamorders"
bind F7 "vstr hudlookstoggle"
bind F9 "currenttime"
bind F11 "screenshot"
bind F12 "screenshotJPEG"
bind KP_HOME "+button2"
bind KP_PGUP "r_gamma 1;disconnect"
bind KP_LEFTARROW "weapon 3"
bind KP_END "weapon 2"
bind KP_DOWNARROW "weapon 1"
bind KP_PGDN "exec gametype_maplist.cfg"
bind KP_INS "weapon 8"
bind KP_DEL "weapon 9"
bind KP_PLUS "callvote nextmap"
bind MOUSE1 "+attack"
bind MOUSE2 "+moveup"
bind MOUSE3 "+zoom"
bind MWHEELDOWN "weapnext"
bind MWHEELUP "weapprev"
seta capturelimit "8"
seta cg_altLightning "3"
seta cg_ambientSounds "0"
seta cg_autoaction "0"
seta cg_autorecordFormat "$(name)_$(gametype)_$(map)_$(rdate)_$(time)"
seta cg_autoswitch "0"
seta cg_bobbing "3"
seta cg_bobpitch "0.002"
seta cg_bobroll "0.002"
seta cg_bobup "0.005"
seta cg_brassTime "0"
seta cg_cameraOrbitDelay "50"
seta cg_corpse "3"
seta cg_country "us"
seta cg_crosshairColor "7"
seta cg_crosshairHealth "0"
seta cg_crosshairHitColors "231"
seta cg_crosshairHitTime "200"
seta cg_crosshairPulse "1"
seta cg_crosshairSize "36"
seta cg_crosshairX "0"
seta cg_crosshairY "0"
seta cg_damageEffect "3"
seta cg_deferplayers "0"
seta cg_draw2D "1"
seta cg_draw3dIcons "1"
seta cg_drawAmmoWarning "1"
seta cg_drawAttacker "1"
seta cg_drawChatId "1"
seta cg_drawCrosshair "8"
seta cg_drawCrosshairNames "1"
seta cg_drawFPS "0"
seta cg_drawFriend "1"
seta cg_drawGun "1"
seta cg_drawIcons "1"
seta cg_drawMouse "0"
seta cg_drawNames "0"
seta cg_drawRewards "1"
seta cg_drawScores "1"
seta cg_drawStatus "1"
seta cg_drawTime "2"
seta cg_drawTimer "1"
seta cg_enemyColors "77777"
seta cg_enemyModel ""
seta cg_explosionSparks "0"
seta cg_followKiller "0"
seta cg_forceModel "0"
seta cg_fov "112"
seta cg_gibs "1"
seta cg_gunAnimations "15"
seta cg_gunOffset ""
seta cg_gunfov "0"
seta cg_hiResIcons "1"
seta cg_hitsound "5"
seta cg_itemFX "7"
seta cg_lightningImpact "1"
seta cg_marks "0"
seta cg_muzzleflash "1"
seta cg_noAmmoChange "1"
seta cg_noBlink "0"
seta cg_noMip "511"
seta cg_noProjectileTrail "1"
seta cg_noShotgunTrail "0"
seta cg_noSnow "0"
seta cg_nochatbeep "0"
seta cg_oldGrenade "0"
seta cg_oldPlasma "1"
seta cg_oldRail "1"
seta cg_oldRocket "0"
seta cg_playerSounds "0"
seta cg_predictItems "1"
seta cg_projectileNudge "0"
seta cg_railTrailRadius "75"
seta cg_railTrailTime "400"
seta cg_runpitch "0.002"
seta cg_runroll "0.005"
seta cg_scorePlums "0"
seta cg_screenshotFormat "$(name)_$(gametype)_$(map)_$(rdate)_$(time)"
seta cg_shadows "1"
seta cg_simpleItems "0"
seta cg_smoke_sg "0"
seta cg_smokegrowth_gl "0"
seta cg_smokegrowth_rl "0"
seta cg_smokepuff "0"
seta cg_smokeradius_gl "0"
seta cg_smokeradius_rl "0"
seta cg_smoothclients "1"
seta cg_teamChatsOnly "0"
seta cg_teamColors ""
seta cg_teamModel ""
seta cg_teamSounds "3"
seta cg_thirdPersonAngle "0"
seta cg_thirdPersonRange "40"
seta cg_truelightning "1.0"
seta cg_unlagged "1"
seta cg_waterEffects "3"
seta cg_weaponPriority ""
seta cg_zoomFov "22.5"
seta cg_zoomTime "150"
seta cl_autoRecordDemo "0"
seta cl_aviFrameRate "25"
seta cl_aviMotionJpeg "1"
seta cl_aviPipeFormat "-preset medium -crf 23 -vcodec libx264 -flags +cgop -pix_fmt yuvj420p -bf 2 -codec:a aac -strict -2 -b:a 160k -movflags faststart"
seta cl_drawRecording "1"
seta cl_maxpackets "125"
seta cl_reconnectArgs "10.0.0.90:27960"
seta cl_timenudge "-30"
seta color "47777"
seta color1 "0999"
seta color2 "4"
seta com_blood "1"
seta com_hunkMegs "700"
seta com_introplayed "1"
seta com_skipIdLogo "1"
seta com_soundMegs "8"
seta com_zoneMegs "12"
seta ed_font "0"
seta ed_hud "QL"
seta fraglimit "30"
seta g_allowvote "1"
seta g_autoJoin "1"
seta g_bans "bans.txt"
seta g_blueteam "^4BLUE TEAM"
seta g_botsFile ""
seta g_chatDelay "1"
seta g_chatProtection "0"
seta g_crontab "crontab.txt"
seta g_friendlyFire "0"
seta g_holyshit "0"
seta g_inactivitySpectator "180"
seta g_log "games.log"
seta g_logSync "0"
seta g_matchmode "1"
seta g_maxGameClients "0"
seta g_maxTeamClients "0"
seta g_motdFile "motd.txt"
seta g_predictPVS "1"
seta g_redteam "^1RED TEAM"
seta g_referee "map_restart,nextmap,map,kick,mute,unmute,forceteam,lock,unlock,speclock,timeout,timein,teamready,timelimit,g_warmup,g_suddendeath,scorelimit,fraglimit,capturelimit,roundlimit"
seta g_rotation "rotation.txt"
seta g_ruleset "quakelive.cfg"
seta g_spAwards "\a4\40176\a2\6778\a1\1153\a3\41\a0\9\a5\1"
seta g_spScores1 "\l0\1"
seta g_spScores2 "\l24\1"
seta g_spScores3 "\l25\1\l23\1\l22\1\l21\1\l20\1\l16\1\l19\1\l18\1\l17\1\l14\1\l13\1\l12\1\l11\1\l10\1"
seta g_spScores4 "\l17\1\l21\1\l22\1\l23\1\l15\1\l10\6\l9\1\l8\1\l7\1\l6\1\l5\1\l4\1\l3\1\l2\1\l1\1"
seta g_spScores5 "\l177\4\l59\3\l126\5\l80\1\l137\2\l168\1\l130\1\l47\1\l205\2\l116\1\l117\1\l58\1\l61\1\l216\4\l189\2\l32\1\l207\2\l208\2\l204\1\l139\2\l85\1\l68\1\l212\2\l155\1\l122\1\l52\1\l185\1\l106\1\l178\5\l179\3\l98\1\l105\1\l133\5\l44\1\l121\1\l45\1\l37\1\l34\1\l49\1\l209\1\l57\1\l56\1\l43\1\l196\1\l4\1\l19\1\l17\1\l24\1\l109\3\l18\1\l182\5\l184\1\l213\5\l113\1\l202\1\l16\1\l200\1\l134\1\l221\2\l71\1\l201\1\l164\8\l144\3\l206\2\l79\1\l76\7\l215\1\l146\1\l73\1\l193\3\l145\2\l55\4\l78\5\l132\1\l88\1\l89\6\l220\4\l5\1\l11\1\l173\3\l192\1\l3\1\l199\1\l67\2\l149\2\l180\1\l198\1\l143\5\l1\1\l114\1\l211\3\l210\2\l170\7\l90\2\l36\1\l166\2\l218\6\l161\3\l86\6\l203\1\l42\1\l131\6\l75\1\l195\2\l63\2\l136\3\l51\7\l154\7\l40\2\l39\1\l84\1\l38\1\l167\2\l188\4\l129\8\l159\4\l50\3\l6\1\l2\1\l8\1\l0\1\l48\3\l115\3\l9\1\l110\4\l156\4\l21\1\l10\1\l14\1\l15\1\l13\1\l12\1\l22\1\l124\1\l23\1\l7\1\l123\3\l162\2\l33\1\l30\1\l20\1\l25\1\l94\2\l31\1\l35\1\l95\3\l197\1"
seta g_spSkill "5"
seta g_spVideos "\tier8\1\tier7\1\tier6\1\tier5\1\tier4\1\tier3\1\tier2\1\tier1\1"
seta g_specLock "0"
seta g_suddenDeath "1"
seta g_teamBalance "1"
seta g_teamForceBalance "0"
seta g_unlagged "1"
seta g_validTLD "0"
seta g_voteStrings "map_restart,nextmap,map,g_gametype,kick,g_warmup,timelimit,fraglimit,capturelimit,roundlimit,unlagged"
seta g_voteconf "voteconf.txt"
seta g_warmup "60"
seta headmodel "crash/trainer"
seta in_minimize "rshift+3"
seta in_mouse "1"
seta model "crash/trainer"
seta name "^1-"
seta r_customheight "1080"
seta r_customwidth "1920"
seta r_dlightMode "1"
seta r_dynamiclight "1"
seta r_fbo "1"
seta r_fullscreen "1"
seta r_mode "-1"
seta r_modeFullscreen "-2"
seta r_neatsky "0"
seta r_nomip "0"
seta r_picmip "0"
seta r_railCoreWidth "2"
seta r_railSegmentLength "2"
seta r_railWidth "1"
seta r_renderHeight "1200"
seta r_renderWidth "1920"
seta r_textureMode "GL_LINEAR_MIPMAP_NEAREST"
seta r_vertexLight "0"
seta rate "25000"
seta refereePassword ""
seta roundlimit ""
seta s_musicvolume "0"
seta s_muteWhenMinimized "1"
seta s_muteWhenUnfocused "1"
seta s_volume "1"
seta sensitivity "1.3"
seta server1 ""
seta server10 ""
seta server11 ""
seta server12 ""
seta server13 ""
seta server14 ""
seta server15 ""
seta server16 ""
seta server2 ""
seta server3 ""
seta server4 ""
seta server5 ""
seta server6 ""
seta server7 ""
seta server8 ""
seta server9 ""
seta sex "it"
seta snaps "40"
seta sv_allowDownload "1"
seta sv_dlRate "100"
seta sv_dlURL ""
seta sv_filter "filter.txt"
seta sv_floodProtect ""
seta sv_fps "20"
seta sv_hostname ""
seta sv_maxRate ""
seta sv_maxclients "8"
seta sv_maxclientsPerIP "3"
seta sv_minRate ""
seta sv_pure "1"
seta sv_strictAuth "1"
seta sv_timeout "200"
seta timelimit "10"
seta ui_browserGameType "0"
seta ui_browserMaster "0"
seta ui_browserShowEmpty "1"
seta ui_browserShowFull "1"
seta ui_browserSortKey "4"
seta ui_ctf_capturelimit "8"
seta ui_ctf_friendly "0"
seta ui_ctf_timelimit "30"
seta ui_ffa_fraglimit "20"
seta ui_ffa_timelimit "0"
seta ui_team_fraglimit "0"
seta ui_team_friendly "1"
seta ui_team_timelimit "20"
seta ui_tourney_fraglimit "0"
seta ui_tourney_timelimit "15"
seta vid_xpos "3"
seta vid_ypos "22"
seta vm_cgame "2"
seta vm_game "2"
seta vm_ui "2"

**Comment by v1l3dq** [comment]
I've always had r_ignorehwgamma "0"

**Comment by ec-** [comment]
I see, you already have r_fbo set, then something (autoexec.cfg?) might just resetting it?

**Comment by v1l3dq** [comment]
I didn't have r_fbo enabled prior your recommending it, and now that I have it enabled, the r_gamma cvar is working!
