### ISSUE TITLE
How do you build this thing?

### ISSUE THREAD

**Issue by pmiddend** [ec-/Quake3e#28]
I've tried `cmake .` but it just tells me:

```
CMake Error at code/renderer/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    tr_font.c
```

which is true, the file isn't there. Am I missing something?

**Comment by ensiform** [comment]
Use the makefile or msvc project for time being. Cmake is experimental and not always updated

**Comment by ec-** [comment]
This is not my own scripts, some guy provided them, so they are barely supported

**Comment by pmiddend** [comment]
Ah, that seems to work, thanks! Maybe you can add a small README file just telling people how to build/start it?

**Comment by pmiddend** [comment]
Or possibly remove the CMake files, since they don't work.
