### ISSUE TITLE
rj doesn't work anymore

### ISSUE THREAD

**Issue by rhazor** [ec-/Quake3e#280]
On latest windows x64 builds my rj script doesn't work as it should and I don't know why, simply replacing old .exe solves the issue.

The script:
```
seta rocketjump ""
rocketjump "centerview; cl_pitchspeed 9999000; +lookdown; +attack; +moveup; wait 2; -lookdown; -attack; -moveup; wait 2; centerview; cl_pitchspeed 140"
bind MOUSE4 "vstr rocketjump"
```

The issue: When triggering the rj script it does go off but mouse switches/locks up to the sky 90 degree y axis, very annoying.

And like I said if I just replace with older quake3e.exe (from last ~september) issue is solved? No idea what causes this.

**Comment by ec-** [comment]
For now use just `wait` and remove second `wait 2` invocation

**Comment by mataski** [comment]
That fixed. Thanks.

**Comment by rhazor** [comment]
That fixed. Thanks.
