### ISSUE TITLE
[Enhancement] Add CVAR to change WINDOW TITLE

### ISSUE THREAD

**Issue by xplshn** [ec-/Quake3e#289]
The flatpak for OpenARENA which I maintain uses Quake3e, the title is always set incorrectly and con_title did not help: https://github.com/flathub/io.github.ec_.Quake3e.OpenArena/issues/115#issuecomment-2161589134

**Comment by KG7x** [comment]
con_title already exist

**Comment by ensiform** [comment]
Did you add it like `+set con_title "Blah blah here"` to launch parameters?

**Comment by KG7x** [comment]
ah cl_title i think can help
