### ISSUE TITLE
Brightness resets itself after a few seconds

### ISSUE THREAD

**Issue by pmiddend** [ec-/Quake3e#29]
I'm playing on Linux. I have `r_gamma` set to 1.55, but after a few seconds (in the menu and in-game), the screen gets really dark. Resetting the gamma variable brightens it again for a few seconds.
Edit: seems `r_ignorehwgamma` sort of fixes this for me, but it's still a little too dark then.

**Comment by pmiddend** [comment]
Sorry for the disturbance. This is caused by the redshift (http://jonls.dk/redshift/) daemon running in the background.

**Comment by ensiform** [comment]
Consider using r_fbo 1 to use GPU shader gamma instead.
