### ISSUE TITLE
Right alt key sticks down in windows input

### ISSUE THREAD

**Issue by ensiform** [ec-/Quake3e#3]
I believe this is happening since https://github.com/ec-/Quake3e/commit/caf6b5dc383fa5bb0af64f7408687a2ae77a99fc

Press the right alt key, wait a few seconds then press enter like say, to commit your text in the console and it will cause fullscreen toggle.

US layout

**Comment by ec-** [comment]
Fixed in https://github.com/ec-/Quake3e/commit/66dedde09495448760e94231dbb1a3d709334854
