### ISSUE TITLE
Quake3e requires jack (audioserver) running? Is that intentional?

### ISSUE THREAD

**Issue by joemaro** [ec-/Quake3e#34]
Using Manjaro Linux (based on arch) 64 bit and i can only run `./quake3e` when i run a jackserver (for example with `qjackctl`) first. Seems odd and i'd like to know whether this is intentional.

Thanks for the info!

The output when i run `./quake3e.x64`:

```
21:37 ~/Games/quake3❱ ./quake3e.x64 
Q3 1.32e linux-x86_64 Nov 29 2019
----- FS_Startup -----
...loaded in 65 milliseconds
----------------------
21860 files in 180 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found 64-bit GenuineIntel w/ SSE4.1
----- Client Initialization -----
----- Initializing Renderer ----
-------------------------------
----- Client Initialization Complete -----
----- R_Init -----
...initializing QGL
...loading 'libGL.so.1' : succeeded
...RandR extension version 1.6 detected.
...current monitor: 1440x900@0,0 VGA1

...DGA extension version 2.0 detected.
Initializing display
...setting mode -1: 1440 900
...using desktop display mode
ATTENTION: default value of option vblank_mode overridden by environment.
ATTENTION: option value of option vblank_mode ignored.
Using 8/8/8 Color bits, 24 depth, 8 stencil display.
...using GLX_EXT_swap_control
Initializing OpenGL extensions
...ignoring GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_env_add
...using GL_ARB_multitexture
...using GL_EXT_compiled_vertex_array
...ignoring GL_EXT_texture_filter_anisotropic
...using ARB vertex/fragment programs
...using ARB vertex buffer objects
...using xrandr gamma extension

GL_VENDOR: Intel Open Source Technology Center
GL_RENDERER: Mesa DRI Intel(R) Haswell Mobile 
GL_VERSION: 3.0 Mesa 19.2.4

GL_MAX_TEXTURE_SIZE: 16384
GL_MAX_TEXTURE_UNITS_ARB: 8

PIXELFORMAT: color(24-bits) Z(24-bit) stencil(8-bits)
MODE: -2, 1440 x 900 fullscreen hz:N/A
multitexture: enabled
compiled vertex arrays: enabled
texenv add: enabled
compressed textures: disabled
GAMMA: hardware w/ 0 overbright bits
rendering primitives: single glDrawElements
texturemode: GL_LINEAR_MIPMAP_NEAREST
texture bits: 32
picmip: 0
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound ------
...trying MMAP mode
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Playback device open error: No such file or directory
Received signal 11, exiting...
----- Client Shutdown (Signal caught (11)) -----
RE_Shutdown( 2 )
...shutting down QGL
...unloading OpenGL DLL
-----------------------
```

**Comment by ec-** [comment]
Engine tries to open "default" **ALSA** device, there is no such hardcoded **jack** dependencies, so this looks like as your local configuration issue.

You may try to set **USE_SDL = 1** in Makefile and recompile engine

**Comment by joemaro** [comment]
i forgot to mention that the binary i used was the one latest github release (20191119). When i run the `./ioquake` in the same folder, same configs, some mods etc... everything works fine. i don't understand it... yet :) thanks for the info, i'll report back when i make progress.

**Comment by joemaro** [comment]
i forgot to mention that the binary i used was the one latest github release (20191119). When i run the `./ioquake` in the same folder, same configs, some mods etc... everything works fine. i don't understand it... yet :) thanks for the info, i'll report back when i make progress.

**Comment by joemaro** [comment]
when i compile the latest source code without any modifications, quake3e needs jack to be running in order to work. Probably influenced by some local circumstances, but my system is in no way special, it's a pretty standard manjaro linux i'd say.

**Comment by joemaro** [comment]
Even when i set **USE_SDL = 1** in the makefile, the result is the same: jack server needs to be running.

**Comment by ensiform** [comment]
Comparison to ioquake3 not valid entirely. ioquake3 uses OpenAL by default. But no matter what backend code in q3e seems to still choose that specific alsa device

**Comment by ec-** [comment]
SDL may still want to open the same default ALSA device, I see no engine-specific dependencies there

**Comment by joemaro** [comment]
`seta s_device "pulse"` in `baseq3/q3config.cfg` did the job. `default` and `sysdefault` needed jack running.

Thanks for the help!

**Comment by ensiform** [comment]
Team arena is the missionpack folder so not baseq3 folder.
