### ISSUE TITLE
cl_autonudge does not work well

### ISSUE THREAD

**Issue by yojan95** [ec-/Quake3e#37]
should improve the client code by merging part of this code
[https://github.com/ry4096/znudge](url)
 

ec say> Well, pretty much every improvement that increases FPS (for example) might be considered as unfair too so I don't see any problems here, it is a nice feature
[https://github.com/ec-/Quake3e/issues/10](url)

many of us are from other countries and playing with high ping is annoying,
you are still working on your engine and that is very interesting so you should improve the experience of us players with high ping

**Comment by ec-** [comment]
znudge is a mod, can't be merged into engine, modern mods already have unlagged/xerp functionality to compensate ping difference, cl_autonudge is a solution (with questionable efficiency but better than nothing) for abandoned mods like OSP

**Comment by yojan95** [comment]
ok understand, I also want to know about the pk8a.pk3. about source code, It has osp-like characteristics

**Comment by ensiform** [comment]
Pak8a is https://github.com/ec-/baseq3a
