### ISSUE TITLE
Vulkan: Game freezes after loading many bots.

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#38]
If loading many bots into any map, the game freezes.
This only happens when the engine is compiled with USE_VULKAN = 1.
When compiling the current code with USE_VULKAN = 0 (the default) the crash doesn't happen, hence my suspicion that Vulkan causes the bug.
Best way to reproduce the crash, is by compiling the engine with  USE_VULKAN = 1.
Than load any map you want, add more and more bots until the game will freeze. Eventually you will get a somehow 'chopped up' screen.
WARNING: you can't quit Q3a regulary.

Currently I'm not sure if the amount of bots is of some importance.

Specifications:
Win 8.1 (64-bit)
NV GT1060
Compiled from latest source, unmodified, with Cygwin.

**Comment by ec-** [comment]
Check now

**Comment by KuehnhammerTobias** [comment]
Yeah, it seems you fixed this issue. The good thing is I currently work on the bots AI, loading 64 bots all the time is very likely, so I can easily check if the crash will happen still.
Though, I can't reproduce the crash again! Well done!
