### ISSUE TITLE
Disconnected bots on respawn?

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#39]
Currently I'm not sure if this is an engine or a baseq3a issue:
Sometimes bots have their 'Disconnection' sprite (icon) appearing over their head (instead of their talk balloon?).
It's not clear to me if they are really disconnected for a milisecond, or if this is just a graphical glitch of Q3e/baseq3a.
I  thought it would be the best to mention this issue here.
The issue is easy to reproduce: Start any map where you can spectate lot of spawnpoints at once, add lots of bots and watch them spawn.
Here are some screenshots:
![shot-20200130-002950-3](https://user-images.githubusercontent.com/5429387/73441649-9935ae00-4353-11ea-8216-b2757387c534.jpg)

**Comment by ec-** [comment]
This is a mod issue (just visual) related to unlagged code, fixed
