### ISSUE TITLE
Renderers: Both renderers miss 'videoMap'.

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#40]
Part of PointRelease 1.27 (or was it 1.29) was the ability to play videos ingame from map. This was part of the Team Arena maps. There are a few custom maps as well, iirc.
Bothe Q3a renderers (GL1 and Vulkan) seems to have trouble to play those videos.
As far as the GL renderer is concerned it seems the 'videoMap' and the 'lighmap' is somehow mixing up, or interfere with each other.
Here is a screenshot of what happens to GL1 renderer if you enter an area where a 'videoMap' shader should be seen:
![shot-20200130-194841](https://user-images.githubusercontent.com/5429387/73503301-392f1e00-43cc-11ea-83e7-81dd80b9a23c.jpg)
...and here is how 'videoMaps' look in Vulkan:
![shot-20200131-013526](https://user-images.githubusercontent.com/5429387/73503341-4ba95780-43cc-11ea-8632-907afd960049.jpg)
The best way to reproduce this is by loading maps from Team Arena (for example mpteam3 or mpteam5) or any custom map that ships with an ingame video.

**Comment by ec-** [comment]
Yes, it was accidentally broken by unneeded `GL_BindTexture( 0 );` calls
