### ISSUE TITLE
Drop Back to UI vm when trying to load map "zeel-exzeel_slick"

### ISSUE THREAD

**Issue by reangames** [ec-/Quake3e#42]
this is the condump:

iDFe RC+1591 win_mingw-x86_64 Jan 19 2020
----- FS_Startup -----
...found 80 cached paks
...loaded in 23 milliseconds
----------------------
9089 files in 82 pk3 files
execing default.cfg
execing q3config.cfg
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found 64-bit GenuineIntel w/ SSE4.1
----- Client Initialization -----
12:43:56 ----- Initializing Renderer ----
12:43:56 -------------------------------
12:43:56 ----- Client Initialization Complete -----
12:43:56 ----- R_Init -----
12:43:56 Initializing Vulkan subsystem
12:43:56 ...initializing QVK
12:43:56 ...loading 'C:\WINDOWS\SYSTEM32\vulkan-1.dll' : succeeded
12:43:56 ...current monitor: 1920x1080@0,0 \\.\DISPLAY1
12:43:56 ...setting mode -2: 1920 1080 FS
12:43:56 ...using desktop display depth of 32
12:43:56 ...calling CDS: ok
12:43:56 ...registered window class
12:43:56 Raw mouse input initialized.
12:43:56 ...created window@0,0 (1920x1080)
12:43:57 ...selected physical device #0
12:43:57 ...presentation modes: FIFO FIFO_RELAXED MAILBOX
12:43:57 ...selected presentation mode: MAILBOX, image count: 2
12:43:57
VK_VENDOR: NVIDIA
12:43:57 VK_RENDERER: Discrete GeForce GTX 1050 Ti, 0x1c8c
12:43:57 VK_VERSION: API: 1.0.65, Driver: 391.48.0.0
12:43:57
VK_MAX_TEXTURE_SIZE: 2048
12:43:57 VK_MAX_TEXTURE_UNITS: 8
12:43:57
PIXELFORMAT: color(32-bits) Z(24-bit) stencil(8-bits)
12:43:57  presentation: VK_FORMAT_B8G8R8A8_UNORM
12:43:57  depth: VK_FORMAT_D24_UNORM_S8_UINT
12:43:57 MODE: -2, 1920 x 1080 fullscreen hz:120
12:43:57 GAMMA: hardware w/ 0 overbright bits
12:43:57 texturemode: GL_LINEAR_MIPMAP_NEAREST
12:43:57 texture bits: 32
12:43:57 picmip: 0
12:43:57 Initializing Shaders
12:43:57 ----- finished R_Init -----
12:43:57 ------ Initializing Sound ------
12:43:57 ----- Sound Info -----
12:43:57     2 channels
12:43:57 16384 samples
12:43:57    32 samplebits (float)
12:43:57     1 submission_chunk
12:43:57 22050 speed
12:43:57 00000000014E9F00 dma buffer
12:43:57 Using WASAPI subsystem
12:43:57 No background file.
12:43:57 ----------------------
12:43:57 Sound initialization successful.
12:43:57 --------------------------------
12:43:57 Sound memory manager started
12:43:57 Loading vm file vm/ui.qvm...
12:43:57 VM file ui compiled to 696142 bytes of code
12:43:57 ui loaded in 2098176 bytes on the hunk
12:43:57 52 arenas parsed
12:43:57 32 bots parsed
12:43:57 --- Common Initialization Complete ---
12:43:57 Winsock Initialized
12:43:57 Hostname: DESKTOP-VSR4E9C
12:43:57 IP6: fe80::f559:a247:66ea:eb7d%42
12:43:57 IP6: fe80::ec41:8e11:96da:c435%4
12:43:57 IP6: 2003:c9:871f:1600:bd78:d376:26d3:c7ed
12:43:57 IP6: 2003:c9:871f:1600:ec41:8e11:96da:c435
12:43:57 IP: 192.168.178.28
12:43:57 IP: 192.168.56.1
12:43:57 Opening IP6 socket: [::]:27960
12:43:57 Opening IP socket: 0.0.0.0:27960
12:43:57 Working directory: C:\Users\screen13\Desktop\df
12:43:57 83.243.73.220:27960 resolved to 83.243.73.220:27960
12:43:57 Resolving authorize.quake3arena.com
12:43:57 authorize.quake3arena.com resolved to 192.246.40.56:27952
12:43:57 WARNING: server is not allowed to set df_mp_interferenceOff=3
12:43:57 ----- FS_Startup -----
12:43:57 ...loaded in 3 milliseconds
12:43:57 ----------------------
12:43:57 9089 files in 82 pk3 files
12:43:57 URL: http://ws.q3df.org/maps/download/zeel-exzeel_slick
12:44:12 ----- FS_Startup -----
12:44:12 ...loaded in 4 milliseconds
12:44:12 ----------------------
12:44:12 9104 files in 83 pk3 files
12:44:12 defrag\zeel-exzeel_slick.pk3 downloaded
12:44:12 WARNING: server is not allowed to set df_mp_interferenceOff=3
12:44:12 RE_Shutdown( 0 )
12:44:12 Hunk_Clear: reset the hunk ok
12:44:12 ----- R_Init -----
12:44:12 GAMMA: hardware w/ 0 overbright bits
12:44:12 texturemode: GL_LINEAR_MIPMAP_NEAREST
12:44:12 texture bits: 32
12:44:12 picmip: 0
12:44:12 Initializing Shaders
12:44:12 ----- finished R_Init -----
12:44:12 Loading vm file vm/ui.qvm...
12:44:12 VM file ui compiled to 696142 bytes of code
12:44:12 ui loaded in 2098176 bytes on the hunk
12:44:12 52 arenas parsed
12:44:12 32 bots parsed
12:44:12 Loading vm file vm/cgame.qvm...
12:44:13 VM file cgame compiled to 1243646 bytes of code
12:44:13 cgame loaded in 8389632 bytes on the hunk
12:44:13 Cvar: df_promode 1
12:44:13 Cvar: dmflags 0
12:44:13 Cvar: sv_cheats 0
12:44:13 Cvar: timescale 1.00
12:44:13 Cvar: g_synchronousClients 0
12:44:13 Cvar: pmove_fixed 1
12:44:13 Cvar: pmove_msec 8
12:44:13 Cvar: g_speed 320
12:44:13 Cvar: g_gravity 800
12:44:13 Cvar: g_knockback 1000
12:44:13 stitched 0 LoD cracks
12:44:13 ...loaded 1243 faces, 0 meshes, 2 trisurfs, 0 flares
12:44:13 ...found 1222 VBO surfaces (6333 vertexes, 11691 indexes)
12:44:14 CL_InitCGame:  1.65 seconds
12:44:14 Com_TouchMemory: 0 msec
12:44:14 sL1kJR entered the game.
12:44:14 ********************
**ERROR: SHADER_MAX_VERTEXES hit in FillCloudySkySide()**
********************
12:44:14 RE_Shutdown( 0 )
12:44:14 Hunk_Clear: reset the hunk ok
12:44:14 ----- R_Init -----
12:44:14 GAMMA: hardware w/ 0 overbright bits
12:44:14 texturemode: GL_LINEAR_MIPMAP_NEAREST
12:44:14 texture bits: 32
12:44:14 picmip: 0
12:44:14 Initializing Shaders
12:44:14 ----- finished R_Init -----
12:44:14 Loading vm file vm/ui.qvm...
12:44:14 VM file ui compiled to 696142 bytes of code
12:44:14 ui loaded in 2098176 bytes on the hunk
12:44:14 52 arenas parsed
12:44:14 32 bots parsed
12:44:14 Not recording a demo.
12:44:45 ]\condump error
12:44:45 Dumped console text to error.txt.

**Comment by ensiform** [comment]
Does map load with vanilla renderer, or original quake3 binary or ioquake3?

**Comment by ec-** [comment]
Skybox clipping works slightly different (generates more vertices), not sure why, but reducing SKY_SUBDIVISIONS helps for now

**Comment by reangames** [comment]
I remeber that some earlier time I was playing the map with the default renderer without problems. Someone played the map on a server and I wanted to join. So.. seems like could be a vulkan renderer Issue :)

**Comment by ec-** [comment]
Both renderers affected: "bug" comes from https://github.com/ec-/Quake3e/commit/2aa52847162c01e68753eee84dca8247eed4dd5d
Before that each sky side were rendered as a separate shader (resetting geometry at the end), now they are collapsed into single one which could cause geometry overflow
