### ISSUE TITLE
Reported ping in score stats view

### ISSUE THREAD

**Issue by horiac7** [ec-/Quake3e#43]
Hello! 

Not quite an issue to report, but was curious about the following stats reporting during a Skirmish bot match played locally: 

Whenever using RTSS i.e. Riva Tuner Statistics Server (with MSI Afterburner) to cap the framerate of Quake3e (either OGL or Vulkan), the reported ping for my character is 8ms (if capping at 120) or 16ms (if capping at 60) - so equivalent to the cost of a frame at said frame cap.

If not using any external framerate limiter then the Ping value is 0. 

- Why does external frame capping cause this issue?
- Does it affect input lag or is it correlated with this in any way?

**Comment by ec-** [comment]
I guess that external frame capping tools adding explicit delay at swapchain which may cause input lags, in other case engine have more time to process and respond to the user commands

**Comment by horiac7** [comment]
I forgot to mention but running with the original `quake3.exe` and the same frame capping method - RTSS - then the Ping value is 0. 
Is there something changed in the way this value is calculated? Or anything related to it?

**Comment by ec-** [comment]
Ping calculation now is more precise, so if you have delay somewhere - it will be displayed
