### ISSUE TITLE
Vulkan renderer fails to start on Linux

### ISSUE THREAD

**Issue by Calinou** [ec-/Quake3e#44]
**OS:** Fedora 31
**Graphics card:** GeForce GTX 1080, NVIDIA proprietary driver 440.64
**Quake3e version:** Git https://github.com/ec-/Quake3e/commit/b5ab0675856aaf00fb465db46a8caa486693f967

When compiling Quake3e using `make USE_VULKAN=1`, I get the following error when starting it:

```text
Q3 1.32e linux-x86_64 Mar 13 2020
----- FS_Startup -----
...found 15 cached paks
...loaded in 1 milliseconds
----------------------
6313 files in 15 pk3 files
execing default.cfg
execing q3config.cfg
com_zoneMegs will be changed upon restarting.
couldn't exec autoexec.cfg
Hunk_Clear: reset the hunk ok
...detecting CPU, found 64-bit GenuineIntel w/ SSE4.1
----- Client Initialization -----
----- Initializing Renderer ----
-------------------------------
----- Client Initialization Complete -----
----- R_Init -----
...initializing QVK
...loading 'libvulkan.so' : failed
...shutting down QVK
----- Client Shutdown (Server fatal crashed: GLW_StartVulkan() - could not load Vulkan subsystem
) -----
RE_Shutdown( 2 )
...shutting down QVK
-----------------------
Sys_Error: GLW_StartVulkan() - could not load Vulkan subsystem
```

Other Vulkan applications and games (such as GZDoom) work fine on this machine. Quake3e's OpenGL renderer also works.

**Comment by ec-** [comment]
It fails to load `libvulkan.so`, probably it has different name, try to inspect your `/usr/lib` directory for corresponding library and create symlink to it

**Comment by ec-** [comment]
Feel free to reopen if this still happens
