### ISSUE TITLE
Compatible with Arch Linux?

### ISSUE THREAD

**Issue by ghost** [ec-/Quake3e#50]
Figure I'd check here but is this compatible with Arch Linux in particular? Looking to install Quake3e and having a tough time getting started.

**Comment by ec-** [comment]
Precompiled binaries should work fine.

Otherwise in order to compile it you may need to install *distribution-dependent* packages which contains required header files for cURL, X11, SDL2, some distributions like Slackware do not require to install anything.

There is a lot of distributions and package managers so I can't tell what you need exactly in Arch Linux, you may find it faster than me

**Comment by WandeingLagomorph793** [comment]
> Precompiled binaries should work fine.
> 
> Otherwise in order to compile it you may need to install _distribution-dependent_ packages which contains required header files for cURL, X11, SDL2, some distributions like Slackware do not require to install anything.
> 
> There is a lot of distributions and package managers so I can't tell what you need exactly in Arch Linux, you may find it faster than me

Is it one of the other non executable files? I reckon those are the other precompiled ones for Linux in particular. Opening doesn't bring up much, unless I need some extra dependencies.

**Comment by mxmilkiib** [comment]
I'm on Arch, just cloned, built and run it, had all the deps already apart from `libxxf86dga` package.

**Comment by ec-** [comment]
@mxmilkiib try to compile with **USE_SDL=1** flag

**Comment by zoidby** [comment]
I am working on an aur package for archlinux. I think i am pretty much done except for an icon. Is there one yet?

**Comment by ec-** [comment]
There is a standard win32 ico file, you may try to convert it to format you need

**Comment by zoidby** [comment]
Are you talking about the original one from id Software? Because i am not sure if i can use that. They GPL’d the engine, but not the artwork right? The people from ioquake made their own afaik.

**Comment by ensiform** [comment]
If the icon is included in the GPL release the icon should be too I'm

**Comment by zoidby** [comment]
Right! I checked it out but it’s only 32px and looks dated.

But there was a background.bmp, which i used to create this:
![q3e](https://user-images.githubusercontent.com/44140842/91974854-c0f05880-ed1e-11ea-88a9-25a164fa46fb.png)

In use, it looks like this: 
![screenshot--2020-09-02--13-19-30](https://user-images.githubusercontent.com/44140842/91974975-f432e780-ed1e-11ea-9980-b67e709cb16a.png)

I could use this for the arch package until someone creates a better one. I am not a graphic designer. What do you think?

**Comment by zoidby** [comment]
I finally had the time to publish this package. Here it is:

https://aur.archlinux.org/packages/quake3e/

I am not committed to keeping this exact icon or other information provided by the package. If someone has an improvement, let me know.

**Comment by adojck** [comment]
Hello,
When I try to run 2021-01-16 release from GitHub (https://github.com/ec-/Quake3e/releases/download/2021-01-16/quake3e-linux-x86_64.zip) on my Arch Linux machine, it fails at start like this:

```
[...]
Initializing Shaders
----- finished R_Init -----
------ Initializing Sound ------
...trying MMAP mode
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
Playback device open error: No such file or directory
Received signal 11, exiting...
----- Client Shutdown (Signal caught (11)) -----
RE_Shutdown( 2 )
...shutting down QGL
...unloading OpenGL DLL
-----------------------
```
It seems that my system is missing some sound related package. Maybe someone knows which one?

When I use AUR package by zoidby, it works properly (quake3e-git)

**Comment by zoidby** [comment]
Hey @ec-, could you add this to README.md?

```
### Arch Linux

The package `quake3e-git` can either be installed through your favourite AUR helper, or manually using these commands:

Download the snapshot from AUR:

`curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/quake3e-git.tar.gz`

Extract the snapshot:

`tar xfz quake3e-git.tar.gz`

Enter the extracted directory:

`cd quake3e-git`

Build and install `quake3e-git`:

`makepkg -risc`
```

Also if you add this, i think this issue could be closed.

**Comment by ec-** [comment]
Implemented in https://github.com/ec-/Quake3e/commit/f69865508ef4f3d63bcc82c8505d661a1c290f92
