### ISSUE TITLE
Consider outsourcing dependencies

### ISSUE THREAD

**Issue by grepwood** [ec-/Quake3e#54]
Last I remember, ioQuake3 has been keeping local copies of the following libraries in binary format:
- libjpeg
- libSDL2
- libcurl
- probably more but I can't think of any more examples

The purpose, I guess, was to enable building of ioQuake3 for Windows without tasking the SCM with pulling these libraries from their respective sources in source or binary form. I think that is fundamentally wrong to do because this puts the project into a position where it uses outdated, possibly vulnerable versions of these dependencies.

I can propose such solutions:
1. These dependencies are included as git submodules.
2. Solutions for MSVC are reworked to rely on NuGet to pull these dependencies.

**Comment by ensiform** [comment]
You're better off using vcpkg instead of nuget

**Comment by grepwood** [comment]
@ensiform why? Does it come with MSVC? Can MSVC be made to use vcpkg to provide dependencies? If so, that's great. I tried doing the manual labor of what I suggest with NuGet and it was possible.

**Comment by ensiform** [comment]
it's just a matter of pulling the repo, execute the bootstrap script and then vcpkg install sdl2

**Comment by ec-** [comment]
MSVC is not the only build system on windows.

Also, it is better to have all possible dependencies:
- for stable and newbie-friendly build process
- to minimize end-user actions in case of missing/incompatible libraries - which is a common case for windows systems

**Comment by grepwood** [comment]
@ec- that's exactly why things like NuGet and vcpkg exist.

**Comment by ensiform** [comment]
As a side note I'm currently working on a basic cmake script for ETe Linux which is based on Q3e and merged with Enemy Territory. (@etfdevs/ETe)

Eventually it could be brought back to Q3e with relevant changes

**Comment by grepwood** [comment]
There's already some work started in https://github.com/ec-/Quake3e/pull/56 but this is for Linux, not MSVC.
