### ISSUE TITLE
Release versions

### ISSUE THREAD

**Issue by grepwood** [ec-/Quake3e#57]
Are they going to stay the same for the foreseeable future? I'm about to package this engine for Gentoo in src_prepare-overlay :)

**Comment by ensiform** [comment]
He updates pretty regularly depending on how often new changes seem worthy of a release

**Comment by grepwood** [comment]
@ensiform well, yeah, I'm just asking if the releases are going to remain called ${year}-${month}-${day}. Knowing this makes it easier.

**Comment by ec-** [comment]
${year}-${month}-${day} is a good scheme, I will keep it for a future
