### ISSUE TITLE
Feature request: Demo recording renaming fail safe

### ISSUE THREAD

**Issue by daffymahman** [ec-/Quake3e#6]
Some times I accidentaly overwrite demos when using the /record command, it also happens with the auto record functinoality in CPMA when there's no date in the name of the demo.

It would be very helpful if Quake3e had a built in function that added a number sequence at the end of the name for each demo so that you never accidentally overwrite demos.

**Comment by ec-** [comment]
Old demo (**auto**)naming scheme is just a legacy, sure it will be changed to YYYY-MM-DD_HH_mm_SS[-NN] just like for screenshots.
But no changes to manually specified demo will be made
