### ISSUE TITLE
Fix cross compiling the win version on linux using mingw

### ISSUE THREAD

**Issue by uzum4ki** [ec-/Quake3e#62]
When building the windows version on Linux (precisely, Debian) using MingW, there is a need to change the case of "#include <VersionHelpers.h>" in "code/win32/win_snd.c" to "#include <versionhelpers.h>".

**Comment by ensiform** [comment]
This include can be replaced with this function

https://github.com/etfdevs/ETe/blob/master/src/win32/win_snd.c#51
