### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by ucodelukas** [ec-/Quake3e#65]
Hello, I would like to make a website for you, 
We can host it on our server and stuff.

I want to support this project in any way because it's technically and practically better than ioQuake3 now.

Write your ideas here!

**Comment by ec-** [comment]
Hi, that would be nice, I'm already added **Contacts** section to README.md, it is better to continue conversation there

**Comment by ucodelukas** [comment]
made updates again

**Comment by KuehnhammerTobias** [comment]
@ucodelukas Any progress on this? It would be cool to have an alternative to Discord shit.

**Comment by sniffingsugar** [comment]
> @ucodelukas Any progress on this? It would be cool to have an alternative to Discord shit.

Hi, i am the Host of the Cluster you can contact me on XMPP or via Mail to discuss the website, I still want to support the Project :)
XMPP/Mail: phil@ucode.space

**Comment by ensiform** [comment]
> @ucodelukas Any progress on this? It would be cool to have an alternative to Discord shit.

Why is discord so bad to you ._. Being elitist over technology only spreads projects and people thin on already small teams.

**Comment by jp0531812** [comment]
@ensiform Discord is really bad from the privacy perspective => if you dont want to sell your data, use anything else.
Look at the Facebook data leak, anything should be at least particular open source and yes I now that will never be happen, but can we make this world eventually a bit better? Also a Discord bridge seems quite good for an mirror. On that way you can have the discord people and it might hook some people to change their mind, if they see for an exmaple XMPP or Matrix.

**Comment by briancullinan** [comment]
> @ucodelukas Any progress on this? It would be cool to have an alternative to Discord shit.

We miss you ToKu. We promise we've kept all the secrets.
