### ISSUE TITLE
Cannot connect to even a local dedicated server, I thought I am not doing enough udp to tcp to ssh tcp tunnelling to udp magic with my vps, but it just doesn't work at all.

### ISSUE THREAD

**Issue by kubast2** [ec-/Quake3e#66]
Scanning for servers on the local network...
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
Sys_SendPacket: Cannot assign requested address
127.0.0.1:27960 resolved to 127.0.0.1:27960

**Comment by ensiform** [comment]
This error is produced by the socket level of the platform so it is not exclusively an issue with Quake3e.

**Comment by kubast2** [comment]
> This error is produced by the socket level of the platform so it is not exclusively an issue with Quake3e.

You are absolutely correct, I have used someone else-s config and then realized I can actually run quake3e without having one created right away.
