### ISSUE TITLE
Textsture bug in cpmctf1

### ISSUE THREAD

**Issue by em92** [ec-/Quake3e#68]
Hi!
Compiled from 3887c5da75a2103dca2e47a34a9f5f6741cd5f04
Game: cpma
Map: cpmctf1

Playing with bots on gametype NTF.
[texture_bug.tar.gz](https://github.com/ec-/Quake3e/files/5361250/texture_bug.tar.gz)

**Comment by ensiform** [comment]
Well it can't be that commit specifically since it's not related to rendering. Have you tried a more recent one?

**Comment by ec-** [comment]
Check against most recent build, and record in-game demo if possible

**Comment by em92** [comment]
Checked against bd88c4f25e31abd01a54d869cebd7d1029aa39ab
Here is makefile diff, I used.
```diff
diff --git a/Makefile b/Makefile
index 0741009..eca612d 100644
--- a/Makefile
+++ b/Makefile
@@ -19,9 +19,9 @@ ifeq ($(COMPILE_PLATFORM),mingw32)
 endif
 
 BUILD_CLIENT     = 1
-BUILD_SERVER     = 1
+BUILD_SERVER     = 0
 
-USE_SDL          = 0
+USE_SDL          = 1
 USE_CURL         = 1
 USE_LOCAL_HEADERS= 0
 USE_VULKAN       = 0
```

Demo and new video attached
[texture_bug2.tar.gz](https://github.com/ec-/Quake3e/files/5383802/texture_bug2.tar.gz)

**Comment by ec-** [comment]
I'm still not able to reproduce it, make sure you're clean build directory before compilation, if it doesn't help - send me your config and hud too

**Comment by em92** [comment]
> Are you sure you really use a recent Q3e build?

Yes.

> Btw, does the issue also happen to you if you use the Vulkan renderer?

No. But other issue happens:
![shot-20201019-180142](https://user-images.githubusercontent.com/15870400/96467011-ee984f00-1243-11eb-8176-f516259e407e.jpg)

> I'm still not able to reproduce it, make sure you're clean build directory before compilation, if it doesn't help - send me your config and hud too

I do `make clean` before `make`. `git diff` returns only diff above with Makefile. If I leave USE_SDL = 0, same bugs happen. `git log -1` returns this commit: https://github.com/ec-/Quake3e/commit/bd88c4f25e31abd01a54d869cebd7d1029aa39ab

q3config: https://pastebin.com/n7fbmzeD
hud (`gaiiahud01.cfg`): https://pastebin.com/QbdW1ppJ

Console dumps:
[opengl.txt](https://github.com/ec-/Quake3e/files/5402745/opengl.txt) `cl_renderer opengl`
[vk.txt](https://github.com/ec-/Quake3e/files/5402746/vk.txt)  `cl_renderer vulkan`

**Comment by ec-** [comment]
I suspect a driver bug there because I saw similar lightmap corruption on `lun3dm5` reported by other player, try with `\r_mergeLightmaps  0`
