### ISSUE TITLE
Vulkan: compiling with Cygwin shows a warning.

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#69]
When compiling the latest vulkan renderer, I receive this warning:: **-fPIC ignored for target (all code is position independent)**
This warning is displayed for multiple files (rendercommon, renderer, renderervk and even qcommon), for example:

**REND_CC **code/renderervk/shaders/spirv/st_frag.c**
code/renderervk/shaders/spirv/st_frag.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 const unsigned char st_frag_spv[] = {**

However, compiling is successful, even a working quake3e_vulkan_x86_64.dll renderer is created.
Compiled with Cygwin on Win 8.1 (64-bit).

Log output, building quake3 in build/release-mingw32-x86_64 (USE_VULKAN = 1):

  VERSION: 1.32e
  PLATFORM: mingw32
  ARCH: x86_64
  COMPILE_PLATFORM: cygwin
  COMPILE_ARCH: x86_64
  WINDRES: /usr/bin/x86_64-w64-mingw32-windres
  CC: /usr/bin/x86_64-w64-mingw32-gcc

  CFLAGS:
    -DUSE_RENDERER_DLOPEN
    -DRENDERER_PREFIX="quake3e"
    -DUSE_CURL
    -DCURL_STATICLIB
    -DUSE_VULKAN_API
    -MMD
    -Wall
    -fno-strict-aliasing
    -Wimplicit
    -Wstrict-prototypes
    -DUSE_ICON
    -DMINGW=1
    -m64
    -Icode/libcurl/windows/include
    -DNDEBUG
    -O2
    -ffast-math
    -fstrength-reduce

  Output:
    build/release-mingw32-x86_64/quake3e.ded.x64.exe
    build/release-mingw32-x86_64/quake3e.x64.exe
    build/release-mingw32-x86_64/quake3e_opengl_x86_64.dll
    build/release-mingw32-x86_64/quake3e_vulkan_x86_64.dll

DED_CC code/server/sv_bot.c
DED_CC code/server/sv_client.c
DED_CC code/server/sv_ccmds.c
DED_CC code/server/sv_filter.c
DED_CC code/server/sv_game.c
DED_CC code/server/sv_init.c
DED_CC code/server/sv_main.c
DED_CC code/server/sv_net_chan.c
DED_CC code/server/sv_snapshot.c
DED_CC code/server/sv_world.c
DED_CC code/qcommon/cm_load.c
DED_CC code/qcommon/cm_patch.c
DED_CC code/qcommon/cm_polylib.c
DED_CC code/qcommon/cm_test.c
DED_CC code/qcommon/cm_trace.c
DED_CC code/qcommon/cmd.c
DED_CC code/qcommon/common.c
DED_CC code/qcommon/cvar.c
DED_CC code/qcommon/files.c
DED_CC code/qcommon/history.c
DED_CC code/qcommon/keys.c
DED_CC code/qcommon/md4.c
DED_CC code/qcommon/md5.c
DED_CC code/qcommon/msg.c
DED_CC code/qcommon/net_chan.c
DED_CC code/qcommon/net_ip.c
DED_CC code/qcommon/huffman.c
DED_CC code/qcommon/huffman_static.c
DED_CC code/qcommon/q_math.c
DED_CC code/qcommon/q_shared.c
DED_CC code/qcommon/unzip.c
DED_CC code/qcommon/vm.c
DED_CC code/qcommon/vm_interpreted.c
...
LD build/release-mingw32-x86_64/quake3e.x64.exe
REND_CC code/renderer/tr_animation.c
code/renderer/tr_animation.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_arb.c
code/renderer/tr_arb.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 #include "tr_local.h"
 ^
REND_CC code/renderer/tr_backend.c
code/renderer/tr_backend.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_bsp.c
code/renderer/tr_bsp.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_cmds.c
code/renderer/tr_cmds.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_curve.c
code/renderer/tr_curve.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_flares.c
code/renderer/tr_flares.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_font.c
code/renderercommon/tr_font.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderer/tr_image.c
code/renderer/tr_image.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_image_png.c
code/renderercommon/tr_image_png.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_image_jpg.c
code/renderercommon/tr_image_jpg.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_image_bmp.c
code/renderercommon/tr_image_bmp.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_image_tga.c
code/renderercommon/tr_image_tga.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/renderercommon/tr_image_pcx.c
code/renderercommon/tr_image_pcx.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
...
REND_CC code/qcommon/puff.c
code/qcommon/puff.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
REND_CC code/qcommon/q_math.c
code/qcommon/q_math.c:1:0: warning: -fPIC ignored for target (all code is position independent)
 /*
 ^
...
LD build/release-mingw32-x86_64/quake3e_vulkan_x86_64.dll
$

**Comment by ensiform** [comment]
Guessing you can safely remove the compiler option then if cygwin is detected in makefile

**Comment by ec-** [comment]
Try removing `-fPIC` for `SHLIBCFLAGS`

**Comment by KuehnhammerTobias** [comment]
Yes, removing -fPIC will avoid the warning.
I'm always a little worried about just ignoring a warning.
Thanks to you both, closing this issue now.
