### ISSUE TITLE
Feature request: Follow IP command

### ISSUE THREAD

**Issue by daffymahman** [ec-/Quake3e#7]
When you jump around servers a lot it would be nice to able to just type /followip or something to connect to the last IP or server address someone wrote in console.

Thanks for your hard work!

**Comment by q3superman** [comment]
you can navigate in the console history by pressing the "arrow up" key in the active console

**Comment by daffymahman** [comment]
> you can navigate in the console history by pressing the "arrow up" key in the active console

That is only for what you've written yourself.

I'm referring to when someone else writes an IP in chat and you want to connect to that address, right you'll need to write (since you can't copy from console) /connect 127.0.0.1:27601;password abc and so forth.

So my request is to have a command, /followip, that will parse the console for the last server address and connect to that automatically.

**Comment by ensiform** [comment]
Sounds like a mod feature to parse chat logs to me.

**Comment by q3superman** [comment]
i think that could be done with a console log file but i personally ain't a friend of log files since they destroy your hd with time, especially ssd's.

**Comment by garoto** [comment]
My 40GB Intel SSD from 2010 used as my main C: drive begs to disagree.
