### ISSUE TITLE
`Hunk_Alloc failed` and game restarts

### ISSUE THREAD

**Issue by ribx** [ec-/Quake3e#72]
I am playing since around 6 months, recompile the master from time to time. But experience this error from time to time:

```
********************
ERROR: Hunk_Alloc failed on 403648
********************
forcefully unloading cgame vm
RE_Shutdown( 0 )
Hunk_Clear: reset the hunk ok
```

Then the system restart.

I am on a laptop with Gentoo Linux,
an Intel onboard grafic card (I think HD 4400),
```
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b)
```
default OpenGL renderer, low resolution, mesa 20.2.4.

I cannot reproduce the error, I just appears while playing from time to time.

What ever I can do to help, tell me. I can handle gdb roughly.

Off topic: Thanks for bringing this game back to life and back into my life. Had quite some fun with it in these terrible times! :kissing:

**Comment by ec-** [comment]
That's probably map-dependent, try to enter in console ```com_hunkMegs 256``` then restart engine
