### ISSUE TITLE
MOUSE4 and MOUSE5 have no effect on Linux

### ISSUE THREAD

**Issue by shapirus** [ec-/Quake3e#74]
Debian Testing.

I took my config that I used with ioquake3 where MOUSE4 and MOUSE5 work perfectly, and tried it with Quake3e, where it turned out that those buttons (side mouse buttons in my case) would not work.

Changing the in_mouse setting (tried everything between -1 and 2) did not affect it.

One interesting thing about it is that when I launch ioquake3 with the config that was read and updated by Quake3e, the two buttons in question stop working there too. They resume working after I restore the original config from backup. If it helps, I can send both configs for analysis.

**Comment by ensiform** [comment]
Are you compiling with SDL in the makefile?

Also, considering that quake3e is not based on modern ioquake3 you should not necessarily expect that the config files will transfer.

**Comment by shapirus** [comment]
Using or not using SDL had no effect on this, but it turned out that those two mouse buttons were bound to AUX1 and AUX2.

The issue is now solved for me, but it may be worth mentioning in the docs.

**Comment by ensiform** [comment]
The code explicitly points to using mouse4 and mouse5 binds regardless of SDL, so maybe your mouse driver is pointing the wrong buttons mapped at the OS level. Which X11 and SDL are picking up on which is why it is redirected to the aux binds.
