### ISSUE TITLE
Shader load issue on map mksteel

### ISSUE THREAD

**Issue by themuffinator** [ec-/Quake3e#76]
Hi,

We've recently discovered that the map mksteel shows up missing textures in newer builds of quake3e. This is not the case in older builds from a number of years ago, quake3.exe, ioq3, cnq3 etc..

The shader file does have a missing bracket, so I suppose the argument could be that quake3e has corrected the shader handling and the map is to blame but there could be other maps too in which this happens. Short of creating patches for maps, maybe there could be a work around in quake3e to detect issues when shaders don't load correctly?

**Comment by ensiform** [comment]
A missing bracket generally results in a major break in the original engine. Ioquake3 just drops your shader file completely if there's a bad bracket placement.

**Comment by Tigger-oN** [comment]
The problem with the shader on mksteel (from what I could see) was not a missing `}` but that the lack of a line return before the closing `}` on a number of lines.

There is no issue with this map with other tested engines.
