### ISSUE TITLE
Vulkan: random crash (error code -4).

### ISSUE THREAD

**Issue by KuehnhammerTobias** [ec-/Quake3e#77]
Sometimes Vulkan crahes with this error message:

----- Client Shutdown (Server fatal crashed: Vulkan: error code -4 returned by qvkWaitForFences( vk.device, 1, &vk.cmd->rendering_finished_fence, VK_FALSE, 1e10 )) -----
RE_Shutdown( 2 )
----- Client Shutdown (recursive error after: Vulkan: error code -4 returned by qvkWaitForFences( vk.device, 1, &vk.cmd->rendering_finished_fence, VK_FALSE, 1e10 )) -----
WARNING: Recursive CL_Shutdown()
recursive error after: Vulkan: error code -4 returned by qvkWaitForFences( vk.device, 1, &vk.cmd->rendering_finished_fence, VK_FALSE, 1e10 )
----- Client Shutdown (Server fatal crashed: Vulkan: error code -4 returned by qvkDeviceWaitIdle( vk.device )) -----
WARNING: Recursive CL_Shutdown()
----- Server Shutdown (Server fatal crashed: Vulkan: error code -4 returned by qvkDeviceWaitIdle( vk.device )) -----
==== ShutdownGame ====
AAS shutdown.
----- Client Shutdown (Vulkan: error code -4 returned by qvkDeviceWaitIdle( vk.device )) -----
WARNING: Recursive CL_Shutdown()
Vulkan: error code -4 returned by qvkDeviceWaitIdle( vk.device )
---------------------------
Unfortunately this crash isn't intentionally reproducible, last time it happend exactly after picking up the Quad and firing the first shot (though, I'm in doubt that the crash really relies on a specific game event).

**Comment by ec-** [comment]
Error code `-4` is equal to `VK_ERROR_DEVICE_LOST`, I need more info about your setup (OS/GPU/Drivers)

**Comment by KuehnhammerTobias** [comment]
Here it is:

OS: Windows 8.1 64-bit (everything up to date).
Intel i5-4670k 3.40 GHz
GPU: Nvidia GTX 1060 6GB Driver: 460.89.
16 GB RAM
2 x SATA

My Q3e is unmodified, with the exception I changed USE_VULKAN = 0 to USE_VULKAN = 1.
Compiling with 0 errors.
I installed Q3e on my second HDD (D:).
No OS energy management enabled.

Please let me know what other informations you need.

**Comment by ec-** [comment]
I cannot reproduce that. Is there any screen capture tools installed? I suspect than some other process is injecting vulkan commands into application

**Comment by KuehnhammerTobias** [comment]
Yeah, it's not possible to intentionally reproduce the crash, that makes it hard to gather more informations.
I have Fraps installed, I'm not sure if this will help us. Please let me know if you want me to install any specific screen capture tool ... or do think a screen capture tool will cause the trouble.

**Comment by ec-** [comment]
Can you run vulkan build with RenderDoc and capture at least one frame? I need to see screenshot of `Event Browser` window as I still asume there is some command injection from other process

**Comment by KuehnhammerTobias** [comment]
Jawoll! I will do, but need some time, because I don't know RenderDoc, I will dl, install, and capture at least one frame.

**Comment by KuehnhammerTobias** [comment]
Here is the log from RenderDoc. I'm not sure if this is what you need, please let me know if I did something wrong, I just started Q3e via RenderDoc.
[RenderDoc_2021.01.03_16.00.10.log](https://github.com/ec-/Quake3e/files/5761784/RenderDoc_2021.01.03_16.00.10.log)

**Comment by ec-** [comment]
I saw you launched opengl version, try vulkan, then press F12 in game, then close game

**Comment by KuehnhammerTobias** [comment]
Hm, sorry it seems I'm too stupid for you. What do you mean? Which one did I launch with the opengl version? If you mean Q3e, than, no I used Vulkan (at least the console says it is vulkan rendered, all the VK_ things are printed instead of GL_).
If you mean I launched RenderDoc in 'OpenGL' version, than I don't see any option (inside the RenderDoc menu) to launch it in 'Vulkan' version.

**Comment by KuehnhammerTobias** [comment]
Ok, here is the new log. I hope now everything is done correct. I launched Q3e from within RendererDoc (I don't set any additional parameters) and hit the 'Launch' button. I loaded q3dm4 added a few bots and hit F12.
The attached log is the new one created with Vulkan renderer set via cl_renderer command. During the game there was no crash.
I see an error in the log file (!!! ESTIMATED UPPER BOUND CHUNK LENGTH 96 EXCEEDED: 132. CAPTURE WILL BE CORRUPTED. !!!). I don't know if the capture was successful
[RenderDoc_2021.01.06_01.00.22.log](https://github.com/ec-/Quake3e/files/5773237/RenderDoc_2021.01.06_01.00.22.log)
 enough for you to see if there is some command injection from other process.

**Comment by ec-** [comment]
I need to see screenshot of `Event Browser` to see if there any other command buffers being recorded before ours

**Comment by KuehnhammerTobias** [comment]
The screenshot:
![eventBrowser](https://user-images.githubusercontent.com/5429387/103766879-e28c8400-501f-11eb-9e69-f64f743165e9.jpg)
Here is the corresponding .txt. file:
[eventBrowser .txt](https://github.com/ec-/Quake3e/files/5775652/eventBrowser.txt)

**Comment by ec-** [comment]
I see nothing suspicious, try to play and reproduce crash with recent sources

**Comment by KuehnhammerTobias** [comment]
I'll try. Thanks for your efforts.

**Comment by KuehnhammerTobias** [comment]
Looks good, no crash so far. Closing this issue now.
Thanks for fixing this issue, well done!
