### ISSUE TITLE
Defeating a tier boss on nightmare crashes the game on Windows

### ISSUE THREAD

**Issue by grepwood** [ec-/Quake3e#79]
As per thread title.

**Comment by KuehnhammerTobias** [comment]
Is there any error message shown, after the crash?

**Comment by grepwood** [comment]
@KuehnhammerTobias none whatsoever. This occurred during a Discord stream that my friend was doing.

**Comment by ensiform** [comment]
Can you produce a logfile from the game to see what mod is running and what the last messages are at least?

Run with `+set logfile 2`

It should produce qconsole.log in the folder where your configs are saved under the active mod folder or base.

**Comment by ec-** [comment]
Please confirm that this still happens with recent release

**Comment by AlexanderRevo** [comment]
At least on my machine it didn't happen for neither Hunter nor Sarge with the latest build.
