### ISSUE TITLE
fullscreen issues Linux

### ISSUE THREAD

**Issue by c1a0** [ec-/Quake3e#8]
I'm having issues running Q3 in fullscreen, both in the base game and CPMA mod. Until recently I skipped around the issue by using i3wm's fullscreen mode and killing any running compositor. Since switching over to gnome I can no longer do that, meaning I have to run Quake 3 in windowed mode for now.

Running the base game in fullscreen will span the game across both monitors (r_mode 19 for 1920x1080 is set), and doing the same in CPMA will render the game in a tiny box on the bottom left of my first monitor. I've got no idea why it's different between the two, and I've never figured out why it happens in the first place.

I have no idea if this is an easy or difficult fix for someone with knowledge of the engine, or if I'm doing something wrong to cause the issue for myself. If any more info is needed for a potential fix, please let me know.

**Comment by ec-** [comment]
Threre is no proper multimonitor support for linux atm, try to set **\r_modeFullscreen ""**, if it doesn't help - try **\r_mode -1** and set custom width/height

**Comment by c1a0** [comment]
Thanks for the reply, both of those methods work however the game is very dark and the refresh rate is incorrect on my setup. No bother though I'm quite happy to disable my second monitor when I play, It works fine at 120hz fullscreen with my second monitor disabled.

Any possibilty of multi-monitor being supported in the future on Linux? I imagine it ranks pretty low on your list of things to do but I thought I'd ask anyway.

**Comment by ec-** [comment]
I can't guarantee anything but if you know some good articles/examples of using xrandr X11 extension (or what is handles video modes/monitors setup) - it will help a lot

**Comment by ec-** [comment]
Should works now

**Comment by c1a0** [comment]
Thank you for this, works great with my setup!
