### ISSUE TITLE
Feature request: CNQ3 r_mapbrightness

### ISSUE THREAD

**Issue by themuffinator** [ec-/Quake3e#83]
Hi,

The way gamma is handled in q3e seems to be similar/same as in legacy Q3 - brightens the hw gamma resulting in a bright desktop in fullscreen or r_ignorehwgamma 1 to make the game look dull and flat. There's also the issue of the desktop gamma not resetting if the engine crashes.

CNQ3 seems to get around this, removing r_ignorehwgamma and overbrights. Would it not be beneficial to port into q3e?

Edit: This could also potentially fix the external lightmap issue.

**Comment by ensiform** [comment]
It is recommended to use r_fbo 1 in Q3e. Shader gamma is superior to desktop gamma problem. The game also resets gamma on some crashes unlike vanilla.

Please read documentation for changes.

**Comment by themuffinator** [comment]
Not saying it is legacy but rather behaved like it. r_fbo solves it, thanks.

Btw, brilliant work by everyone who helped developing the vulkan renderer, it gives insane performance boosts!
Closing this off.
