### ISSUE TITLE
Log Path Override Linux Dedicated Server?

### ISSUE THREAD

**Issue by own3mall** [ec-/Quake3e#88]
This isn't necessarily q3e related (since it happens in normal q3 Linux servers as well), but is there a way to change the write path for the hidden directory log and cache files?

Right now, admin.log, games.log, and other cache files are stored in /home/user_running_server/.q3a/

For example, could there be a cvar in the server config that sets a custom logging and cache directory?

With a game server path of `/games/q3e/server1/` I would like these files to be stored in `/games/q3e/server1/.q3a`.  Thus, in server.cfg, would it be possible to add support for something like:

```
set logpath="./"
```

The above setting would result in these cache and log files being stored in a .q3a directory local to the q3e executable's current path?  Thus, `/games/q3e/server1/.q3a`

or 

```
set logpath="myq3logs"
```

Would result in these files being written to `/games/q3e/server1/myq3logs`

If the cvar is not set, it could use its default behavior.

This would be a nice option to have since not all server instances are always run under different Linux user accounts.

**Comment by ec-** [comment]
Try different `fs_homepath`

**Comment by own3mall** [comment]
@ec- That worked.  I did not know that.  Thank you!
