### ISSUE TITLE
[feature request] some quality of life options

### ISSUE THREAD

**Issue by Riccardoman** [ec-/Quake3e#89]
-Can you possibly extend the number of maps supported in the skirmish menu? (not all the 280 maps I have are displayed) Like in this mod but more http://neogeographica.com/site/pages/mods/moremaps.html

-Extend the widescreen support also for the menu, especially for the skirmish mode so to have 18 maps displayed at once in the skirmish mode instead of the classic 8

-Add the option to start the next map (in alphabetical or random order) in the pause menu for the skirmish mode, so a new map loads instantly without the need to access the menu, or if not possible add the option to start a new map like in spearmint where you get instantly in the map selection menu

-Ability to change anisotropic, anti aliasing, aspect ratio, more modern resolution options, fps and fov settings directly in the graphics menu

**Comment by ec-** [comment]
All that is not related to engine, it is a mod-side functionality

**Comment by Riccardoman** [comment]
another idea that coult be releated to the engine: the possibility to disable the texture filtering without impacting how the reflections look ( pixelly textures, blurry reflections)

**Comment by ec-** [comment]
Too tricky for a very little benefit
