### ISSUE TITLE
Issue with rock textures in Endurance (q3gwdm2)

### ISSUE THREAD

**Issue by Riccardoman** [ec-/Quake3e#90]
![shot-20210213-125939](https://user-images.githubusercontent.com/74624503/107849432-6e51b700-6dfb-11eb-9b3a-d6bdebb611f6.jpg)
Quake 3 with only vanilla files
It is displayed correcly with Spearmint

Here's the culprit shader
[gwdm2.zip](https://github.com/ec-/Quake3e/files/5975605/gwdm2.zip)

**Comment by ec-** [comment]
Please record demo from that position, also specify what renderer is used (vulkan or opengl)

**Comment by Riccardoman** [comment]
Vulkan, it happens with your latest build
the previous builds work perfectly
In the other maps the alpha textures of some terrains gets intermitted

**Comment by ec-** [comment]
Please record demo from that POV, it is hard to understand where it happens

**Comment by Riccardoman** [comment]
I cannot reproduce it anymore, I changed something in the config without even thinking it would effect the result

I'll close this until I'll encounter the same issue
