### ISSUE TITLE
screenshot / printscreen square in vulkan 

### ISSUE THREAD

**Issue by Takkie** [ec-/Quake3e#92]
Hi,

I encountered this issue:
If I take a .bmp screenshot with vulkan renderer it saves it as a square (1080x1080).
If I use the openGl version it saves the .bmp screenshot in the right dimension (1920x1080).
I use the win-x86 version.

Regards,
Takkie

**Comment by ensiform** [comment]
Sound like copy paste bug on using wrong size variable 😄
