### ISSUE TITLE
Vulkan q3ctf4 tele

### ISSUE THREAD

**Issue by Takkie** [ec-/Quake3e#98]
Hi,
I am using the windows-x86-vulkan version.
When I play q3ctf4 (blue team) and want to use the left (blue-team) teleporter the game freezes. I tested it 3 times and it feezed 3 times. I have to alt-tab the game and end it 'manually'.
This behaviour doesn't happen with the quake3e renderer.
I encountered this issue on one other map: https://lvlworld.com/comments/id:477#n35373
but then I noticed it on q3ctf4 and it became an 'issue'.

**Comment by ec-** [comment]
Not reproducible for me, make sure you're using [latest build](https://github.com/ec-/Quake3e/releases/tag/latest)

**Comment by Takkie** [comment]
Hmm,
It is an issue with my config.
Although i haven't changed anything to it, suddenly it causes the game to freeze.
With a 'fresh' config the issue is gone.
I will build it up again.
Sorry for the inconvenience.

**Comment by ec-** [comment]
Can you try to reproduce your faulty config? That would be really useful to make engine more stable and predictable

**Comment by Takkie** [comment]
No problem.
I still have it. I'll post it here 'tomorrow'.

**Comment by Takkie** [comment]
Here's the faulty  q3takkie.cfg from my onedrive
https://1drv.ms/u/s!ArnrOxftqP-Hq0ZOYQyzDMk8yeVr

**Comment by ec-** [comment]
Plase, test now

**Comment by Takkie** [comment]
The new version fixed it.
There are no tele issues with my config (q3takkie.cfg) anymore.
I tested both maps.
Thanks
